//----------------------
// <auto-generated>
//     This code was generated by the Mockolate source generator.
//
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated!
// </auto-generated>
//----------------------

#nullable enable annotations
namespace Mockolate;

/// <summary>
///     Mock extensions for <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.
/// </summary>
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static partial class MockExtensionsForComprehensiveAbstractClass
{
	/// <inheritdoc cref="MockExtensionsForComprehensiveAbstractClass" />
	extension(global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass mock)
	{
		/// <summary>
		///     Gets the mock accessor for <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> - the entry point for configuring setups, verifying interactions and raising events.
		/// </summary>
		/// <remarks>
		///     The accessor is the bridge between the strongly-typed instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> returned by <c>CreateMock(...)</c> and the underlying mock registry where setups and recorded interactions live.<br />
		///     Through it you can:<br />
		///     <list type="bullet"><br />
		///       <item><description><c>Setup</c> - configure how members respond when invoked (<c>Returns</c>, <c>Throws</c>, <c>Do</c>, <c>InitializeWith</c>, ...).</description></item><br />
		///       <item><description><c>Verify</c> - assert how often (and in which order) members were invoked.</description></item><br />
		///       <item><description><c>SetupProtected</c> / <c>VerifyProtected</c> / <c>RaiseProtected</c> - target <see langword="protected" /> members on class mocks.</description></item><br />
		///       <item><description><c>InScenario</c> / <c>TransitionTo</c> - scope setups and behavior to a named scenario and switch between scenarios.</description></item><br />
		///       <item><description><c>Monitor</c>, <c>ClearAllInteractions</c>, <c>VerifyThatAllInteractionsAreVerified</c>, <c>VerifyThatAllSetupsAreUsed</c> - manage recorded interactions.</description></item><br />
		///       <item><description><c>VerifySetup</c> - verify how often a specific setup matched.</description></item><br />
		///     </list>
		/// </remarks>
		/// <exception cref="global::Mockolate.Exceptions.MockException">The instance is not a Mockolate-generated mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</exception>
		public global::Mockolate.Mock.IMockForComprehensiveAbstractClass Mock
		{
			get
			{
				if (mock is global::Mockolate.Mock.IMockForComprehensiveAbstractClass mockInterface)
				{
					return mockInterface;
				}
				throw new global::Mockolate.Exceptions.MockException("The subject is no mock.");
			}
		}

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> with the default <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.
		/// </summary>
		/// <remarks>
		///     The returned instance is a strongly-typed mock generated at compile time - it implements <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> and exposes the Mockolate surface through <c>.Mock</c>:<br />
		///     <list type="bullet"><br />
		///       <item><description><c>.Mock.Setup</c> configures how members respond (<c>Returns</c>, <c>Throws</c>, <c>Do</c>, <c>InitializeWith</c>, sequences, callbacks).</description></item><br />
		///       <item><description><c>.Mock.Verify</c> asserts how often and in which order members were invoked.</description></item><br />
		///     </list><br />
		///     With the default behavior, un-configured members return <c>default</c> values (empty collections / strings, completed tasks, <see langword="null" /> otherwise) and base-class implementations are invoked for class mocks. Use one of the overloads that accepts a <see cref="global::Mockolate.MockBehavior">MockBehavior</see> to customize this (for example to make un-configured calls throw or to skip the base class).<br />
		///     Overloads allow you to additionally pass constructor parameters (for class mocks), apply an initial <c>setup</c> callback before the instance is returned, or combine both.
		/// </remarks>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock()
			=> CreateMock(null, null, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> with the default <see cref="global::Mockolate.MockBehavior">MockBehavior</see>, applying the given <paramref name="setup" /> immediately.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup)
			=> CreateMock(null, setup, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> with the given <paramref name="mockBehavior" />.
		/// </summary>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior mockBehavior)
			=> CreateMock(mockBehavior, null, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> with the given <paramref name="mockBehavior" />, applying the given <paramref name="setup" /> immediately.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior mockBehavior, global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup)
			=> CreateMock(mockBehavior, setup, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given <paramref name="constructorParameters" /> to invoke the base-class constructor.
		/// </summary>
		/// <param name="constructorParameters">Values forwarded to a matching base-class constructor. Required when no parameterless constructor exists.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(object?[] constructorParameters)
			=> CreateMock(null, null, constructorParameters);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given <paramref name="mockBehavior" /> and <paramref name="constructorParameters" />.
		/// </summary>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="constructorParameters">Values forwarded to a matching base-class constructor. Required when no parameterless constructor exists.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior mockBehavior, object?[] constructorParameters)
			=> CreateMock(mockBehavior, null, constructorParameters);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> applying the given <paramref name="setup" /> immediately, using the given <paramref name="constructorParameters" />.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <param name="constructorParameters">Values forwarded to a matching base-class constructor. Required when no parameterless constructor exists.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup, object?[] constructorParameters)
			=> CreateMock(null, setup, constructorParameters);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(int, string)">ComprehensiveAbstractClass(int, string)</see> constructor.
		/// </summary>
		/// <param name="v">Value forwarded to the base-class constructor.</param>
		/// <param name="text">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(int v, string text = "x")
			=> CreateMock(null, null, new object?[] { v, text });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given <paramref name="mockBehavior" /> and the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(int, string)">ComprehensiveAbstractClass(int, string)</see> constructor.
		/// </summary>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="v">Value forwarded to the base-class constructor.</param>
		/// <param name="text">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior mockBehavior, int v, string text = "x")
			=> CreateMock(mockBehavior, null, new object?[] { v, text });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> applying the given <paramref name="setup" /> immediately, using the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(int, string)">ComprehensiveAbstractClass(int, string)</see> constructor.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <param name="v">Value forwarded to the base-class constructor.</param>
		/// <param name="text">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup, int v, string text = "x")
			=> CreateMock(null, setup, new object?[] { v, text });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given <paramref name="mockBehavior" />, applying the given <paramref name="setup" /> immediately, using the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(int, string)">ComprehensiveAbstractClass(int, string)</see> constructor.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <param name="v">Value forwarded to the base-class constructor.</param>
		/// <param name="text">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior mockBehavior, global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup, int v, string text = "x")
			=> CreateMock(mockBehavior, setup, new object?[] { v, text });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(int, bool)">ComprehensiveAbstractClass(int, bool)</see> constructor.
		/// </summary>
		/// <param name="mockRegistry">Value forwarded to the base-class constructor.</param>
		/// <param name="_">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(int mockRegistry, bool _)
			=> CreateMock(null, null, new object?[] { mockRegistry, _ });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given <paramref name="mockBehavior" /> and the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(int, bool)">ComprehensiveAbstractClass(int, bool)</see> constructor.
		/// </summary>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="mockRegistry">Value forwarded to the base-class constructor.</param>
		/// <param name="_">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior mockBehavior, int mockRegistry, bool _)
			=> CreateMock(mockBehavior, null, new object?[] { mockRegistry, _ });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> applying the given <paramref name="setup" /> immediately, using the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(int, bool)">ComprehensiveAbstractClass(int, bool)</see> constructor.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <param name="mockRegistry">Value forwarded to the base-class constructor.</param>
		/// <param name="_">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup, int mockRegistry, bool _)
			=> CreateMock(null, setup, new object?[] { mockRegistry, _ });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given <paramref name="mockBehavior" />, applying the given <paramref name="setup" /> immediately, using the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(int, bool)">ComprehensiveAbstractClass(int, bool)</see> constructor.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <param name="mockRegistry">Value forwarded to the base-class constructor.</param>
		/// <param name="_">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior mockBehavior, global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup, int mockRegistry, bool _)
			=> CreateMock(mockBehavior, setup, new object?[] { mockRegistry, _ });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(string)">ComprehensiveAbstractClass(string)</see> constructor.
		/// </summary>
		/// <param name="name">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(string name)
			=> CreateMock(null, null, new object?[] { name });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given <paramref name="mockBehavior" /> and the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(string)">ComprehensiveAbstractClass(string)</see> constructor.
		/// </summary>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="name">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior mockBehavior, string name)
			=> CreateMock(mockBehavior, null, new object?[] { name });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> applying the given <paramref name="setup" /> immediately, using the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(string)">ComprehensiveAbstractClass(string)</see> constructor.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <param name="name">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup, string name)
			=> CreateMock(null, setup, new object?[] { name });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given <paramref name="mockBehavior" />, applying the given <paramref name="setup" /> immediately, using the given constructor parameters to invoke the <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass(string)">ComprehensiveAbstractClass(string)</see> constructor.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <param name="name">Value forwarded to the base-class constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior mockBehavior, global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup, string name)
			=> CreateMock(mockBehavior, setup, new object?[] { name });

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> using the given <paramref name="mockBehavior" />, applying the given <paramref name="setup" /> immediately, using the given <paramref name="constructorParameters" />.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup, or <see langword="null" /> for <c>MockBehavior.Default</c>.</param>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned, or <see langword="null" /> to skip.</param>
		/// <param name="constructorParameters">Values forwarded to a matching base-class constructor, or <see langword="null" /> to use the parameterless constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.</returns>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMock(global::Mockolate.MockBehavior? mockBehavior, global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass>? setup, object?[]? constructorParameters)
		{
			if (mockBehavior is not null)
			{
				IMockBehaviorAccess mockBehaviorAccess = (global::Mockolate.IMockBehaviorAccess)mockBehavior;
				if (mockBehaviorAccess.TryGet<global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass>?>(out var additionalSetup))
				{
					if (setup is null)
					{
						setup = additionalSetup;
					}
					else
					{
						var originalSetup = setup;
						setup = s => { additionalSetup.Invoke(s); originalSetup.Invoke(s); };
					}
				}
				if (constructorParameters is null && mockBehaviorAccess.TryGetConstructorParameters<global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass>(out object?[]? parameters))
				{
					constructorParameters = parameters;
				}
			}

			mockBehavior ??= global::Mockolate.MockBehavior.Default;
			global::Mockolate.MockRegistry mockRegistry = new global::Mockolate.MockRegistry(mockBehavior, global::Mockolate.Mock.ComprehensiveAbstractClass.CreateFastInteractions(mockBehavior), constructorParameters);
			return CreateMockInstance(mockRegistry, constructorParameters, setup);
		}

		private static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass CreateMockInstance(global::Mockolate.MockRegistry mockRegistry, object?[]? constructorParameters, global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass>? setup)
		{
			if (constructorParameters is null || constructorParameters.Length == 0)
			{
				global::Mockolate.Mock.ComprehensiveAbstractClass.MockRegistryProvider.Value = mockRegistry;
				global::Mockolate.MockExtensionsForComprehensiveAbstractClass.MockSetup? setupTarget = null;
				if (setup is not null)
				{
					setupTarget ??= new(mockRegistry);
					setup.Invoke(setupTarget);
				}
				return new global::Mockolate.Mock.ComprehensiveAbstractClass(mockRegistry);
			}
			else if (constructorParameters.Length == 0)
			{
				global::Mockolate.Mock.ComprehensiveAbstractClass.MockRegistryProvider.Value = mockRegistry;
				global::Mockolate.MockExtensionsForComprehensiveAbstractClass.MockSetup? setupTarget = null;
				if (setup is not null)
				{
					setupTarget ??= new(mockRegistry);
					setup.Invoke(setupTarget);
				}
				return new global::Mockolate.Mock.ComprehensiveAbstractClass(mockRegistry);
			}
			else if (constructorParameters.Length >= 1 && constructorParameters.Length <= 2
			    && TryCast(constructorParameters, 0, mockRegistry.Behavior, out int c2p1)
			    && TryCastWithDefaultValue(constructorParameters, 1, "x", mockRegistry.Behavior, out string c2p2))
			{
				global::Mockolate.Mock.ComprehensiveAbstractClass.MockRegistryProvider.Value = mockRegistry;
				global::Mockolate.MockExtensionsForComprehensiveAbstractClass.MockSetup? setupTarget = null;
				if (setup is not null)
				{
					setupTarget ??= new(mockRegistry);
					setup.Invoke(setupTarget);
				}
				return new global::Mockolate.Mock.ComprehensiveAbstractClass(mockRegistry, c2p1, c2p2);
			}
			else if (constructorParameters.Length == 2
			    && TryCast(constructorParameters, 0, mockRegistry.Behavior, out int c3p1)
			    && TryCast(constructorParameters, 1, mockRegistry.Behavior, out bool c3p2))
			{
				global::Mockolate.Mock.ComprehensiveAbstractClass.MockRegistryProvider.Value = mockRegistry;
				global::Mockolate.MockExtensionsForComprehensiveAbstractClass.MockSetup? setupTarget = null;
				if (setup is not null)
				{
					setupTarget ??= new(mockRegistry);
					setup.Invoke(setupTarget);
				}
				return new global::Mockolate.Mock.ComprehensiveAbstractClass(mockRegistry, c3p1, c3p2);
			}
			else if (constructorParameters.Length == 1
			    && TryCast(constructorParameters, 0, mockRegistry.Behavior, out string c4p1))
			{
				global::Mockolate.Mock.ComprehensiveAbstractClass.MockRegistryProvider.Value = mockRegistry;
				global::Mockolate.MockExtensionsForComprehensiveAbstractClass.MockSetup? setupTarget = null;
				if (setup is not null)
				{
					setupTarget ??= new(mockRegistry);
					setup.Invoke(setupTarget);
				}
				return new global::Mockolate.Mock.ComprehensiveAbstractClass(mockRegistry, c4p1);
			}
			else
			{
				throw new global::Mockolate.Exceptions.MockException($"Could not find any constructor for 'Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass' that matches the {constructorParameters.Length} given parameters ({string.Join(", ", constructorParameters)}).");
			}
			static bool TryCast<TValue>(object?[] values, int index, global::Mockolate.MockBehavior behavior, out TValue result)
			{
			    var value = values[index];
				if (value is TValue typedValue)
				{
					result = typedValue;
					return true;
				}
				
				result = default!;
				return value is null;
			}
			static bool TryCastWithDefaultValue<TValue>(object?[] values, int index, TValue defaultValue, global::Mockolate.MockBehavior behavior, out TValue result)
			{
				if (values.Length > index && values[index] is TValue typedValue)
				{
					result = typedValue;
					return true;
				}
				
				result = defaultValue;
				return true;
			}
		}
		/// <summary>
		///     Creates a mock that wraps the given <paramref name="instance" />.
		/// </summary>
		/// <remarks>
		///     Public members on the mock forward to <paramref name="instance" /> unless overridden by a setup; protected members still go through the base-class implementation. All forwarded interactions are recorded and can be verified the same as on a plain mock.
		/// </remarks>
		/// <param name="instance">The real object whose calls should be forwarded. Must not be <see langword="null" />.</param>
		/// <returns>A new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> that delegates to <paramref name="instance" />.</returns>
		public global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass Wrapping(global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass instance)
		{
			if (mock is global::Mockolate.IMock mockInterface)
			{
				global::Mockolate.MockRegistry wrappingRegistry = new global::Mockolate.MockRegistry(mockInterface.MockRegistry, instance);
				wrappingRegistry = new global::Mockolate.MockRegistry(wrappingRegistry, global::Mockolate.Mock.ComprehensiveAbstractClass.CreateFastInteractions(wrappingRegistry.Behavior));
				return CreateMockInstance(wrappingRegistry, mockInterface.MockRegistry.ConstructorParameters, null);
			}
			throw new global::Mockolate.Exceptions.MockException("The subject is no mock.");
		}

	}

	/// <inheritdoc cref="MockExtensionsForComprehensiveAbstractClass" />
	extension(global::Mockolate.MockBehavior behavior)
	{
		/// <summary>
		///     Initializes mocks of type <typeparamref name="T" /> with the given <paramref name="setup" />.
		/// </summary>
		/// <remarks>
		///     The <paramref name="setup" /> is applied to the mock before the constructor is executed. Calling <c>Initialize</c> again overlays additional setups on top of any previously registered ones.
		/// </remarks>
		/// <typeparam name="T">The mockable type derived from <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> that this setup should apply to.</typeparam>
		/// <param name="setup">Callback invoked when a new mock of <typeparamref name="T" /> is created.</param>
		/// <returns>A new <see cref="global::Mockolate.MockBehavior">MockBehavior</see> with the registered initializer. The original instance is unchanged.</returns>
		public global::Mockolate.MockBehavior Initialize<T>(global::System.Action<IMockSetupInitializationForComprehensiveAbstractClass> setup)
			where T : global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass
		{
			var behaviorAccess = (global::Mockolate.IMockBehaviorAccess)behavior;
			return behaviorAccess.Set(setup);
		}
	}
	internal interface IMockSetupInitializationForComprehensiveAbstractClass : global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass
	{
		/// <summary>
		///     Setup protected members
		/// </summary>
		global::Mockolate.Mock.IMockProtectedSetupForComprehensiveAbstractClass Protected { get; }
	}

	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal sealed class MockSetup(global::Mockolate.MockRegistry mockRegistry) : global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass, global::Mockolate.Mock.IMockProtectedSetupForComprehensiveAbstractClass, IMockSetupInitializationForComprehensiveAbstractClass
	{
		/// <inheritdoc />
		global::Mockolate.Mock.IMockProtectedSetupForComprehensiveAbstractClass IMockSetupInitializationForComprehensiveAbstractClass.Protected => this;
		private global::Mockolate.MockRegistry MockRegistry { get; } = mockRegistry;

		#region IMockSetupForComprehensiveAbstractClass

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Setup.PropertySetup<int> global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass.V
		{
			get
			{
				var propertySetup = new global::Mockolate.Setup.PropertySetup<int>(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V");
				this.MockRegistry.SetupProperty(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Get, propertySetup);
				return propertySetup;
			}
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetup<int> global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass.A()
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<int>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_A, methodSetup);
			return methodSetup;
		}

		#endregion IMockSetupForComprehensiveAbstractClass

		#region IMockProtectedSetupForComprehensiveAbstractClass

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetup<int> global::Mockolate.Mock.IMockProtectedSetupForComprehensiveAbstractClass.P()
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<int>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_P, methodSetup);
			return methodSetup;
		}

		#endregion IMockProtectedSetupForComprehensiveAbstractClass
	}

	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class CovariantParameterAdapter<T>(global::Mockolate.Parameters.IParameter inner) : global::Mockolate.Parameters.IParameterMatch<T>
	{
		public bool Matches(T value) => inner.Matches(value);
		public void InvokeCallbacks(T value) => inner.InvokeCallbacks(value);
		public override string? ToString() => inner.ToString();

		public static global::Mockolate.Parameters.IParameterMatch<T> Wrap(global::Mockolate.Parameters.IParameter<T> parameter)
			=> parameter is global::Mockolate.Parameters.IParameterMatch<T> direct
				? direct
				: new CovariantParameterAdapter<T>(parameter);
	}
}

internal static partial class Mock
{
	/// <summary>
	///     A mock implementation for <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal class ComprehensiveAbstractClass :
		global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass, IMockForComprehensiveAbstractClass, IMockSetupForComprehensiveAbstractClass, IMockProtectedSetupForComprehensiveAbstractClass, global::Mockolate.MockExtensionsForComprehensiveAbstractClass.IMockSetupInitializationForComprehensiveAbstractClass, IMockVerifyForComprehensiveAbstractClass, IMockProtectedVerifyForComprehensiveAbstractClass,
		global::Mockolate.IMock
	{
		internal const int MemberId_V_Get = 0;
		internal const int MemberId_V_Set = 1;
		internal const int MemberId_A = 2;
		internal const int MemberId_P = 3;
		internal const int MemberCount = 4;
		internal static readonly global::Mockolate.Interactions.PropertyGetterAccess PropertyAccess_V_Get = new global::Mockolate.Interactions.PropertyGetterAccess("global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V");

		/// <summary>
		///     Creates a <see cref="global::Mockolate.Interactions.FastMockInteractions">FastMockInteractions</see> sized to <see cref="MemberCount">MemberCount</see> for use as the mock's interaction store.
		/// </summary>
		internal static global::Mockolate.Interactions.FastMockInteractions CreateFastInteractions(global::Mockolate.MockBehavior behavior)
		{
			global::Mockolate.Interactions.FastMockInteractions fast = new global::Mockolate.Interactions.FastMockInteractions(MemberCount, behavior.SkipInteractionRecording);
			global::Mockolate.Interactions.FastMethodBufferFactory.InstallMethod(fast, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_A);
			global::Mockolate.Interactions.FastMethodBufferFactory.InstallMethod(fast, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_P);
			global::Mockolate.Interactions.FastPropertyBufferFactory.InstallPropertyGetter(fast, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Get, global::Mockolate.Mock.ComprehensiveAbstractClass.PropertyAccess_V_Get);
			global::Mockolate.Interactions.FastPropertyBufferFactory.InstallPropertySetter<int>(fast, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Set);
			return fast;
		}

		/// <summary>
		///     Builds a <see cref="global::Mockolate.MockRegistry">MockRegistry</see> backed by a typed-buffer-sized <see cref="global::Mockolate.Interactions.FastMockInteractions">FastMockInteractions</see> from <paramref name="behavior" />.
		/// </summary>
		private static global::Mockolate.MockRegistry MockolateCreateRegistryFromBehavior(global::Mockolate.MockBehavior behavior)
		{
			global::Mockolate.MockRegistry registry = new global::Mockolate.MockRegistry(behavior, CreateFastInteractions(behavior));
			MockRegistryProvider.Value = registry;
			return registry;
		}

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.MockRegistry global::Mockolate.IMock.MockRegistry => this.MockRegistry;
		private global::Mockolate.MockRegistry MockRegistry
		{
			get => field ?? MockRegistryProvider.Value;
			set;
		}
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		internal static readonly global::System.Threading.AsyncLocal<global::Mockolate.MockRegistry> MockRegistryProvider = new global::System.Threading.AsyncLocal<global::Mockolate.MockRegistry>();

		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		private global::Mockolate.Interactions.FastMethod0Buffer MockolateBuffer_A
			=> field ?? (field = (global::Mockolate.Interactions.FastMethod0Buffer)((global::Mockolate.Interactions.FastMockInteractions)this.MockRegistry.Interactions).Buffers[global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_A]!);
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		private global::Mockolate.Interactions.FastMethod0Buffer MockolateBuffer_P
			=> field ?? (field = (global::Mockolate.Interactions.FastMethod0Buffer)((global::Mockolate.Interactions.FastMockInteractions)this.MockRegistry.Interactions).Buffers[global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_P]!);

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockSetupForComprehensiveAbstractClass IMockForComprehensiveAbstractClass.Setup
			=> this;
		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockProtectedSetupForComprehensiveAbstractClass IMockForComprehensiveAbstractClass.SetupProtected
			=> this;
		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockProtectedSetupForComprehensiveAbstractClass global::Mockolate.MockExtensionsForComprehensiveAbstractClass.IMockSetupInitializationForComprehensiveAbstractClass.Protected
			=> this;
		/// <inheritdoc />
		IMockInScenarioForComprehensiveAbstractClass IMockForComprehensiveAbstractClass.InScenario(string scenario)
			=> new MockInScenarioForComprehensiveAbstractClass(this.MockRegistry, scenario);

		/// <inheritdoc />
		IMockForComprehensiveAbstractClass IMockForComprehensiveAbstractClass.InScenario(string scenario, global::System.Action<IMockInScenarioForComprehensiveAbstractClass> setup)
		{
			setup.Invoke(new MockInScenarioForComprehensiveAbstractClass(this.MockRegistry, scenario));
			return this;
		}

		/// <inheritdoc />
		IMockForComprehensiveAbstractClass IMockForComprehensiveAbstractClass.TransitionTo(string scenario)
		{
			this.MockRegistry.TransitionTo(scenario);
			return this;
		}
		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockVerifyForComprehensiveAbstractClass IMockForComprehensiveAbstractClass.Verify
			=> this;
		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockProtectedVerifyForComprehensiveAbstractClass IMockForComprehensiveAbstractClass.VerifyProtected
			=> this;
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveAbstractClass> IMockForComprehensiveAbstractClass.VerifySetup(global::Mockolate.Setup.IMethodSetup setup)
			=> this.MockRegistry.Method<IMockVerifyForComprehensiveAbstractClass>(this, setup);
		/// <inheritdoc />
		bool IMockForComprehensiveAbstractClass.VerifyThatAllInteractionsAreVerified()
			=> this.MockRegistry.Interactions.GetUnverifiedInteractions().Count == 0;
		/// <inheritdoc />
		bool IMockForComprehensiveAbstractClass.VerifyThatAllSetupsAreUsed()
			=> this.MockRegistry.GetUnusedSetups(this.MockRegistry.Interactions).Count == 0;
		/// <inheritdoc />
		void IMockForComprehensiveAbstractClass.ClearAllInteractions()
			=> this.MockRegistry.ClearAllInteractions();
		/// <inheritdoc />
		global::Mockolate.Monitor.MockMonitor<IMockVerifyForComprehensiveAbstractClass> IMockForComprehensiveAbstractClass.Monitor()
			=> new global::Mockolate.Monitor.MockMonitor<IMockVerifyForComprehensiveAbstractClass>(this.MockRegistry.Interactions, interactions => new VerifyMonitorComprehensiveAbstractClass(new global::Mockolate.MockRegistry(this.MockRegistry, interactions)));

		/// <inheritdoc />
		string global::Mockolate.IMock.ToString()
			=> "Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass mock";

		/// <inheritdoc cref="ComprehensiveAbstractClass" />
		[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
		public ComprehensiveAbstractClass(global::Mockolate.MockRegistry mockRegistry)
			: base()
		{
			this.MockRegistry = mockRegistry;
		}

		/// <inheritdoc cref="ComprehensiveAbstractClass" />
		[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
		public ComprehensiveAbstractClass(global::Mockolate.MockBehavior behavior)
			: this(MockolateCreateRegistryFromBehavior(behavior))
		{
		}

		/// <inheritdoc cref="ComprehensiveAbstractClass" />
		[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
		public ComprehensiveAbstractClass(global::Mockolate.MockRegistry mockRegistry, int v, string text = "x")
			: base(v, text)
		{
			this.MockRegistry = mockRegistry;
		}

		/// <inheritdoc cref="ComprehensiveAbstractClass" />
		[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
		public ComprehensiveAbstractClass(global::Mockolate.MockBehavior behavior, int v, string text = "x")
			: this(MockolateCreateRegistryFromBehavior(behavior), v, text)
		{
		}

		/// <inheritdoc cref="ComprehensiveAbstractClass" />
		[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
		public ComprehensiveAbstractClass(global::Mockolate.MockRegistry mockRegistry_1, int mockRegistry, bool _)
			: base(mockRegistry, _)
		{
			this.MockRegistry = mockRegistry_1;
		}

		/// <inheritdoc cref="ComprehensiveAbstractClass" />
		[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
		public ComprehensiveAbstractClass(global::Mockolate.MockBehavior behavior, int mockRegistry, bool _)
			: this(MockolateCreateRegistryFromBehavior(behavior), mockRegistry, _)
		{
		}

		/// <inheritdoc cref="ComprehensiveAbstractClass" />
		[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
		public ComprehensiveAbstractClass(global::Mockolate.MockRegistry mockRegistry, string name)
			: base(name)
		{
			this.MockRegistry = mockRegistry;
		}

		/// <inheritdoc cref="ComprehensiveAbstractClass" />
		[global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
		public ComprehensiveAbstractClass(global::Mockolate.MockBehavior behavior, string name)
			: this(MockolateCreateRegistryFromBehavior(behavior), name)
		{
		}

		#region Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass

		/// <inheritdoc cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V" />
		public override int V
		{
			get
			{
				return this.MockRegistry.GetPropertyFast<int>(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Get, global::Mockolate.Mock.ComprehensiveAbstractClass.PropertyAccess_V_Get, static b => b.DefaultValue.Generate(default(int)!), this.MockRegistry.Wraps is global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass wraps ? () => wraps.V : () => base.V);
			}
			set
			{
				if (!this.MockRegistry.SetPropertyFast<int>(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Get, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Set, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V", value))
				{
					if (this.MockRegistry.Wraps is global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass wraps)
					{
						wraps.V = value;
					}
					else
					{
						base.V = value;
					}
				}
			}
		}

		/// <inheritdoc cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A()" />
		public override int A()
		{
			global::Mockolate.Setup.ReturnMethodSetup<int>? methodSetup = null;
			if (string.IsNullOrEmpty(this.MockRegistry.Scenario))
			{
				global::Mockolate.Setup.MethodSetup[]? snapshot_methodSetup = this.MockRegistry.GetMethodSetupSnapshot(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_A);
				if (snapshot_methodSetup is not null)
				{
					for (int i_methodSetup = snapshot_methodSetup.Length - 1; i_methodSetup >= 0; i_methodSetup--)
					{
						if (snapshot_methodSetup[i_methodSetup] is global::Mockolate.Setup.ReturnMethodSetup<int> s_methodSetup && s_methodSetup.Matches())
						{
							methodSetup = s_methodSetup;
							break;
						}
					}
				}
			}
			if (methodSetup is null)
			{
				foreach (global::Mockolate.Setup.ReturnMethodSetup<int> s_methodSetup in this.MockRegistry.GetMethodSetups<global::Mockolate.Setup.ReturnMethodSetup<int>>("global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A"))
				{
					if (s_methodSetup.Matches())
					{
						methodSetup = s_methodSetup;
						break;
					}
				}
			}
			bool hasWrappedResult = false;
			int wrappedResult = default!;
			if (this.MockRegistry.Behavior.SkipInteractionRecording == false)
			{
				this.MockolateBuffer_A.Append("global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A");
			}
			try
			{
				if (this.MockRegistry.Wraps is global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass wraps)
				{
					wrappedResult = wraps.A();
					hasWrappedResult = true;
				}
			}
			finally
			{
				methodSetup?.TriggerCallbacks();
			}
			if (methodSetup is null && !hasWrappedResult && this.MockRegistry.Behavior.ThrowWhenNotSetup)
			{
				throw new global::Mockolate.Exceptions.MockNotSetupException("The method 'global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A()' was invoked without prior setup.");
			}
			if (methodSetup?.HasReturnCallbacks != true && hasWrappedResult)
			{
				return wrappedResult;
			}
			return methodSetup?.TryGetReturnValue(out var returnValue) == true ? returnValue : this.MockRegistry.Behavior.DefaultValue.Generate(default(int)!);
		}

		/// <inheritdoc cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P()" />
		protected override int P()
		{
			global::Mockolate.Setup.ReturnMethodSetup<int>? methodSetup = null;
			if (string.IsNullOrEmpty(this.MockRegistry.Scenario))
			{
				global::Mockolate.Setup.MethodSetup[]? snapshot_methodSetup = this.MockRegistry.GetMethodSetupSnapshot(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_P);
				if (snapshot_methodSetup is not null)
				{
					for (int i_methodSetup = snapshot_methodSetup.Length - 1; i_methodSetup >= 0; i_methodSetup--)
					{
						if (snapshot_methodSetup[i_methodSetup] is global::Mockolate.Setup.ReturnMethodSetup<int> s_methodSetup && s_methodSetup.Matches())
						{
							methodSetup = s_methodSetup;
							break;
						}
					}
				}
			}
			if (methodSetup is null)
			{
				foreach (global::Mockolate.Setup.ReturnMethodSetup<int> s_methodSetup in this.MockRegistry.GetMethodSetups<global::Mockolate.Setup.ReturnMethodSetup<int>>("global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P"))
				{
					if (s_methodSetup.Matches())
					{
						methodSetup = s_methodSetup;
						break;
					}
				}
			}
			bool hasWrappedResult = false;
			int wrappedResult = default!;
			if (this.MockRegistry.Behavior.SkipInteractionRecording == false)
			{
				this.MockolateBuffer_P.Append("global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P");
			}
			try
			{
				if (!(methodSetup?.SkipBaseClass(this.MockRegistry.Behavior) ?? this.MockRegistry.Behavior.SkipBaseClass))
				{
					wrappedResult = base.P();
					hasWrappedResult = true;
				}
			}
			finally
			{
				methodSetup?.TriggerCallbacks();
			}
			if (methodSetup is null && !hasWrappedResult && this.MockRegistry.Behavior.ThrowWhenNotSetup)
			{
				throw new global::Mockolate.Exceptions.MockNotSetupException("The method 'global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P()' was invoked without prior setup.");
			}
			if (methodSetup?.HasReturnCallbacks != true && hasWrappedResult)
			{
				return wrappedResult;
			}
			return methodSetup?.TryGetReturnValue(out var returnValue) == true ? returnValue : this.MockRegistry.Behavior.DefaultValue.Generate(default(int)!);
		}

		#endregion Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass

		#region IMockSetupForComprehensiveAbstractClass

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Setup.PropertySetup<int> global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass.V
		{
			get
			{
				var propertySetup = new global::Mockolate.Setup.PropertySetup<int>(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V");
				this.MockRegistry.SetupProperty(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Get, propertySetup);
				return propertySetup;
			}
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetup<int> global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass.A()
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<int>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_A, methodSetup);
			return methodSetup;
		}

		#endregion IMockSetupForComprehensiveAbstractClass

		#region IMockProtectedSetupForComprehensiveAbstractClass

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetup<int> global::Mockolate.Mock.IMockProtectedSetupForComprehensiveAbstractClass.P()
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<int>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_P, methodSetup);
			return methodSetup;
		}

		#endregion IMockProtectedSetupForComprehensiveAbstractClass

		#region IMockVerifyForComprehensiveAbstractClass

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForComprehensiveAbstractClass, int> IMockVerifyForComprehensiveAbstractClass.V
		{
			get
			{
				return new global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForComprehensiveAbstractClass, int>(this, this.MockRegistry, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Get, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Set, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V");
			}
		}

		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveAbstractClass>.IgnoreParameters IMockVerifyForComprehensiveAbstractClass.A()
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveAbstractClass>(this, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_A, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A", () => $"A()");
		#endregion IMockVerifyForComprehensiveAbstractClass

		#region IMockProtectedVerifyForComprehensiveAbstractClass

		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockProtectedVerifyForComprehensiveAbstractClass>.IgnoreParameters IMockProtectedVerifyForComprehensiveAbstractClass.P()
			=> this.MockRegistry.VerifyMethod<IMockProtectedVerifyForComprehensiveAbstractClass>(this, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_P, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P", () => $"P()");
		#endregion IMockProtectedVerifyForComprehensiveAbstractClass
	}

	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class VerifyMonitorComprehensiveAbstractClass(global::Mockolate.MockRegistry mockRegistry) : global::Mockolate.Mock.IMockVerifyForComprehensiveAbstractClass
	{
		private global::Mockolate.MockRegistry MockRegistry { get; } = mockRegistry;

		#region IMockVerifyForComprehensiveAbstractClass

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForComprehensiveAbstractClass, int> IMockVerifyForComprehensiveAbstractClass.V
		{
			get
			{
				return new global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForComprehensiveAbstractClass, int>(this, this.MockRegistry, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Get, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Set, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V");
			}
		}

		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveAbstractClass>.IgnoreParameters IMockVerifyForComprehensiveAbstractClass.A()
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveAbstractClass>(this, global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_A, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A", () => $"A()");
		#endregion IMockVerifyForComprehensiveAbstractClass
	}

	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class MockInScenarioForComprehensiveAbstractClass : global::Mockolate.Mock.IMockInScenarioForComprehensiveAbstractClass, global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass, global::Mockolate.Mock.IMockProtectedSetupForComprehensiveAbstractClass
	{
		private global::Mockolate.MockRegistry MockRegistry { get; }
		private string _scenarioName;

		public MockInScenarioForComprehensiveAbstractClass(global::Mockolate.MockRegistry mockRegistry, string scenario)
		{
			this.MockRegistry = mockRegistry;
			_scenarioName = scenario;
		}

		/// <inheritdoc />
		global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass global::Mockolate.Mock.IMockInScenarioForComprehensiveAbstractClass.Setup
			=> this;

		/// <inheritdoc />
		global::Mockolate.Mock.IMockProtectedSetupForComprehensiveAbstractClass global::Mockolate.Mock.IMockInScenarioForComprehensiveAbstractClass.SetupProtected
			=> this;

		#region IMockSetupForComprehensiveAbstractClass

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Setup.PropertySetup<int> global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass.V
		{
			get
			{
				var propertySetup = new global::Mockolate.Setup.PropertySetup<int>(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V");
				this.MockRegistry.SetupProperty(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_V_Get, _scenarioName, propertySetup);
				return propertySetup;
			}
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetup<int> global::Mockolate.Mock.IMockSetupForComprehensiveAbstractClass.A()
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<int>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_A, _scenarioName, methodSetup);
			return methodSetup;
		}

		#endregion IMockSetupForComprehensiveAbstractClass

		#region IMockProtectedSetupForComprehensiveAbstractClass

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetup<int> global::Mockolate.Mock.IMockProtectedSetupForComprehensiveAbstractClass.P()
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<int>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveAbstractClass.MemberId_P, _scenarioName, methodSetup);
			return methodSetup;
		}

		#endregion IMockProtectedSetupForComprehensiveAbstractClass
	}

	/// <summary>
	///     The Mockolate accessor for a mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>, reached through <c>.Mock</c> on the mocked instance.
	/// </summary>
	/// <remarks>
	///     Groups every operation that acts on the mock rather than on the mocked subject: setups, verifications, event raising, scenarios and monitoring.
	/// </remarks>
	internal interface IMockForComprehensiveAbstractClass
	{
		/// <summary>
		///     Configures how members of the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> respond when invoked.
		/// </summary>
		/// <remarks>
		///     Each mocked member is available as a strongly-typed entry on this surface. Chain <c>Returns</c>, <c>ReturnsAsync</c>, <c>Throws</c>, <c>ThrowsAsync</c> or <c>Do</c> to control the response; chain <c>InitializeWith</c>/<c>Register</c> to initialize properties and indexers; chain multiple returns/throws to define a sequence; use <c>.For(n)</c>, <c>.Only(n)</c>, <c>.Forever()</c>, <c>.When(predicate)</c> to control when a callback runs.<br />
		///     When two setups overlap, the most recently defined one wins.
		/// </remarks>
		IMockSetupForComprehensiveAbstractClass Setup { get; }

		/// <summary>
		///     Configures how <see langword="protected" /> virtual members of the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> respond when invoked.
		/// </summary>
		/// <remarks>
		///     Only members declared as <see langword="protected" /> (or <see langword="protected" /> <see langword="internal" />) on the mocked class appear here. All setup chain operators (<c>Returns</c>, <c>Throws</c>, <c>Do</c>, sequences, <c>.For</c>/<c>.Only</c>/<c>.Forever</c>, ...) work identically to <see cref="Setup">Setup</see>.
		/// </remarks>
		IMockProtectedSetupForComprehensiveAbstractClass SetupProtected { get; }

		/// <summary>
		///     Opens a named scenario scope on the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> so that additional setups can be registered for that scenario.
		/// </summary>
		/// <remarks>
		///     Scenarios let you define per-state behavior. Setups registered inside the returned <c>IMockInScenarioFor...</c> scope only apply while the mock's current scenario matches <paramref name="scenario" />; switch scenarios with <see cref="TransitionTo">TransitionTo</see>.
		/// </remarks>
		/// <param name="scenario">Name of the scenario to enter. Any non-null string acts as a key; the mock starts in an unnamed default scenario.</param>
		/// <returns>A scoped accessor whose <c>Setup</c> (and <c>SetupProtected</c>, where applicable) register scenario-specific setups.</returns>
		IMockInScenarioForComprehensiveAbstractClass InScenario(string scenario);

		/// <summary>
		///     Opens a named scenario scope on the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> and immediately invokes <paramref name="setup" /> to register scenario-specific setups.
		/// </summary>
		/// <remarks>
		///     Equivalent to <c>InScenario(scenario)</c> followed by the setup callback, but returns the original <c>IMockFor...</c> accessor so it chains nicely at mock-creation time.
		/// </remarks>
		/// <param name="scenario">Name of the scenario to enter.</param>
		/// <param name="setup">Callback that receives the scenario-scoped setup surface and registers scenario-specific setups.</param>
		/// <returns>This accessor, to allow chaining.</returns>
		IMockForComprehensiveAbstractClass InScenario(string scenario, global::System.Action<IMockInScenarioForComprehensiveAbstractClass> setup);

		/// <summary>
		///     Switches the active scenario of the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> to <paramref name="scenario" />.
		/// </summary>
		/// <remarks>
		///     After the transition, setups registered via <see cref="InScenario(string)">InScenario(string)</see> under that scenario take effect. Scenarios that have no matching setup for a given member fall back to the default (un-scoped) setups.
		/// </remarks>
		/// <param name="scenario">Name of the scenario to transition to.</param>
		/// <returns>This accessor, to allow chaining.</returns>
		IMockForComprehensiveAbstractClass TransitionTo(string scenario);

		/// <summary>
		///     Asserts how often, and in which order, members of the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> were invoked.
		/// </summary>
		/// <remarks>
		///     Each call to a member here returns a <c>VerificationResult</c> that you terminate with a count assertion: <c>Never()</c>, <c>Once()</c>, <c>Twice()</c>, <c>Exactly(n)</c>, <c>AtLeast(n)</c>/<c>AtLeastOnce()</c>/<c>AtLeastTwice()</c>, <c>AtMost(n)</c>/<c>AtMostOnce()</c>/<c>AtMostTwice()</c>, <c>Between(min, max)</c> or <c>Times(predicate)</c>.<br />
		///     Use <c>Within(TimeSpan)</c> / <c>WithCancellation(CancellationToken)</c> before the terminator to wait for expected interactions that happen on background threads.<br />
		///     Chain <c>Then(...)</c> to assert an ordered sequence of calls. A failing assertion throws a <see cref="global::Mockolate.Exceptions.MockVerificationException">MockVerificationException</see>.
		/// </remarks>
		IMockVerifyForComprehensiveAbstractClass Verify { get; }

		/// <summary>
		///     Asserts how often, and in which order, <see langword="protected" /> members of the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> were invoked.
		/// </summary>
		/// <remarks>
		///     Same terminators and modifiers as <see cref="Verify">Verify</see> (<c>Once()</c>, <c>Exactly(n)</c>, <c>Within(...)</c>, <c>Then(...)</c>, ...); applies to <see langword="protected" /> members and events instead of public ones.
		/// </remarks>
		IMockProtectedVerifyForComprehensiveAbstractClass VerifyProtected { get; }

		/// <summary>
		///     Verifies how often a specific method setup was matched by actual invocations.
		/// </summary>
		/// <remarks>
		///     Useful when you want to verify &quot;this <em>particular</em> setup was hit N times&quot; without re-stating the matchers. Chain the usual count terminators (<c>Once()</c>, <c>AtLeastOnce()</c>, <c>Exactly(n)</c>, ...) on the returned result.
		/// </remarks>
		/// <param name="setup">The setup previously registered through <see cref="Setup">Setup</see> (typically returned from a <c>Returns(...)</c>/<c>Throws(...)</c> call).</param>
		/// <returns>A <c>VerificationResult</c> that counts invocations matching the given setup.</returns>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveAbstractClass> VerifySetup(global::Mockolate.Setup.IMethodSetup setup);

		/// <summary>
		///     Checks whether every recorded interaction on this mock has been observed by at least one <c>Verify</c> call.
		/// </summary>
		/// <remarks>
		///     Useful in test teardown to catch unexpected interactions (&quot;strict verification&quot;): if any recorded call has never been matched by a verification, the method returns <see langword="false" />.
		/// </remarks>
		/// <returns><see langword="true" /> if every recorded interaction was verified at least once; otherwise <see langword="false" />.</returns>
		bool VerifyThatAllInteractionsAreVerified();

		/// <summary>
		///     Checks whether every registered setup on this mock was matched by at least one actual invocation.
		/// </summary>
		/// <remarks>
		///     Useful to catch unused setups that silently rot as the test subject evolves.
		/// </remarks>
		/// <returns><see langword="true" /> if every registered setup was used at least once; otherwise <see langword="false" />.</returns>
		bool VerifyThatAllSetupsAreUsed();

		/// <summary>
		///     Removes every recorded interaction from this mock while keeping all registered setups intact.
		/// </summary>
		/// <remarks>
		///     Handy when a single test exercises multiple logical phases and you only want to verify the interactions of the latest phase.
		/// </remarks>
		void ClearAllInteractions();

		/// <summary>
		///     Creates a monitor whose <c>Verify</c> surface is scoped to interactions produced between <c>monitor.Run()</c> and the disposal of its <see cref="global::System.IDisposable">IDisposable</see> scope.
		/// </summary>
		/// <remarks>
		///     The underlying mock keeps recording all interactions as usual - only the monitor's <c>Verify</c> view is scoped. Useful to verify only the interactions produced by a specific block of test code without resetting the mock.
		/// </remarks>
		/// <returns>A <see cref="global::Mockolate.Monitor.MockMonitor{T}">MockMonitor&lt;T&gt;</see> that exposes <c>Verify</c> over the monitored interactions and a <c>Run()</c> method that opens the recording scope.</returns>
		global::Mockolate.Monitor.MockMonitor<IMockVerifyForComprehensiveAbstractClass> Monitor();
	}

	/// <summary>
	///     Scoped access to setups for a scenario on the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.
	/// </summary>
	internal interface IMockInScenarioForComprehensiveAbstractClass
	{
		/// <summary>
		///     Set up the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> within the scenario scope.
		/// </summary>
		IMockSetupForComprehensiveAbstractClass Setup { get; }

		/// <summary>
		///     Set up protected members of the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see> within the scenario scope.
		/// </summary>
		IMockProtectedSetupForComprehensiveAbstractClass SetupProtected { get; }
	}

	/// <summary>
	///     Set up the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.
	/// </summary>
	internal interface IMockSetupForComprehensiveAbstractClass : global::Mockolate.Setup.IMockSetup<global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass>
	{
		/// <summary>
		///     Setup for the int property <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V">V</see>.
		/// </summary>
		global::Mockolate.Setup.PropertySetup<int> V { get; }

		/// <summary>
		///     Setup for the method <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A()">A()</see>.
		/// </summary>
		[global::System.Runtime.CompilerServices.OverloadResolutionPriority(int.MaxValue)]
		global::Mockolate.Setup.IReturnMethodSetup<int> A();

	}

	/// <summary>
	///     Set up protected members for the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.
	/// </summary>
	internal interface IMockProtectedSetupForComprehensiveAbstractClass
	{
		/// <summary>
		///     Setup for the method <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P()">P()</see>.
		/// </summary>
		[global::System.Runtime.CompilerServices.OverloadResolutionPriority(int.MaxValue)]
		global::Mockolate.Setup.IReturnMethodSetup<int> P();

	}

	/// <summary>
	///     Verify interactions with the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.
	/// </summary>
	internal interface IMockVerifyForComprehensiveAbstractClass : global::Mockolate.Verify.IMockVerify<global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass>
	{
		/// <summary>
		///     Verify interactions with the int property <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.V">V</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForComprehensiveAbstractClass, int> V { get; }

		/// <summary>
		///     Verify invocations for the method <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.A()">A()</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveAbstractClass>.IgnoreParameters A();

	}

	/// <summary>
	///     Verify protected interactions with the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass">ComprehensiveAbstractClass</see>.
	/// </summary>
	internal interface IMockProtectedVerifyForComprehensiveAbstractClass
	{
		/// <summary>
		///     Verify invocations for the method <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveAbstractClass.P()">P()</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationResult<IMockProtectedVerifyForComprehensiveAbstractClass>.IgnoreParameters P();

	}
}

#nullable disable annotations
