//----------------------
// <auto-generated>
//     This code was generated by the Mockolate source generator.
//
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated!
// </auto-generated>
//----------------------

#nullable enable annotations
namespace Mockolate;

internal static partial class Mock
{
	/// <summary>
	///     A mock implementation for <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal class IStaticAbstractMembers :
		global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers, IMockForIStaticAbstractMembers, IMockSetupForIStaticAbstractMembers, IMockStaticSetupForIStaticAbstractMembers, IMockStaticRaiseOnIStaticAbstractMembers, IMockVerifyForIStaticAbstractMembers, IMockStaticVerifyForIStaticAbstractMembers,
		global::Mockolate.IMock
	{
		internal const int MemberId_AbstractStaticProperty_Get = 0;
		internal const int MemberId_AbstractStaticProperty_Set = 1;
		internal const int MemberId_VirtualStaticProperty_Get = 2;
		internal const int MemberId_VirtualStaticProperty_Set = 3;
		internal const int MemberId_AbstractStaticEvent_Subscribe = 4;
		internal const int MemberId_AbstractStaticEvent_Unsubscribe = 5;
		internal const int MemberId_AbstractStaticMethod = 6;
		internal const int MemberId_VirtualStaticMethod = 7;
		internal const int MemberCount = 8;
		internal static readonly global::Mockolate.Interactions.PropertyGetterAccess PropertyAccess_AbstractStaticProperty_Get = new global::Mockolate.Interactions.PropertyGetterAccess("global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticProperty");
		internal static readonly global::Mockolate.Interactions.PropertyGetterAccess PropertyAccess_VirtualStaticProperty_Get = new global::Mockolate.Interactions.PropertyGetterAccess("global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticProperty");

		/// <summary>
		///     Creates a <see cref="global::Mockolate.Interactions.FastMockInteractions">FastMockInteractions</see> sized to <see cref="MemberCount">MemberCount</see> for use as the mock's interaction store.
		///     Per-member buffers are not allocated up-front: the recording hot paths call <see cref="global::Mockolate.Interactions.FastMockInteractions.GetOrCreateBuffer{TBuffer}(int, global::System.Func{global::Mockolate.Interactions.FastMockInteractions, TBuffer})">GetOrCreateBuffer&lt;TBuffer&gt;(int, Func&lt;FastMockInteractions, TBuffer&gt;)</see> so a slot is materialized only when its member is first invoked.
		/// </summary>
		internal static global::Mockolate.Interactions.FastMockInteractions CreateFastInteractions(global::Mockolate.MockBehavior behavior)
			=> new global::Mockolate.Interactions.FastMockInteractions(MemberCount, behavior.SkipInteractionRecording);

		/// <summary>
		///     Builds a <see cref="global::Mockolate.MockRegistry">MockRegistry</see> backed by a typed-buffer-sized <see cref="global::Mockolate.Interactions.FastMockInteractions">FastMockInteractions</see> from <paramref name="behavior" />.
		/// </summary>
		private static global::Mockolate.MockRegistry MockolateCreateRegistryFromBehavior(global::Mockolate.MockBehavior behavior)
		{
			global::Mockolate.MockRegistry registry = new global::Mockolate.MockRegistry(behavior, CreateFastInteractions(behavior));
			MockRegistryProvider.Value = registry;
			return registry;
		}

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.MockRegistry global::Mockolate.IMock.MockRegistry => this.MockRegistry;
		private global::Mockolate.MockRegistry MockRegistry { get; }
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		internal static readonly global::System.Threading.AsyncLocal<global::Mockolate.MockRegistry> MockRegistryProvider = new global::System.Threading.AsyncLocal<global::Mockolate.MockRegistry>();


		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockSetupForIStaticAbstractMembers IMockForIStaticAbstractMembers.Setup
			=> this;
		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockStaticSetupForIStaticAbstractMembers IMockForIStaticAbstractMembers.SetupStatic
			=> this;
		/// <inheritdoc />
		IMockInScenarioForIStaticAbstractMembers IMockForIStaticAbstractMembers.InScenario(string scenario)
			=> new MockInScenarioForIStaticAbstractMembers(this.MockRegistry, scenario);

		/// <inheritdoc />
		IMockForIStaticAbstractMembers IMockForIStaticAbstractMembers.InScenario(string scenario, global::System.Action<IMockInScenarioForIStaticAbstractMembers> setup)
		{
			setup.Invoke(new MockInScenarioForIStaticAbstractMembers(this.MockRegistry, scenario));
			return this;
		}

		/// <inheritdoc />
		IMockForIStaticAbstractMembers IMockForIStaticAbstractMembers.TransitionTo(string scenario)
		{
			this.MockRegistry.TransitionTo(scenario);
			return this;
		}
		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockStaticRaiseOnIStaticAbstractMembers IMockForIStaticAbstractMembers.RaiseStatic
			=> this;
		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockVerifyForIStaticAbstractMembers IMockForIStaticAbstractMembers.Verify
			=> this;
		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockStaticVerifyForIStaticAbstractMembers IMockForIStaticAbstractMembers.VerifyStatic
			=> this;
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForIStaticAbstractMembers> IMockForIStaticAbstractMembers.VerifySetup(global::Mockolate.Setup.IMethodSetup setup)
			=> this.MockRegistry.Method<IMockVerifyForIStaticAbstractMembers>(this, setup);
		/// <inheritdoc />
		bool IMockForIStaticAbstractMembers.VerifyThatAllInteractionsAreVerified()
			=> this.MockRegistry.Interactions.GetUnverifiedInteractions().Count == 0;
		/// <inheritdoc />
		bool IMockForIStaticAbstractMembers.VerifyThatAllSetupsAreUsed()
			=> this.MockRegistry.GetUnusedSetups(this.MockRegistry.Interactions).Count == 0;
		/// <inheritdoc />
		void IMockForIStaticAbstractMembers.ClearAllInteractions()
			=> this.MockRegistry.ClearAllInteractions();
		/// <inheritdoc />
		global::Mockolate.Monitor.MockMonitor<IMockVerifyForIStaticAbstractMembers> IMockForIStaticAbstractMembers.Monitor()
			=> new global::Mockolate.Monitor.MockMonitor<IMockVerifyForIStaticAbstractMembers>(this.MockRegistry.Interactions, interactions => new VerifyMonitorIStaticAbstractMembers(new global::Mockolate.MockRegistry(this.MockRegistry, interactions)));

		/// <inheritdoc />
		string global::Mockolate.IMock.ToString()
			=> "Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers mock";

		/// <inheritdoc cref="IStaticAbstractMembers" />
		public IStaticAbstractMembers(global::Mockolate.MockRegistry mockRegistry)
		{
			this.MockRegistry = mockRegistry;
			MockRegistryProvider.Value = mockRegistry;
		}

		/// <inheritdoc cref="IStaticAbstractMembers" />
		public IStaticAbstractMembers(global::Mockolate.MockBehavior behavior)
			: this(MockolateCreateRegistryFromBehavior(behavior))
		{
		}

		#region Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers

		private static readonly global::System.Threading.AsyncLocal<global::System.Action<int>?> _mockolateEvent_global__Mockolate_Tests_GeneratorCoverage_IStaticAbstractMembers_AbstractStaticEvent = new global::System.Threading.AsyncLocal<global::System.Action<int>?>();
		/// <inheritdoc cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent" />
		public static event global::System.Action<int> AbstractStaticEvent
		{
			add
			{
				if (value is not null)
				{
					MockRegistryProvider.Value.AddEvent("global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent", value.Target, value.Method);
				}
				_mockolateEvent_global__Mockolate_Tests_GeneratorCoverage_IStaticAbstractMembers_AbstractStaticEvent.Value += value;
			}
			remove
			{
				if (value is not null)
				{
					MockRegistryProvider.Value.RemoveEvent("global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent", value.Target, value.Method);
				}
				_mockolateEvent_global__Mockolate_Tests_GeneratorCoverage_IStaticAbstractMembers_AbstractStaticEvent.Value -= value;
			}
		}

		/// <inheritdoc cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticProperty" />
		public static int AbstractStaticProperty
		{
			get
			{
				return MockRegistryProvider.Value.GetProperty<int>(global::Mockolate.Mock.IStaticAbstractMembers.PropertyAccess_AbstractStaticProperty_Get, () => MockRegistryProvider.Value.Behavior.DefaultValue.Generate(default(int)!), null);
			}
			set
			{
				MockRegistryProvider.Value.SetProperty<int>("global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticProperty", value);
			}
		}

		/// <inheritdoc cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticProperty" />
		public static int VirtualStaticProperty
		{
			get
			{
				return MockRegistryProvider.Value.GetProperty<int>(global::Mockolate.Mock.IStaticAbstractMembers.PropertyAccess_VirtualStaticProperty_Get, () => MockRegistryProvider.Value.Behavior.DefaultValue.Generate(default(int)!), null);
			}
		}

		/// <inheritdoc cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticMethod()" />
		public static int AbstractStaticMethod()
		{
			global::Mockolate.Setup.ReturnMethodSetup<int>? methodSetup = null;
			if (string.IsNullOrEmpty(MockRegistryProvider.Value.Scenario))
			{
				global::Mockolate.Setup.MethodSetup[]? snapshot_methodSetup = MockRegistryProvider.Value.GetMethodSetupSnapshot(global::Mockolate.Mock.IStaticAbstractMembers.MemberId_AbstractStaticMethod);
				if (snapshot_methodSetup is not null)
				{
					for (int i_methodSetup = snapshot_methodSetup.Length - 1; i_methodSetup >= 0; i_methodSetup--)
					{
						if (snapshot_methodSetup[i_methodSetup] is global::Mockolate.Setup.ReturnMethodSetup<int> s_methodSetup && s_methodSetup.Matches())
						{
							methodSetup = s_methodSetup;
							break;
						}
					}
				}
			}
			if (methodSetup is null)
			{
				foreach (global::Mockolate.Setup.ReturnMethodSetup<int> s_methodSetup in MockRegistryProvider.Value.GetMethodSetups<global::Mockolate.Setup.ReturnMethodSetup<int>>("global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticMethod"))
				{
					if (s_methodSetup.Matches())
					{
						methodSetup = s_methodSetup;
						break;
					}
				}
			}
			bool hasWrappedResult = false;
			int wrappedResult = default!;
			if (MockRegistryProvider.Value.Behavior.SkipInteractionRecording == false)
			{
				((global::Mockolate.Interactions.FastMockInteractions)MockRegistryProvider.Value.Interactions).GetOrCreateBuffer<global::Mockolate.Interactions.FastMethod0Buffer>(global::Mockolate.Mock.IStaticAbstractMembers.MemberId_AbstractStaticMethod, static fast => new global::Mockolate.Interactions.FastMethod0Buffer(fast)).Append("global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticMethod");
			}
			try
			{
			}
			finally
			{
				methodSetup?.TriggerCallbacks();
			}
			if (methodSetup is null && !hasWrappedResult && MockRegistryProvider.Value.Behavior.ThrowWhenNotSetup)
			{
				throw new global::Mockolate.Exceptions.MockNotSetupException("The method 'global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticMethod()' was invoked without prior setup.");
			}
			if (methodSetup?.HasReturnCallbacks != true && hasWrappedResult)
			{
				return wrappedResult;
			}
			return methodSetup?.TryGetReturnValue(out var returnValue) == true ? returnValue : MockRegistryProvider.Value.Behavior.DefaultValue.Generate(default(int)!);
		}

		/// <inheritdoc cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticMethod()" />
		public static int VirtualStaticMethod()
		{
			global::Mockolate.Setup.ReturnMethodSetup<int>? methodSetup = null;
			if (string.IsNullOrEmpty(MockRegistryProvider.Value.Scenario))
			{
				global::Mockolate.Setup.MethodSetup[]? snapshot_methodSetup = MockRegistryProvider.Value.GetMethodSetupSnapshot(global::Mockolate.Mock.IStaticAbstractMembers.MemberId_VirtualStaticMethod);
				if (snapshot_methodSetup is not null)
				{
					for (int i_methodSetup = snapshot_methodSetup.Length - 1; i_methodSetup >= 0; i_methodSetup--)
					{
						if (snapshot_methodSetup[i_methodSetup] is global::Mockolate.Setup.ReturnMethodSetup<int> s_methodSetup && s_methodSetup.Matches())
						{
							methodSetup = s_methodSetup;
							break;
						}
					}
				}
			}
			if (methodSetup is null)
			{
				foreach (global::Mockolate.Setup.ReturnMethodSetup<int> s_methodSetup in MockRegistryProvider.Value.GetMethodSetups<global::Mockolate.Setup.ReturnMethodSetup<int>>("global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticMethod"))
				{
					if (s_methodSetup.Matches())
					{
						methodSetup = s_methodSetup;
						break;
					}
				}
			}
			bool hasWrappedResult = false;
			int wrappedResult = default!;
			if (MockRegistryProvider.Value.Behavior.SkipInteractionRecording == false)
			{
				((global::Mockolate.Interactions.FastMockInteractions)MockRegistryProvider.Value.Interactions).GetOrCreateBuffer<global::Mockolate.Interactions.FastMethod0Buffer>(global::Mockolate.Mock.IStaticAbstractMembers.MemberId_VirtualStaticMethod, static fast => new global::Mockolate.Interactions.FastMethod0Buffer(fast)).Append("global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticMethod");
			}
			try
			{
			}
			finally
			{
				methodSetup?.TriggerCallbacks();
			}
			if (methodSetup is null && !hasWrappedResult && MockRegistryProvider.Value.Behavior.ThrowWhenNotSetup)
			{
				throw new global::Mockolate.Exceptions.MockNotSetupException("The method 'global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticMethod()' was invoked without prior setup.");
			}
			if (methodSetup?.HasReturnCallbacks != true && hasWrappedResult)
			{
				return wrappedResult;
			}
			return methodSetup?.TryGetReturnValue(out var returnValue) == true ? returnValue : MockRegistryProvider.Value.Behavior.DefaultValue.Generate(default(int)!);
		}

		#endregion Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers

		#region IMockSetupForIStaticAbstractMembers

		#endregion IMockSetupForIStaticAbstractMembers

		#region IMockStaticSetupForIStaticAbstractMembers

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Setup.PropertySetup<int> global::Mockolate.Mock.IMockStaticSetupForIStaticAbstractMembers.AbstractStaticProperty
		{
			get
			{
				var propertySetup = new global::Mockolate.Setup.PropertySetup<int>(MockRegistry, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticProperty");
				this.MockRegistry.SetupProperty(global::Mockolate.Mock.IStaticAbstractMembers.MemberId_AbstractStaticProperty_Get, propertySetup);
				return propertySetup;
			}
		}

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Setup.PropertySetup<int> global::Mockolate.Mock.IMockStaticSetupForIStaticAbstractMembers.VirtualStaticProperty
		{
			get
			{
				var propertySetup = new global::Mockolate.Setup.PropertySetup<int>(MockRegistry, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticProperty");
				this.MockRegistry.SetupProperty(global::Mockolate.Mock.IStaticAbstractMembers.MemberId_VirtualStaticProperty_Get, propertySetup);
				return propertySetup;
			}
		}

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Setup.EventSetup global::Mockolate.Mock.IMockStaticSetupForIStaticAbstractMembers.AbstractStaticEvent
		{
			get
			{
				global::Mockolate.Setup.EventSetup eventSetup = new global::Mockolate.Setup.EventSetup(MockRegistry, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent");
				this.MockRegistry.SetupEvent(global::Mockolate.Mock.IStaticAbstractMembers.MemberId_AbstractStaticEvent_Subscribe, eventSetup);
				return eventSetup;
			}
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetup<int> global::Mockolate.Mock.IMockStaticSetupForIStaticAbstractMembers.AbstractStaticMethod()
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<int>.WithParameterCollection(MockRegistry, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticMethod");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.IStaticAbstractMembers.MemberId_AbstractStaticMethod, methodSetup);
			return methodSetup;
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetup<int> global::Mockolate.Mock.IMockStaticSetupForIStaticAbstractMembers.VirtualStaticMethod()
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<int>.WithParameterCollection(MockRegistry, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticMethod");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.IStaticAbstractMembers.MemberId_VirtualStaticMethod, methodSetup);
			return methodSetup;
		}

		#endregion IMockStaticSetupForIStaticAbstractMembers

		#region IMockStaticRaiseOnIStaticAbstractMembers

		/// <inheritdoc />
		void IMockStaticRaiseOnIStaticAbstractMembers.AbstractStaticEvent(int obj)
		{
			_mockolateEvent_global__Mockolate_Tests_GeneratorCoverage_IStaticAbstractMembers_AbstractStaticEvent.Value?.Invoke(obj);
		}

		/// <inheritdoc />
		void IMockStaticRaiseOnIStaticAbstractMembers.AbstractStaticEvent(global::Mockolate.Parameters.IDefaultEventParameters parameters)
		{
			global::Mockolate.MockBehavior mockBehavior = MockRegistryProvider.Value.Behavior;
			_mockolateEvent_global__Mockolate_Tests_GeneratorCoverage_IStaticAbstractMembers_AbstractStaticEvent.Value?.Invoke(mockBehavior.DefaultValue.Generate(default(int)));
		}

		#endregion IMockStaticRaiseOnIStaticAbstractMembers

		#region IMockVerifyForIStaticAbstractMembers

		#endregion IMockVerifyForIStaticAbstractMembers

		#region IMockStaticVerifyForIStaticAbstractMembers

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Verify.VerificationPropertyResult<IMockStaticVerifyForIStaticAbstractMembers, int> IMockStaticVerifyForIStaticAbstractMembers.AbstractStaticProperty
		{
			get
			{
				return new global::Mockolate.Verify.VerificationPropertyResult<IMockStaticVerifyForIStaticAbstractMembers, int>(this, this.MockRegistry, -1, -1, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticProperty");
			}
		}

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Verify.VerificationPropertyResult<IMockStaticVerifyForIStaticAbstractMembers, int> IMockStaticVerifyForIStaticAbstractMembers.VirtualStaticProperty
		{
			get
			{
				return new global::Mockolate.Verify.VerificationPropertyResult<IMockStaticVerifyForIStaticAbstractMembers, int>(this, this.MockRegistry, -1, -1, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticProperty");
			}
		}

		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockStaticVerifyForIStaticAbstractMembers>.IgnoreParameters IMockStaticVerifyForIStaticAbstractMembers.AbstractStaticMethod()
			=> this.MockRegistry.VerifyMethod<IMockStaticVerifyForIStaticAbstractMembers>(this, global::Mockolate.Mock.IStaticAbstractMembers.MemberId_AbstractStaticMethod, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticMethod", () => $"AbstractStaticMethod()");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockStaticVerifyForIStaticAbstractMembers>.IgnoreParameters IMockStaticVerifyForIStaticAbstractMembers.VirtualStaticMethod()
			=> this.MockRegistry.VerifyMethod<IMockStaticVerifyForIStaticAbstractMembers>(this, global::Mockolate.Mock.IStaticAbstractMembers.MemberId_VirtualStaticMethod, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticMethod", () => $"VirtualStaticMethod()");
		/// <summary>
		///     Verify subscriptions on the AbstractStaticEvent event <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent">AbstractStaticEvent</see>.
		/// </summary>
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Verify.VerificationEventResult<IMockStaticVerifyForIStaticAbstractMembers> IMockStaticVerifyForIStaticAbstractMembers.AbstractStaticEvent
		{
			get
			{
				return new global::Mockolate.Verify.VerificationEventResult<IMockStaticVerifyForIStaticAbstractMembers>(this, this.MockRegistry, -1, -1, "global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent");
			}
		}

		#endregion IMockStaticVerifyForIStaticAbstractMembers
	}

	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class VerifyMonitorIStaticAbstractMembers(global::Mockolate.MockRegistry mockRegistry) : global::Mockolate.Mock.IMockVerifyForIStaticAbstractMembers
	{
		private global::Mockolate.MockRegistry MockRegistry { get; } = mockRegistry;

		#region IMockVerifyForIStaticAbstractMembers

		#endregion IMockVerifyForIStaticAbstractMembers
	}

	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class MockInScenarioForIStaticAbstractMembers : global::Mockolate.Mock.IMockInScenarioForIStaticAbstractMembers, global::Mockolate.Mock.IMockSetupForIStaticAbstractMembers
	{
		private global::Mockolate.MockRegistry MockRegistry { get; }
		private string _scenarioName;

		public MockInScenarioForIStaticAbstractMembers(global::Mockolate.MockRegistry mockRegistry, string scenario)
		{
			this.MockRegistry = mockRegistry;
			_scenarioName = scenario;
		}

		/// <inheritdoc />
		global::Mockolate.Mock.IMockSetupForIStaticAbstractMembers global::Mockolate.Mock.IMockInScenarioForIStaticAbstractMembers.Setup
			=> this;

		#region IMockSetupForIStaticAbstractMembers

		#endregion IMockSetupForIStaticAbstractMembers
	}

	/// <summary>
	///     The Mockolate accessor for a mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>, reached through <c>.Mock</c> on the mocked instance.
	/// </summary>
	/// <remarks>
	///     Groups every operation that acts on the mock rather than on the mocked subject: setups, verifications, event raising, scenarios and monitoring.
	/// </remarks>
	internal interface IMockForIStaticAbstractMembers
	{
		/// <summary>
		///     Configures how members of the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> respond when invoked.
		/// </summary>
		/// <remarks>
		///     Each mocked member is available as a strongly-typed entry on this surface. Chain <c>Returns</c>, <c>ReturnsAsync</c>, <c>Throws</c>, <c>ThrowsAsync</c> or <c>Do</c> to control the response; chain <c>InitializeWith</c>/<c>Register</c> to initialize properties and indexers; chain multiple returns/throws to define a sequence; use <c>.For(n)</c>, <c>.Only(n)</c>, <c>.Forever()</c>, <c>.When(predicate)</c> to control when a callback runs.<br />
		///     When two setups overlap, the most recently defined one wins.
		/// </remarks>
		IMockSetupForIStaticAbstractMembers Setup { get; }

		/// <summary>
		///     Configures how <see langword="static" /> members declared on <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> respond when invoked.
		/// </summary>
		/// <remarks>
		///     Static members are scoped per async/execution flow while the mock is alive; invocations from other flows are not intercepted.
		/// </remarks>
		IMockStaticSetupForIStaticAbstractMembers SetupStatic { get; }

		/// <summary>
		///     Opens a named scenario scope on the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> so that additional setups can be registered for that scenario.
		/// </summary>
		/// <remarks>
		///     Scenarios let you define per-state behavior. Setups registered inside the returned <c>IMockInScenarioFor...</c> scope only apply while the mock's current scenario matches <paramref name="scenario" />; switch scenarios with <see cref="TransitionTo">TransitionTo</see>.
		/// </remarks>
		/// <param name="scenario">Name of the scenario to enter. Any non-null string acts as a key; the mock starts in an unnamed default scenario.</param>
		/// <returns>A scoped accessor whose <c>Setup</c> (and <c>SetupProtected</c>, where applicable) register scenario-specific setups.</returns>
		IMockInScenarioForIStaticAbstractMembers InScenario(string scenario);

		/// <summary>
		///     Opens a named scenario scope on the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> and immediately invokes <paramref name="setup" /> to register scenario-specific setups.
		/// </summary>
		/// <remarks>
		///     Equivalent to <c>InScenario(scenario)</c> followed by the setup callback, but returns the original <c>IMockFor...</c> accessor so it chains nicely at mock-creation time.
		/// </remarks>
		/// <param name="scenario">Name of the scenario to enter.</param>
		/// <param name="setup">Callback that receives the scenario-scoped setup surface and registers scenario-specific setups.</param>
		/// <returns>This accessor, to allow chaining.</returns>
		IMockForIStaticAbstractMembers InScenario(string scenario, global::System.Action<IMockInScenarioForIStaticAbstractMembers> setup);

		/// <summary>
		///     Switches the active scenario of the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> to <paramref name="scenario" />.
		/// </summary>
		/// <remarks>
		///     After the transition, setups registered via <see cref="InScenario(string)">InScenario(string)</see> under that scenario take effect. Scenarios that have no matching setup for a given member fall back to the default (un-scoped) setups.
		/// </remarks>
		/// <param name="scenario">Name of the scenario to transition to.</param>
		/// <returns>This accessor, to allow chaining.</returns>
		IMockForIStaticAbstractMembers TransitionTo(string scenario);

		/// <summary>
		///     Triggers <see langword="static" /> events declared on <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> so that currently subscribed handlers are invoked.
		/// </summary>
		/// <remarks>
		///     Static events are scoped per async/execution flow while the mock is alive.
		/// </remarks>
		IMockStaticRaiseOnIStaticAbstractMembers RaiseStatic { get; }

		/// <summary>
		///     Asserts how often, and in which order, members of the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> were invoked.
		/// </summary>
		/// <remarks>
		///     Each call to a member here returns a <c>VerificationResult</c> that you terminate with a count assertion: <c>Never()</c>, <c>Once()</c>, <c>Twice()</c>, <c>Exactly(n)</c>, <c>AtLeast(n)</c>/<c>AtLeastOnce()</c>/<c>AtLeastTwice()</c>, <c>AtMost(n)</c>/<c>AtMostOnce()</c>/<c>AtMostTwice()</c>, <c>Between(min, max)</c> or <c>Times(predicate)</c>.<br />
		///     Use <c>Within(TimeSpan)</c> / <c>WithCancellation(CancellationToken)</c> before the terminator to wait for expected interactions that happen on background threads.<br />
		///     Chain <c>Then(...)</c> to assert an ordered sequence of calls. A failing assertion throws a <see cref="global::Mockolate.Exceptions.MockVerificationException">MockVerificationException</see>.
		/// </remarks>
		IMockVerifyForIStaticAbstractMembers Verify { get; }

		/// <summary>
		///     Asserts how often, and in which order, <see langword="static" /> members declared on <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> were invoked.
		/// </summary>
		/// <remarks>
		///     Same terminators and modifiers as <see cref="Verify">Verify</see>; scoped per async/execution flow in the same way as <see cref="SetupStatic">SetupStatic</see>.
		/// </remarks>
		IMockStaticVerifyForIStaticAbstractMembers VerifyStatic { get; }

		/// <summary>
		///     Verifies how often a specific method setup was matched by actual invocations.
		/// </summary>
		/// <remarks>
		///     Useful when you want to verify &quot;this <em>particular</em> setup was hit N times&quot; without re-stating the matchers. Chain the usual count terminators (<c>Once()</c>, <c>AtLeastOnce()</c>, <c>Exactly(n)</c>, ...) on the returned result.
		/// </remarks>
		/// <param name="setup">The setup previously registered through <see cref="Setup">Setup</see> (typically returned from a <c>Returns(...)</c>/<c>Throws(...)</c> call).</param>
		/// <returns>A <c>VerificationResult</c> that counts invocations matching the given setup.</returns>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForIStaticAbstractMembers> VerifySetup(global::Mockolate.Setup.IMethodSetup setup);

		/// <summary>
		///     Checks whether every recorded interaction on this mock has been observed by at least one <c>Verify</c> call.
		/// </summary>
		/// <remarks>
		///     Useful in test teardown to catch unexpected interactions (&quot;strict verification&quot;): if any recorded call has never been matched by a verification, the method returns <see langword="false" />.
		/// </remarks>
		/// <returns><see langword="true" /> if every recorded interaction was verified at least once; otherwise <see langword="false" />.</returns>
		bool VerifyThatAllInteractionsAreVerified();

		/// <summary>
		///     Checks whether every registered setup on this mock was matched by at least one actual invocation.
		/// </summary>
		/// <remarks>
		///     Useful to catch unused setups that silently rot as the test subject evolves.
		/// </remarks>
		/// <returns><see langword="true" /> if every registered setup was used at least once; otherwise <see langword="false" />.</returns>
		bool VerifyThatAllSetupsAreUsed();

		/// <summary>
		///     Removes every recorded interaction from this mock while keeping all registered setups intact.
		/// </summary>
		/// <remarks>
		///     Handy when a single test exercises multiple logical phases and you only want to verify the interactions of the latest phase.
		/// </remarks>
		void ClearAllInteractions();

		/// <summary>
		///     Creates a monitor whose <c>Verify</c> surface is scoped to interactions produced between <c>monitor.Run()</c> and the disposal of its <see cref="global::System.IDisposable">IDisposable</see> scope.
		/// </summary>
		/// <remarks>
		///     The underlying mock keeps recording all interactions as usual - only the monitor's <c>Verify</c> view is scoped. Useful to verify only the interactions produced by a specific block of test code without resetting the mock.
		/// </remarks>
		/// <returns>A <see cref="global::Mockolate.Monitor.MockMonitor{T}">MockMonitor&lt;T&gt;</see> that exposes <c>Verify</c> over the monitored interactions and a <c>Run()</c> method that opens the recording scope.</returns>
		global::Mockolate.Monitor.MockMonitor<IMockVerifyForIStaticAbstractMembers> Monitor();
	}

	/// <summary>
	///     Scoped access to setups for a scenario on the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.
	/// </summary>
	internal interface IMockInScenarioForIStaticAbstractMembers
	{
		/// <summary>
		///     Set up the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> within the scenario scope.
		/// </summary>
		IMockSetupForIStaticAbstractMembers Setup { get; }
	}

	/// <summary>
	///     Set up the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.
	/// </summary>
	internal interface IMockSetupForIStaticAbstractMembers
	{
	}

	/// <summary>
	///     Set up static members for the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.
	/// </summary>
	internal interface IMockStaticSetupForIStaticAbstractMembers
	{
		/// <summary>
		///     Setup for the int property <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticProperty">AbstractStaticProperty</see>.
		/// </summary>
		global::Mockolate.Setup.PropertySetup<int> AbstractStaticProperty { get; }

		/// <summary>
		///     Setup for the int property <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticProperty">VirtualStaticProperty</see>.
		/// </summary>
		global::Mockolate.Setup.PropertySetup<int> VirtualStaticProperty { get; }

		/// <summary>
		///     Setup for the event <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent">AbstractStaticEvent</see>.
		/// </summary>
		global::Mockolate.Setup.EventSetup AbstractStaticEvent { get; }

		/// <summary>
		///     Setup for the method <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticMethod()">AbstractStaticMethod()</see>.
		/// </summary>
		[global::System.Runtime.CompilerServices.OverloadResolutionPriority(int.MaxValue)]
		global::Mockolate.Setup.IReturnMethodSetup<int> AbstractStaticMethod();

		/// <summary>
		///     Setup for the method <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticMethod()">VirtualStaticMethod()</see>.
		/// </summary>
		[global::System.Runtime.CompilerServices.OverloadResolutionPriority(int.MaxValue)]
		global::Mockolate.Setup.IReturnMethodSetup<int> VirtualStaticMethod();

	}

	/// <summary>
	///     Raise static events on the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.
	/// </summary>
	internal interface IMockStaticRaiseOnIStaticAbstractMembers
	{
		/// <summary>
		///     Raise the <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent">AbstractStaticEvent</see> event.
		/// </summary>
		void AbstractStaticEvent(int obj);

		/// <summary>
		///     Raise the <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent">AbstractStaticEvent</see> event.
		/// </summary>
		void AbstractStaticEvent(global::Mockolate.Parameters.IDefaultEventParameters parameters);

	}

	/// <summary>
	///     Verify interactions with the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.
	/// </summary>
	internal interface IMockVerifyForIStaticAbstractMembers
	{
	}

	/// <summary>
	///     Verify static interactions with the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.
	/// </summary>
	internal interface IMockStaticVerifyForIStaticAbstractMembers
	{
		/// <summary>
		///     Verify interactions with the int property <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticProperty">AbstractStaticProperty</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationPropertyResult<IMockStaticVerifyForIStaticAbstractMembers, int> AbstractStaticProperty { get; }

		/// <summary>
		///     Verify interactions with the int property <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticProperty">VirtualStaticProperty</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationPropertyResult<IMockStaticVerifyForIStaticAbstractMembers, int> VirtualStaticProperty { get; }

		/// <summary>
		///     Verify invocations for the method <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticMethod()">AbstractStaticMethod()</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationResult<IMockStaticVerifyForIStaticAbstractMembers>.IgnoreParameters AbstractStaticMethod();

		/// <summary>
		///     Verify invocations for the method <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.VirtualStaticMethod()">VirtualStaticMethod()</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationResult<IMockStaticVerifyForIStaticAbstractMembers>.IgnoreParameters VirtualStaticMethod();

		/// <summary>
		///     Verify subscriptions on the AbstractStaticEvent event of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers.AbstractStaticEvent">AbstractStaticEvent</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationEventResult<IMockStaticVerifyForIStaticAbstractMembers> AbstractStaticEvent { get; }

	}
}
/// <summary>
///     Mock extensions for <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.
/// </summary>
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static partial class MockExtensionsForIStaticAbstractMembers
{
	/// <inheritdoc cref="MockExtensionsForIStaticAbstractMembers" />
	extension(global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers mock)
	{
		/// <summary>
		///     Gets the mock accessor for <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> - the entry point for configuring setups, verifying interactions and raising events.
		/// </summary>
		/// <remarks>
		///     The accessor is the bridge between the strongly-typed instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> returned by <c>CreateMock(...)</c> and the underlying mock registry where setups and recorded interactions live.<br />
		///     Through it you can:<br />
		///     <list type="bullet"><br />
		///       <item><description><c>Setup</c> - configure how members respond when invoked (<c>Returns</c>, <c>Throws</c>, <c>Do</c>, <c>InitializeWith</c>, ...).</description></item><br />
		///       <item><description><c>Verify</c> - assert how often (and in which order) members were invoked.</description></item><br />
		///       <item><description><c>SetupStatic</c> / <c>VerifyStatic</c> / <c>RaiseStatic</c> - target <see langword="static" /> members on interface mocks.</description></item><br />
		///       <item><description><c>InScenario</c> / <c>TransitionTo</c> - scope setups and behavior to a named scenario and switch between scenarios.</description></item><br />
		///       <item><description><c>Monitor</c>, <c>ClearAllInteractions</c>, <c>VerifyThatAllInteractionsAreVerified</c>, <c>VerifyThatAllSetupsAreUsed</c> - manage recorded interactions.</description></item><br />
		///       <item><description><c>VerifySetup</c> - verify how often a specific setup matched.</description></item><br />
		///     </list>
		/// </remarks>
		/// <exception cref="global::Mockolate.Exceptions.MockException">The instance is not a Mockolate-generated mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.</exception>
		public global::Mockolate.Mock.IMockForIStaticAbstractMembers Mock
		{
			get
			{
				if (mock is global::Mockolate.Mock.IMockForIStaticAbstractMembers mockInterface)
				{
					return mockInterface;
				}
				throw new global::Mockolate.Exceptions.MockException("The subject is no mock.");
			}
		}

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> with the default <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.
		/// </summary>
		/// <remarks>
		///     The returned instance is a strongly-typed mock generated at compile time - it implements <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> and exposes the Mockolate surface through <c>.Mock</c>:<br />
		///     <list type="bullet"><br />
		///       <item><description><c>.Mock.Setup</c> configures how members respond (<c>Returns</c>, <c>Throws</c>, <c>Do</c>, <c>InitializeWith</c>, sequences, callbacks).</description></item><br />
		///       <item><description><c>.Mock.Verify</c> asserts how often and in which order members were invoked.</description></item><br />
		///     </list><br />
		///     With the default behavior, un-configured members return <c>default</c> values (empty collections / strings, completed tasks, <see langword="null" /> otherwise) and base-class implementations are invoked for class mocks. Use one of the overloads that accepts a <see cref="global::Mockolate.MockBehavior">MockBehavior</see> to customize this (for example to make un-configured calls throw or to skip the base class).<br />
		///     Overloads allow you to additionally pass constructor parameters (for class mocks), apply an initial <c>setup</c> callback before the instance is returned, or combine both.
		/// </remarks>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.</returns>
		public static global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers CreateMock()
			=> CreateMock(null, null, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> with the default <see cref="global::Mockolate.MockBehavior">MockBehavior</see>, applying the given <paramref name="setup" /> immediately.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.</returns>
		public static global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers CreateMock(global::System.Action<global::Mockolate.Mock.IMockSetupForIStaticAbstractMembers> setup)
			=> CreateMock(null, setup, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> with the given <paramref name="mockBehavior" />.
		/// </summary>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.</returns>
		public static global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers CreateMock(global::Mockolate.MockBehavior mockBehavior)
			=> CreateMock(mockBehavior, null, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> with the given <paramref name="mockBehavior" />, applying the given <paramref name="setup" /> immediately.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.</returns>
		public static global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers CreateMock(global::Mockolate.MockBehavior mockBehavior, global::System.Action<global::Mockolate.Mock.IMockSetupForIStaticAbstractMembers> setup)
			=> CreateMock(mockBehavior, setup, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> using the given <paramref name="mockBehavior" />, applying the given <paramref name="setup" /> immediately, using the given <paramref name="constructorParameters" />.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup, or <see langword="null" /> for <c>MockBehavior.Default</c>.</param>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned, or <see langword="null" /> to skip.</param>
		/// <param name="constructorParameters">Values forwarded to a matching base-class constructor, or <see langword="null" /> to use the parameterless constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see>.</returns>
		private static global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers CreateMock(global::Mockolate.MockBehavior? mockBehavior, global::System.Action<global::Mockolate.Mock.IMockSetupForIStaticAbstractMembers>? setup, object?[]? constructorParameters)
		{
			if (mockBehavior is not null)
			{
				IMockBehaviorAccess mockBehaviorAccess = (global::Mockolate.IMockBehaviorAccess)mockBehavior;
				if (mockBehaviorAccess.TryGet<global::System.Action<global::Mockolate.Mock.IMockSetupForIStaticAbstractMembers>?>(out var additionalSetup))
				{
					if (setup is null)
					{
						setup = additionalSetup;
					}
					else
					{
						var originalSetup = setup;
						setup = s => { additionalSetup.Invoke(s); originalSetup.Invoke(s); };
					}
				}
			}

			mockBehavior ??= global::Mockolate.MockBehavior.Default;
			global::Mockolate.MockRegistry mockRegistry = new global::Mockolate.MockRegistry(mockBehavior, global::Mockolate.Mock.IStaticAbstractMembers.CreateFastInteractions(mockBehavior), constructorParameters);
			return CreateMockInstance(mockRegistry, constructorParameters, setup);
		}

		private static global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers CreateMockInstance(global::Mockolate.MockRegistry mockRegistry, object?[]? constructorParameters, global::System.Action<global::Mockolate.Mock.IMockSetupForIStaticAbstractMembers>? setup)
		{
			var value = new global::Mockolate.Mock.IStaticAbstractMembers(mockRegistry);
			if (setup is not null)
			{
				setup.Invoke(value);
			}
			return value;
		}
		/// <summary>
		///     Creates a mock that wraps the given <paramref name="instance" />.
		/// </summary>
		/// <remarks>
		///     Public members on the mock forward to <paramref name="instance" /> unless overridden by a setup; protected members still go through the base-class implementation. All forwarded interactions are recorded and can be verified the same as on a plain mock.
		/// </remarks>
		/// <param name="instance">The real object whose calls should be forwarded. Must not be <see langword="null" />.</param>
		/// <returns>A new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> that delegates to <paramref name="instance" />.</returns>
		public global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers Wrapping(global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers instance)
		{
			if (mock is global::Mockolate.IMock mockInterface)
			{
				global::Mockolate.MockRegistry wrappingRegistry = new global::Mockolate.MockRegistry(mockInterface.MockRegistry, instance);
				wrappingRegistry = new global::Mockolate.MockRegistry(wrappingRegistry, global::Mockolate.Mock.IStaticAbstractMembers.CreateFastInteractions(wrappingRegistry.Behavior));
				return CreateMockInstance(wrappingRegistry, mockInterface.MockRegistry.ConstructorParameters, null);
			}
			throw new global::Mockolate.Exceptions.MockException("The subject is no mock.");
		}

	}

	/// <inheritdoc cref="MockExtensionsForIStaticAbstractMembers" />
	extension(global::Mockolate.MockBehavior behavior)
	{
		/// <summary>
		///     Initializes mocks of type <typeparamref name="T" /> with the given <paramref name="setup" />.
		/// </summary>
		/// <remarks>
		///     The <paramref name="setup" /> is applied to the mock before the constructor is executed. Calling <c>Initialize</c> again overlays additional setups on top of any previously registered ones.
		/// </remarks>
		/// <typeparam name="T">The mockable type derived from <see cref="global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers">IStaticAbstractMembers</see> that this setup should apply to.</typeparam>
		/// <param name="setup">Callback invoked when a new mock of <typeparamref name="T" /> is created.</param>
		/// <returns>A new <see cref="global::Mockolate.MockBehavior">MockBehavior</see> with the registered initializer. The original instance is unchanged.</returns>
		public global::Mockolate.MockBehavior Initialize<T>(global::System.Action<global::Mockolate.Mock.IMockSetupForIStaticAbstractMembers> setup)
			where T : global::Mockolate.Tests.GeneratorCoverage.IStaticAbstractMembers
		{
			var behaviorAccess = (global::Mockolate.IMockBehaviorAccess)behavior;
			return behaviorAccess.Set(setup);
		}
	}

	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class CovariantParameterAdapter<T>(global::Mockolate.Parameters.IParameter inner) : global::Mockolate.Parameters.IParameterMatch<T>
	{
		public bool Matches(T value) => inner.Matches(value);
		public void InvokeCallbacks(T value) => inner.InvokeCallbacks(value);
		public override string? ToString() => inner.ToString();

		public static global::Mockolate.Parameters.IParameterMatch<T> Wrap(global::Mockolate.Parameters.IParameter<T> parameter)
			=> parameter is global::Mockolate.Parameters.IParameterMatch<T> direct
				? direct
				: new CovariantParameterAdapter<T>(parameter);
	}
}

#nullable disable annotations
