//----------------------
// <auto-generated>
//     This code was generated by the Mockolate source generator.
//
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated!
// </auto-generated>
//----------------------

namespace Mockolate;

#nullable enable

/// <summary>
///     Extensions for setting up return values and throwing exceptions for <see langword="async" /> methods.
/// </summary>
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static class ReturnsThrowsAsyncExtensions2
{
	/// <summary>
	///     Appends <paramref name="returnValue" /> to the sequence - the next matching invocation returns a completed
	///     <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see> carrying this value.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> ReturnsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> setup, TReturn returnValue)
		=> setup.Returns(global::System.Threading.Tasks.Task.FromResult(returnValue));

	/// <summary>
	///     Appends a lazy async return to the sequence; <paramref name="callback" /> is invoked on each matching
	///     invocation and its result is wrapped in a completed <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see>.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> ReturnsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Func<TReturn> callback)
		=> setup.Returns(() => global::System.Threading.Tasks.Task.FromResult(callback()));

	/// <summary>
	///     Appends a lazy async return that receives the method's arguments and produces the value wrapped in a
	///     completed <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see>.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> ReturnsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Func<T1, T2, T3, T4, T5, TReturn> callback)
		=> setup.Returns((v1, v2, v3, v4, v5) => global::System.Threading.Tasks.Task.FromResult(callback(v1, v2, v3, v4, v5)));

	/// <summary>
	///     Appends an entry that faults the returned <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see> with
	///     <paramref name="exception" /> so awaiting it throws.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> ThrowsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Exception exception)
		=> setup.Returns(global::System.Threading.Tasks.Task.FromException<TReturn>(exception));

	/// <summary>
	///     Appends an entry that invokes <paramref name="callback" /> to build the exception the returned
	///     <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see> is faulted with.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> ThrowsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Func<global::System.Exception> callback)
		=> setup.Returns(() => global::System.Threading.Tasks.Task.FromException<TReturn>(callback()));

	/// <summary>
	///     Appends an entry that invokes <paramref name="callback" /> with the method's arguments to build the
	///     exception the returned <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see> is faulted with.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> ThrowsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Func<T1, T2, T3, T4, T5, global::System.Exception> callback)
		=> setup.Returns((v1, v2, v3, v4, v5) => global::System.Threading.Tasks.Task.FromException<TReturn>(callback(v1, v2, v3, v4, v5)));

	/// <summary>
	///     Appends <paramref name="returnValue" /> to the sequence - the next matching invocation returns a completed
	///     <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see> carrying this value.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ReturnsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, TReturn returnValue)
		=> setup.Returns(global::System.Threading.Tasks.Task.FromResult(returnValue));

	/// <summary>
	///     Appends a lazy async return to the sequence; <paramref name="callback" /> is invoked on each matching
	///     invocation and its result is wrapped in a completed <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see>.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ReturnsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Func<TReturn> callback)
		=> setup.Returns(() => global::System.Threading.Tasks.Task.FromResult(callback()));

	/// <summary>
	///     Appends a lazy async return that receives the method's arguments and produces the value wrapped in a
	///     completed <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see>.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ReturnsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TReturn> callback)
		=> setup.Returns((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17) => global::System.Threading.Tasks.Task.FromResult(callback(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17)));

	/// <summary>
	///     Appends an entry that faults the returned <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see> with
	///     <paramref name="exception" /> so awaiting it throws.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ThrowsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Exception exception)
		=> setup.Returns(global::System.Threading.Tasks.Task.FromException<TReturn>(exception));

	/// <summary>
	///     Appends an entry that invokes <paramref name="callback" /> to build the exception the returned
	///     <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see> is faulted with.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ThrowsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Func<global::System.Exception> callback)
		=> setup.Returns(() => global::System.Threading.Tasks.Task.FromException<TReturn>(callback()));

	/// <summary>
	///     Appends an entry that invokes <paramref name="callback" /> with the method's arguments to build the
	///     exception the returned <see cref="global::System.Threading.Tasks.Task{TReturn}">Task&lt;TReturn&gt;</see> is faulted with.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ThrowsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::System.Threading.Tasks.Task<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, global::System.Exception> callback)
		=> setup.Returns((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17) => global::System.Threading.Tasks.Task.FromException<TReturn>(callback(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17)));

#if NET8_0_OR_GREATER

	/// <summary>
	///     Appends <paramref name="returnValue" /> to the sequence - the next matching invocation returns a completed
	///     <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see> carrying this value.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> ReturnsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> setup, TReturn returnValue)
		=> setup.Returns(global::System.Threading.Tasks.ValueTask.FromResult(returnValue));

	/// <summary>
	///     Appends a lazy async return to the sequence; <paramref name="callback" /> is invoked on each matching
	///     invocation and its result is wrapped in a completed <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see>.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> ReturnsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Func<TReturn> callback)
		=> setup.Returns(() => global::System.Threading.Tasks.ValueTask.FromResult(callback()));

	/// <summary>
	///     Appends a lazy async return that receives the method's arguments and produces the value wrapped in a
	///     completed <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see>.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> ReturnsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Func<T1, T2, T3, T4, T5, TReturn> callback)
		=> setup.Returns((v1, v2, v3, v4, v5) => global::System.Threading.Tasks.ValueTask.FromResult(callback(v1, v2, v3, v4, v5)));

	/// <summary>
	///     Appends an entry that faults the returned <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see> with
	///     <paramref name="exception" /> so awaiting it throws.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> ThrowsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Exception exception)
		=> setup.Returns(global::System.Threading.Tasks.ValueTask.FromException<TReturn>(exception));

	/// <summary>
	///     Appends an entry that invokes <paramref name="callback" /> to build the exception the returned
	///     <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see> is faulted with.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> ThrowsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Func<global::System.Exception> callback)
		=> setup.Returns(() => global::System.Threading.Tasks.ValueTask.FromException<TReturn>(callback()));

	/// <summary>
	///     Appends an entry that invokes <paramref name="callback" /> with the method's arguments to build the
	///     exception the returned <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see> is faulted with.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> ThrowsAsync<TReturn, T1, T2, T3, T4, T5>(this global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5> setup, global::System.Func<T1, T2, T3, T4, T5, global::System.Exception> callback)
		=> setup.Returns((v1, v2, v3, v4, v5) => global::System.Threading.Tasks.ValueTask.FromException<TReturn>(callback(v1, v2, v3, v4, v5)));

	/// <summary>
	///     Appends <paramref name="returnValue" /> to the sequence - the next matching invocation returns a completed
	///     <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see> carrying this value.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ReturnsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, TReturn returnValue)
		=> setup.Returns(global::System.Threading.Tasks.ValueTask.FromResult(returnValue));

	/// <summary>
	///     Appends a lazy async return to the sequence; <paramref name="callback" /> is invoked on each matching
	///     invocation and its result is wrapped in a completed <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see>.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ReturnsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Func<TReturn> callback)
		=> setup.Returns(() => global::System.Threading.Tasks.ValueTask.FromResult(callback()));

	/// <summary>
	///     Appends a lazy async return that receives the method's arguments and produces the value wrapped in a
	///     completed <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see>.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ReturnsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TReturn> callback)
		=> setup.Returns((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17) => global::System.Threading.Tasks.ValueTask.FromResult(callback(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17)));

	/// <summary>
	///     Appends an entry that faults the returned <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see> with
	///     <paramref name="exception" /> so awaiting it throws.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ThrowsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Exception exception)
		=> setup.Returns(global::System.Threading.Tasks.ValueTask.FromException<TReturn>(exception));

	/// <summary>
	///     Appends an entry that invokes <paramref name="callback" /> to build the exception the returned
	///     <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see> is faulted with.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ThrowsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetup<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Func<global::System.Exception> callback)
		=> setup.Returns(() => global::System.Threading.Tasks.ValueTask.FromException<TReturn>(callback()));

	/// <summary>
	///     Appends an entry that invokes <paramref name="callback" /> with the method's arguments to build the
	///     exception the returned <see cref="global::System.Threading.Tasks.ValueTask{TReturn}">ValueTask&lt;TReturn&gt;</see> is faulted with.
	/// </summary>
	/// <remarks>
	///     Call <c>ReturnsAsync</c>/<c>ThrowsAsync</c> multiple times to build a sequence; once exhausted it cycles
	///     back to the first entry unless the last one is followed by <c>.Forever()</c>.
	/// </remarks>
	public static global::Mockolate.Setup.IReturnMethodSetupReturnBuilder<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> ThrowsAsync<TReturn, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17>(this global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::System.Threading.Tasks.ValueTask<TReturn>, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> setup, global::System.Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, global::System.Exception> callback)
		=> setup.Returns((v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17) => global::System.Threading.Tasks.ValueTask.FromException<TReturn>(callback(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17)));

#endif
}
#nullable disable
