//----------------------
// <auto-generated>
//     This code was generated by the Mockolate source generator.
//
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated!
// </auto-generated>
//----------------------

#nullable enable

namespace Mockolate
{
	/// <summary>
	///     A setup or verify argument that is either an <see cref="global::Mockolate.It">It</see> matcher
	///     (<see cref="global::Mockolate.Parameters.IParameter{T}">IParameter&lt;T&gt;</see>) or a literal value of type <typeparamref name="T" />.
	/// </summary>
	/// <remarks>
	///     Both case types convert implicitly, so <c>Setup.Method(42)</c> and <c>Setup.Method(It.IsAny&lt;int&gt;())</c>
	///     bind to the same overload. A <see langword="default" /> instance stands for the literal <c>default(T)</c>.
	/// </remarks>
	[global::System.Runtime.CompilerServices.Union]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal readonly struct ParameterArg<T>
	{
		private const byte MatcherTag = 1;
		private const byte LiteralTag = 2;

		private readonly global::Mockolate.Parameters.IParameter<T>? _matcher;
		private readonly T? _literal;
		private readonly byte _tag;

		/// <summary>
		///     Creates the matcher case.
		/// </summary>
		public ParameterArg(global::Mockolate.Parameters.IParameter<T> matcher)
		{
			_matcher = matcher;
			_literal = default;
			_tag = MatcherTag;
		}

		/// <summary>
		///     Creates the literal value case.
		/// </summary>
		public ParameterArg(T? literal)
		{
			_matcher = null;
			_literal = literal;
			_tag = LiteralTag;
		}

		/// <summary>
		///     The contained matcher or literal value, boxed. Part of the union pattern; the generated mocks use the
		///     typed accessors instead.
		/// </summary>
		public object? Value => _tag switch
		{
			MatcherTag => _matcher,
			LiteralTag => _literal,
			_ => null,
		};

		/// <summary>
		///     <see langword="true" /> unless this is the <see langword="default" /> instance.
		/// </summary>
		public bool HasValue => _tag != 0;

		/// <summary>
		///     <see langword="true" /> when the argument is a literal value (including the <see langword="default" /> instance).
		/// </summary>
		public bool IsLiteral => _tag != MatcherTag;

		/// <summary>
		///     The literal value; <c>default(T)</c> for the matcher case and the <see langword="default" /> instance.
		/// </summary>
		public T? Literal => _literal;

		/// <summary>
		///     Gets the matcher, when this is the matcher case.
		/// </summary>
		public bool TryGetValue(out global::Mockolate.Parameters.IParameter<T>? matcher)
		{
			matcher = _matcher;
			return _tag == MatcherTag;
		}

		/// <summary>
		///     Gets the literal value, when this is the literal case.
		/// </summary>
		public bool TryGetValue(out T? literal)
		{
			literal = _literal;
			return _tag == LiteralTag;
		}

		/// <summary>
		///     The <see cref="global::Mockolate.Parameters.IParameterMatch{T}">IParameterMatch&lt;T&gt;</see> for this argument: the matcher itself,
		///     or an equality match for the literal value.
		/// </summary>
		public global::Mockolate.Parameters.IParameterMatch<T> ToParameterMatch()
		{
			if (_tag != MatcherTag)
			{
				return (global::Mockolate.Parameters.IParameterMatch<T>)global::Mockolate.It.IsValue<T>(_literal!);
			}

			if (_matcher is null)
			{
				return (global::Mockolate.Parameters.IParameterMatch<T>)global::Mockolate.It.IsNull<T>("null");
			}

			return _matcher is global::Mockolate.Parameters.IParameterMatch<T> direct
				? direct
				: new global::Mockolate.CovariantParameterAdapter<T>(_matcher);
		}

		/// <inheritdoc cref="object.ToString()" />
		public override string ToString() => _tag switch
		{
			MatcherTag => _matcher?.ToString() ?? "null",
			_ => _literal?.ToString() ?? "null",
		};
	}
}
#nullable disable