//----------------------
// <auto-generated>
//     This code was generated by the Mockolate source generator.
//
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated!
// </auto-generated>
//----------------------

#nullable enable
#if NET9_0_OR_GREATER

namespace Mockolate.Setup
{
	/// <summary>
	///     Ref-struct-compatible void setup for arity 5. Mirrors the hand-written arity 1-4 surface.
	/// </summary>
	public interface IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> : IMethodSetup
		where T1 : allows ref struct
		where T2 : allows ref struct
		where T3 : allows ref struct
		where T4 : allows ref struct
		where T5 : allows ref struct
	{
		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> SkippingBaseClass(bool skipBaseClass = true);
		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> DoesNotThrow();
		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> Throws<TException>() where TException : global::System.Exception, new();
		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> Throws(global::System.Exception exception);
		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> Throws(global::System.Func<global::System.Exception> exceptionFactory);
	}

	/// <summary>
	///     Concrete ref-struct-compatible void setup for arity 5. See <see cref="global::Mockolate.Setup.RefStructVoidMethodSetup{T}">RefStructVoidMethodSetup&lt;T&gt;</see>.
	/// </summary>
#if !DEBUG
#endif
	public sealed class RefStructVoidMethodSetup<T1, T2, T3, T4, T5> : global::Mockolate.Setup.MethodSetup, global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5>
		where T1 : allows ref struct
		where T2 : allows ref struct
		where T3 : allows ref struct
		where T4 : allows ref struct
		where T5 : allows ref struct
	{
		private readonly global::Mockolate.Parameters.IParameterMatch<T1>? _matcher1;
		private readonly global::Mockolate.Parameters.IParameterMatch<T2>? _matcher2;
		private readonly global::Mockolate.Parameters.IParameterMatch<T3>? _matcher3;
		private readonly global::Mockolate.Parameters.IParameterMatch<T4>? _matcher4;
		private readonly global::Mockolate.Parameters.IParameterMatch<T5>? _matcher5;
		private global::System.Func<global::System.Exception?>? _returnAction;
		private bool? _skipBaseClass;

		public RefStructVoidMethodSetup(string name, global::Mockolate.Parameters.IParameterMatch<T1>? matcher1 = null, global::Mockolate.Parameters.IParameterMatch<T2>? matcher2 = null, global::Mockolate.Parameters.IParameterMatch<T3>? matcher3 = null, global::Mockolate.Parameters.IParameterMatch<T4>? matcher4 = null, global::Mockolate.Parameters.IParameterMatch<T5>? matcher5 = null) : base(name)
		{
			_matcher1 = matcher1;
			_matcher2 = matcher2;
			_matcher3 = matcher3;
			_matcher4 = matcher4;
			_matcher5 = matcher5;
		}

		public bool Matches(T1 value1, T2 value2, T3 value3, T4 value4, T5 value5)
			=> (_matcher1 is null || _matcher1.Matches(value1))
			   && (_matcher2 is null || _matcher2.Matches(value2))
			   && (_matcher3 is null || _matcher3.Matches(value3))
			   && (_matcher4 is null || _matcher4.Matches(value4))
			   && (_matcher5 is null || _matcher5.Matches(value5));

		public void Invoke(T1 value1, T2 value2, T3 value3, T4 value4, T5 value5)
		{
			_matcher1?.InvokeCallbacks(value1);
			_matcher2?.InvokeCallbacks(value2);
			_matcher3?.InvokeCallbacks(value3);
			_matcher4?.InvokeCallbacks(value4);
			_matcher5?.InvokeCallbacks(value5);
			if (_returnAction is null)
			{
				return;
			}

			global::System.Exception? exception = _returnAction();
			if (exception is not null)
			{
				throw exception;
			}
		}

		public bool SkipBaseClass(global::Mockolate.MockBehavior behavior)
			=> _skipBaseClass ?? behavior.SkipBaseClass;

		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5>.SkippingBaseClass(bool skipBaseClass)
		{
			_skipBaseClass = skipBaseClass;
			return this;
		}

		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5>.DoesNotThrow()
		{
			_returnAction = static () => null;
			return this;
		}

		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5>.Throws<TException>()
		{
			_returnAction = static () => new TException();
			return this;
		}

		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5>.Throws(global::System.Exception exception)
		{
			_returnAction = () => exception;
			return this;
		}

		global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructVoidMethodSetup<T1, T2, T3, T4, T5>.Throws(global::System.Func<global::System.Exception> exceptionFactory)
		{
			_returnAction = exceptionFactory;
			return this;
		}

		protected override bool MatchesInteraction(global::Mockolate.Interactions.IMethodInteraction interaction)
			=> interaction is global::Mockolate.Interactions.RefStructMethodInvocation invocation && invocation.Name == Name;

		public override string ToString()
			=> $"void {Name}({_matcher1?.ToString() ?? $"<{typeof(T1).Name} ref struct>"}, {_matcher2?.ToString() ?? $"<{typeof(T2).Name} ref struct>"}, {_matcher3?.ToString() ?? $"<{typeof(T3).Name} ref struct>"}, {_matcher4?.ToString() ?? $"<{typeof(T4).Name} ref struct>"}, {_matcher5?.ToString() ?? $"<{typeof(T5).Name} ref struct>"})";
	}

	/// <summary>
	///     Ref-struct-compatible indexer getter setup for arity 5. Mirrors the hand-written arity 1-4 surface.
	/// </summary>
	public interface IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> : IMethodSetup
		where T1 : allows ref struct
		where T2 : allows ref struct
		where T3 : allows ref struct
		where T4 : allows ref struct
		where T5 : allows ref struct
	{
		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> SkippingBaseClass(bool skipBaseClass = true);
		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> Returns(TValue returnValue);
		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> Returns(global::System.Func<TValue> returnFactory);
		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> Throws<TException>() where TException : global::System.Exception, new();
		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> Throws(global::System.Exception exception);
		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> Throws(global::System.Func<global::System.Exception> exceptionFactory);
	}

	/// <summary>
	///     Concrete ref-struct-compatible indexer getter setup for arity 5. See <see cref="global::Mockolate.Setup.RefStructIndexerGetterSetup{TValue, T}">RefStructIndexerGetterSetup&lt;TValue, T&gt;</see>.
	/// </summary>
#if !DEBUG
#endif
	public sealed class RefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> : global::Mockolate.Setup.MethodSetup, global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>
		where T1 : allows ref struct
		where T2 : allows ref struct
		where T3 : allows ref struct
		where T4 : allows ref struct
		where T5 : allows ref struct
	{
		private readonly global::Mockolate.Parameters.IParameterMatch<T1>? _matcher1;
		private readonly global::Mockolate.Parameters.IParameterMatch<T2>? _matcher2;
		private readonly global::Mockolate.Parameters.IParameterMatch<T3>? _matcher3;
		private readonly global::Mockolate.Parameters.IParameterMatch<T4>? _matcher4;
		private readonly global::Mockolate.Parameters.IParameterMatch<T5>? _matcher5;
		private readonly global::Mockolate.Parameters.IRefStructProjectionMatch<T1>? _projection1;
		private readonly global::Mockolate.Parameters.IRefStructProjectionMatch<T2>? _projection2;
		private readonly global::Mockolate.Parameters.IRefStructProjectionMatch<T3>? _projection3;
		private readonly global::Mockolate.Parameters.IRefStructProjectionMatch<T4>? _projection4;
		private readonly global::Mockolate.Parameters.IRefStructProjectionMatch<T5>? _projection5;
		// The concrete leaf is an internal generic — the generator emits against the public base.
		private readonly global::Mockolate.Setup.IndexerValueStorage? _storage;
		private global::System.Func<TValue>? _returnFactory;
		private global::System.Func<global::System.Exception?>? _throwAction;
		private bool? _skipBaseClass;

		public RefStructIndexerGetterSetup(string name, global::Mockolate.Parameters.IParameterMatch<T1>? matcher1 = null, global::Mockolate.Parameters.IParameterMatch<T2>? matcher2 = null, global::Mockolate.Parameters.IParameterMatch<T3>? matcher3 = null, global::Mockolate.Parameters.IParameterMatch<T4>? matcher4 = null, global::Mockolate.Parameters.IParameterMatch<T5>? matcher5 = null) : base(name)
		{
			_matcher1 = matcher1;
			_matcher2 = matcher2;
			_matcher3 = matcher3;
			_matcher4 = matcher4;
			_matcher5 = matcher5;
			_projection1 = matcher1 as global::Mockolate.Parameters.IRefStructProjectionMatch<T1>;
			_projection2 = matcher2 as global::Mockolate.Parameters.IRefStructProjectionMatch<T2>;
			_projection3 = matcher3 as global::Mockolate.Parameters.IRefStructProjectionMatch<T3>;
			_projection4 = matcher4 as global::Mockolate.Parameters.IRefStructProjectionMatch<T4>;
			_projection5 = matcher5 as global::Mockolate.Parameters.IRefStructProjectionMatch<T5>;
			if (global::Mockolate.Setup.RefStructStorageHelper.IsSlotStorageReady(_projection1) && global::Mockolate.Setup.RefStructStorageHelper.IsSlotStorageReady(_projection2) && global::Mockolate.Setup.RefStructStorageHelper.IsSlotStorageReady(_projection3) && global::Mockolate.Setup.RefStructStorageHelper.IsSlotStorageReady(_projection4) && global::Mockolate.Setup.RefStructStorageHelper.IsSlotStorageReady(_projection5))
			{
				_storage = global::Mockolate.Setup.RefStructStorageHelper.CreateStorage<TValue>();
			}
		}

		public bool Matches(T1 value1, T2 value2, T3 value3, T4 value4, T5 value5)
			=> (_matcher1 is null || _matcher1.Matches(value1))
			   && (_matcher2 is null || _matcher2.Matches(value2))
			   && (_matcher3 is null || _matcher3.Matches(value3))
			   && (_matcher4 is null || _matcher4.Matches(value4))
			   && (_matcher5 is null || _matcher5.Matches(value5));

		internal bool TryGetStoredValue(T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, object? rawKey1, object? rawKey2, object? rawKey3, object? rawKey4, object? rawKey5, out TValue value)
		{
			if (_storage is null)
			{
				value = default!;
				return false;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection1, value1, rawKey1, out object key1))
			{
				value = default!;
				return false;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection2, value2, rawKey2, out object key2))
			{
				value = default!;
				return false;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection3, value3, rawKey3, out object key3))
			{
				value = default!;
				return false;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection4, value4, rawKey4, out object key4))
			{
				value = default!;
				return false;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection5, value5, rawKey5, out object key5))
			{
				value = default!;
				return false;
			}

			global::Mockolate.Setup.IndexerValueStorage? node = _storage.GetChildDispatch(key1)?.GetChildDispatch(key2)?.GetChildDispatch(key3)?.GetChildDispatch(key4)?.GetChildDispatch(key5);
			return global::Mockolate.Setup.RefStructStorageHelper.TryGetLeafValue<TValue>(node, out value);
		}

		internal void StoreValue(T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, TValue value, object? rawKey1, object? rawKey2, object? rawKey3, object? rawKey4, object? rawKey5)
		{
			if (_storage is null || !Matches(value1, value2, value3, value4, value5))
			{
				return;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection1, value1, rawKey1, out object key1))
			{
				return;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection2, value2, rawKey2, out object key2))
			{
				return;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection3, value3, rawKey3, out object key3))
			{
				return;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection4, value4, rawKey4, out object key4))
			{
				return;
			}

			if (!global::Mockolate.Setup.RefStructStorageHelper.TryResolveKey(_projection5, value5, rawKey5, out object key5))
			{
				return;
			}

			global::Mockolate.Setup.IndexerValueStorage leaf = _storage.GetOrAddChildDispatch(key1).GetOrAddChildDispatch(key2).GetOrAddChildDispatch(key3).GetOrAddChildDispatch(key4).GetOrAddChildDispatch(key5);
			global::Mockolate.Setup.RefStructStorageHelper.SetLeafValue<TValue>(leaf, value);
		}

		public TValue Invoke(T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, object? rawKey1 = null, object? rawKey2 = null, object? rawKey3 = null, object? rawKey4 = null, object? rawKey5 = null, global::System.Func<TValue>? defaultFactory = null)
		{
			_matcher1?.InvokeCallbacks(value1);
			_matcher2?.InvokeCallbacks(value2);
			_matcher3?.InvokeCallbacks(value3);
			_matcher4?.InvokeCallbacks(value4);
			_matcher5?.InvokeCallbacks(value5);
			if (_throwAction is not null)
			{
				global::System.Exception? exception = _throwAction();
				if (exception is not null)
				{
					throw exception;
				}
			}

			if (_storage is not null && TryGetStoredValue(value1, value2, value3, value4, value5, rawKey1, rawKey2, rawKey3, rawKey4, rawKey5, out TValue stored))
			{
				return stored;
			}

			if (_returnFactory is not null)
			{
				return _returnFactory();
			}

			return defaultFactory is not null ? defaultFactory() : default!;
		}

		public bool HasReturnValue => _returnFactory is not null || _storage is not null;

		public bool SkipBaseClass(global::Mockolate.MockBehavior behavior)
			=> _skipBaseClass ?? behavior.SkipBaseClass;

		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>.SkippingBaseClass(bool skipBaseClass)
		{
			_skipBaseClass = skipBaseClass;
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>.Returns(TValue returnValue)
		{
			_returnFactory = () => returnValue;
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>.Returns(global::System.Func<TValue> returnFactory)
		{
			_returnFactory = returnFactory;
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>.Throws<TException>()
		{
			_throwAction = static () => new TException();
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>.Throws(global::System.Exception exception)
		{
			_throwAction = () => exception;
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>.Throws(global::System.Func<global::System.Exception> exceptionFactory)
		{
			_throwAction = exceptionFactory;
			return this;
		}

		protected override bool MatchesInteraction(global::Mockolate.Interactions.IMethodInteraction interaction)
			=> interaction is global::Mockolate.Interactions.RefStructMethodInvocation invocation && invocation.Name == Name;

		public override string ToString()
			=> $"{typeof(TValue).Name} {Name}[{_matcher1?.ToString() ?? $"<{typeof(T1).Name} ref struct>"}, {_matcher2?.ToString() ?? $"<{typeof(T2).Name} ref struct>"}, {_matcher3?.ToString() ?? $"<{typeof(T3).Name} ref struct>"}, {_matcher4?.ToString() ?? $"<{typeof(T4).Name} ref struct>"}, {_matcher5?.ToString() ?? $"<{typeof(T5).Name} ref struct>"}]";
	}

	/// <summary>
	///     Ref-struct-compatible indexer setter setup for arity 5. Mirrors the hand-written arity 1-4 surface.
	/// </summary>
	public interface IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> : IMethodSetup
		where T1 : allows ref struct
		where T2 : allows ref struct
		where T3 : allows ref struct
		where T4 : allows ref struct
		where T5 : allows ref struct
	{
		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> SkippingBaseClass(bool skipBaseClass = true);
		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> OnSet(global::System.Action<TValue> callback);
		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> Throws<TException>() where TException : global::System.Exception, new();
		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> Throws(global::System.Exception exception);
		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> Throws(global::System.Func<global::System.Exception> exceptionFactory);
	}

	/// <summary>
	///     Concrete ref-struct-compatible indexer setter setup for arity 5. See <see cref="global::Mockolate.Setup.RefStructIndexerSetterSetup{TValue, T}">RefStructIndexerSetterSetup&lt;TValue, T&gt;</see>.
	/// </summary>
#if !DEBUG
#endif
	public sealed class RefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> : global::Mockolate.Setup.MethodSetup, global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>
		where T1 : allows ref struct
		where T2 : allows ref struct
		where T3 : allows ref struct
		where T4 : allows ref struct
		where T5 : allows ref struct
	{
		private readonly global::Mockolate.Parameters.IParameterMatch<T1>? _matcher1;
		private readonly global::Mockolate.Parameters.IParameterMatch<T2>? _matcher2;
		private readonly global::Mockolate.Parameters.IParameterMatch<T3>? _matcher3;
		private readonly global::Mockolate.Parameters.IParameterMatch<T4>? _matcher4;
		private readonly global::Mockolate.Parameters.IParameterMatch<T5>? _matcher5;
		private global::System.Action<TValue>? _onSet;
		private global::System.Func<global::System.Exception?>? _throwAction;
		private bool? _skipBaseClass;

		public RefStructIndexerSetterSetup(string name, global::Mockolate.Parameters.IParameterMatch<T1>? matcher1 = null, global::Mockolate.Parameters.IParameterMatch<T2>? matcher2 = null, global::Mockolate.Parameters.IParameterMatch<T3>? matcher3 = null, global::Mockolate.Parameters.IParameterMatch<T4>? matcher4 = null, global::Mockolate.Parameters.IParameterMatch<T5>? matcher5 = null) : base(name)
		{
			_matcher1 = matcher1;
			_matcher2 = matcher2;
			_matcher3 = matcher3;
			_matcher4 = matcher4;
			_matcher5 = matcher5;
		}

		internal global::Mockolate.Setup.RefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>? BoundGetter { get; set; }

		public bool Matches(T1 value1, T2 value2, T3 value3, T4 value4, T5 value5)
			=> (_matcher1 is null || _matcher1.Matches(value1))
			   && (_matcher2 is null || _matcher2.Matches(value2))
			   && (_matcher3 is null || _matcher3.Matches(value3))
			   && (_matcher4 is null || _matcher4.Matches(value4))
			   && (_matcher5 is null || _matcher5.Matches(value5));

		public void Invoke(T1 k1, T2 k2, T3 k3, T4 k4, T5 k5, TValue value, object? rawKey1 = null, object? rawKey2 = null, object? rawKey3 = null, object? rawKey4 = null, object? rawKey5 = null)
		{
			_matcher1?.InvokeCallbacks(k1);
			_matcher2?.InvokeCallbacks(k2);
			_matcher3?.InvokeCallbacks(k3);
			_matcher4?.InvokeCallbacks(k4);
			_matcher5?.InvokeCallbacks(k5);
			_onSet?.Invoke(value);

			if (_throwAction is not null)
			{
				global::System.Exception? exception = _throwAction();
				if (exception is not null)
				{
					throw exception;
				}
			}

			BoundGetter?.StoreValue(k1, k2, k3, k4, k5, value, rawKey1, rawKey2, rawKey3, rawKey4, rawKey5);
		}

		public bool SkipBaseClass(global::Mockolate.MockBehavior behavior)
			=> _skipBaseClass ?? behavior.SkipBaseClass;

		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>.SkippingBaseClass(bool skipBaseClass)
		{
			_skipBaseClass = skipBaseClass;
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>.OnSet(global::System.Action<TValue> callback)
		{
			_onSet = callback;
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>.Throws<TException>()
		{
			_throwAction = static () => new TException();
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>.Throws(global::System.Exception exception)
		{
			_throwAction = () => exception;
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>.Throws(global::System.Func<global::System.Exception> exceptionFactory)
		{
			_throwAction = exceptionFactory;
			return this;
		}

		protected override bool MatchesInteraction(global::Mockolate.Interactions.IMethodInteraction interaction)
			=> interaction is global::Mockolate.Interactions.RefStructMethodInvocation invocation && invocation.Name == Name;

		public override string ToString()
			=> $"{Name}({_matcher1?.ToString() ?? $"<{typeof(T1).Name} ref struct>"}, {_matcher2?.ToString() ?? $"<{typeof(T2).Name} ref struct>"}, {_matcher3?.ToString() ?? $"<{typeof(T3).Name} ref struct>"}, {_matcher4?.ToString() ?? $"<{typeof(T4).Name} ref struct>"}, {_matcher5?.ToString() ?? $"<{typeof(T5).Name} ref struct>"}) = {typeof(TValue).Name}";
	}

	/// <summary>
	///     Ref-struct-compatible combined indexer setup for arity 5. Mirrors the hand-written arity 1-4 surface.
	/// </summary>
	public interface IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> : IMethodSetup
		where T1 : allows ref struct
		where T2 : allows ref struct
		where T3 : allows ref struct
		where T4 : allows ref struct
		where T5 : allows ref struct
	{
		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> SkippingBaseClass(bool skipBaseClass = true);
		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> Returns(TValue returnValue);
		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> Returns(global::System.Func<TValue> returnFactory);
		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> OnSet(global::System.Action<TValue> callback);
		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> Throws<TException>() where TException : global::System.Exception, new();
		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> Throws(global::System.Exception exception);
		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> Throws(global::System.Func<global::System.Exception> exceptionFactory);
	}

	/// <summary>
	///     Concrete ref-struct-compatible combined indexer setup for arity 5. See <see cref="global::Mockolate.Setup.RefStructIndexerSetup{TValue, T}">RefStructIndexerSetup&lt;TValue, T&gt;</see>.
	/// </summary>
#if !DEBUG
#endif
	public sealed class RefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> : global::Mockolate.Setup.MethodSetup, global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5>
		where T1 : allows ref struct
		where T2 : allows ref struct
		where T3 : allows ref struct
		where T4 : allows ref struct
		where T5 : allows ref struct
	{
		public global::Mockolate.Setup.RefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5> Getter { get; }
		public global::Mockolate.Setup.RefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5> Setter { get; }

		public RefStructIndexerSetup(string getterName, string setterName, global::Mockolate.Parameters.IParameterMatch<T1>? matcher1 = null, global::Mockolate.Parameters.IParameterMatch<T2>? matcher2 = null, global::Mockolate.Parameters.IParameterMatch<T3>? matcher3 = null, global::Mockolate.Parameters.IParameterMatch<T4>? matcher4 = null, global::Mockolate.Parameters.IParameterMatch<T5>? matcher5 = null) : base(getterName)
		{
			Getter = new global::Mockolate.Setup.RefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>(getterName, matcher1, matcher2, matcher3, matcher4, matcher5);
			Setter = new global::Mockolate.Setup.RefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>(setterName, matcher1, matcher2, matcher3, matcher4, matcher5);
			Setter.BoundGetter = Getter;
		}

		protected override bool MatchesInteraction(global::Mockolate.Interactions.IMethodInteraction interaction) => false;

		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5>.SkippingBaseClass(bool skipBaseClass)
		{
			((global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>)Getter).SkippingBaseClass(skipBaseClass);
			((global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>)Setter).SkippingBaseClass(skipBaseClass);
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5>.Returns(TValue returnValue)
		{
			((global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>)Getter).Returns(returnValue);
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5>.Returns(global::System.Func<TValue> returnFactory)
		{
			((global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>)Getter).Returns(returnFactory);
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5>.OnSet(global::System.Action<TValue> callback)
		{
			((global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>)Setter).OnSet(callback);
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5>.Throws<TException>()
		{
			((global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>)Getter).Throws<TException>();
			((global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>)Setter).Throws<TException>();
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5>.Throws(global::System.Exception exception)
		{
			((global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>)Getter).Throws(exception);
			((global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>)Setter).Throws(exception);
			return this;
		}

		global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5> global::Mockolate.Setup.IRefStructIndexerSetup<TValue, T1, T2, T3, T4, T5>.Throws(global::System.Func<global::System.Exception> exceptionFactory)
		{
			((global::Mockolate.Setup.IRefStructIndexerGetterSetup<TValue, T1, T2, T3, T4, T5>)Getter).Throws(exceptionFactory);
			((global::Mockolate.Setup.IRefStructIndexerSetterSetup<TValue, T1, T2, T3, T4, T5>)Setter).Throws(exceptionFactory);
			return this;
		}
	}
}
#endif