//----------------------
// <auto-generated>
//     This code was generated by the Mockolate source generator.
//
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated!
// </auto-generated>
//----------------------

#nullable enable annotations
namespace Mockolate;

/// <summary>
///     Mock extensions for <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see>.
/// </summary>
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static partial class MockExtensionsForComprehensiveDelegate
{
	/// <inheritdoc cref="MockExtensionsForComprehensiveDelegate" />
	extension(global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate mock)
	{
		/// <summary>
		///     Get access to the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see>.
		/// </summary>
		public global::Mockolate.Mock.IMockForComprehensiveDelegate Mock
		{
			get
			{
				if (mock.Target is global::Mockolate.Mock.IMockForComprehensiveDelegate mockInterface)
				{
					return mockInterface;
				}
				throw new global::Mockolate.Exceptions.MockException("The subject is no mock.");
			}
		}

		/// <summary>
		///     Create a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the default <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.
		/// </summary>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate CreateMock()
			=> CreateMock(null, []);

		/// <summary>
		///     Create a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the default <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.
		/// </summary>
		/// <remarks>
		///     All provided <paramref name="setups" /> are immediately applied to the mock.
		/// </remarks>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate CreateMock(params global::System.Action<global::Mockolate.Mock.IMockSetupForComprehensiveDelegate>[] setups)
			=> CreateMock(null, setups);

		/// <summary>
		///     Create a new mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="mockBehavior" />.
		/// </summary>
		/// <remarks>
		///     All provided <paramref name="setups" /> are immediately applied to the mock.
		/// </remarks>
		public static global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate CreateMock(global::Mockolate.MockBehavior? mockBehavior = null, params global::System.Action<global::Mockolate.Mock.IMockSetupForComprehensiveDelegate>[] setups)
		{
			mockBehavior ??= global::Mockolate.MockBehavior.Default;
			var mockRegistry = new global::Mockolate.MockRegistry(mockBehavior, new global::Mockolate.Interactions.FastMockInteractions(0, mockBehavior.SkipInteractionRecording));
			global::Mockolate.Mock.ComprehensiveDelegate mockTarget = new global::Mockolate.Mock.ComprehensiveDelegate(mockRegistry);
			if (setups.Length > 0)
			{
				foreach (var setup in setups)
				{
					setup.Invoke(mockTarget);
				}
			}
			return mockTarget.Object;
		}
	}
}

internal static partial class Mock
{
	/// <summary>
	///     A mock implementation for <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see>.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal class ComprehensiveDelegate :
		IMockForComprehensiveDelegate,
		global::Mockolate.IMock
	{
		internal const int MemberId_Invoke = 0;
		internal const int MemberCount = 1;

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.MockRegistry global::Mockolate.IMock.MockRegistry => this.MockRegistry;
		private global::Mockolate.MockRegistry MockRegistry { get; }

		/// <inheritdoc cref="ComprehensiveDelegate" />
		public ComprehensiveDelegate(global::Mockolate.MockRegistry mockRegistry)
		{
			this.MockRegistry = mockRegistry;
		}

		/// <summary>
		///     Returns the actual delegate with the mock as target.
		/// </summary>
		public global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate Object => new(Invoke);
		private global::System.Span<char> Invoke(int x, ref int y, out string z, in long w)
		{
			var ref_y = y;
			global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long>? methodSetup = null;
			if (string.IsNullOrEmpty(this.MockRegistry.Scenario))
			{
				global::Mockolate.Setup.MethodSetup[]? snapshot_methodSetup = this.MockRegistry.GetMethodSetupSnapshot(global::Mockolate.Mock.ComprehensiveDelegate.MemberId_Invoke);
				if (snapshot_methodSetup is not null)
				{
					for (int i_methodSetup = snapshot_methodSetup.Length - 1; i_methodSetup >= 0; i_methodSetup--)
					{
						if (snapshot_methodSetup[i_methodSetup] is global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> s_methodSetup && s_methodSetup.Matches(x, ref_y, default, w))
						{
							methodSetup = s_methodSetup;
							break;
						}
					}
				}
			}
			if (methodSetup is null)
			{
				foreach (global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> s_methodSetup in this.MockRegistry.GetMethodSetups<global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long>>("global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke"))
				{
					if (s_methodSetup.Matches(x, ref_y, default, w))
					{
						methodSetup = s_methodSetup;
						break;
					}
				}
			}
			z = default!;
			if (methodSetup is global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long>.WithParameterCollection wpc)
			{
				if (wpc.Parameter2 is global::Mockolate.Parameters.IRefParameter<int> refParam2)
				{
					y = refParam2.GetValue(y);
				}
				if (wpc.Parameter3 is not global::Mockolate.Parameters.IOutParameter<string> outParam3 || !outParam3.TryGetValue(out z))
				{
					z = this.MockRegistry.Behavior.DefaultValue.Generate(default(string)!);
				}
			}
			if (MockRegistry.Behavior.SkipInteractionRecording == false)
			{
				MockRegistry.RegisterInteraction(new global::Mockolate.Interactions.MethodInvocation<int, int, string, long>("global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", x, y, z, w));
			}
			if (methodSetup is null && this.MockRegistry.Behavior.ThrowWhenNotSetup)
			{
				throw new global::Mockolate.Exceptions.MockNotSetupException("The method 'global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke(int, int, string, long)' was invoked without prior setup.");
			}
			methodSetup?.TriggerCallbacks(x, y, z, w);
			return methodSetup?.TryGetReturnValue(x, y, z, w, out var returnValue) == true ? returnValue : this.MockRegistry.Behavior.DefaultValue.Generate(default(global::Mockolate.Setup.SpanWrapper<char>)!);
		}

		/// <inheritdoc />
		string global::Mockolate.IMock.ToString()
			=> "Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate mock";

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> global::Mockolate.Mock.IMockSetupForComprehensiveDelegate.Setup(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IRefParameter<int> y, global::Mockolate.Parameters.IOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w)
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", CovariantParameterAdapter<int>.Wrap(x ?? global::Mockolate.It.IsNull<int>("null")), (global::Mockolate.Parameters.IParameterMatch<int>)(y), (global::Mockolate.Parameters.IParameterMatch<string>)(z), (global::Mockolate.Parameters.IParameterMatch<long>)(w ?? global::Mockolate.It.IsNull<long>("null")));
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveDelegate.MemberId_Invoke, methodSetup);
			return methodSetup;
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> global::Mockolate.Mock.IMockSetupForComprehensiveDelegate.Setup(global::Mockolate.Parameters.IParameters parameters)
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long>.WithParameters(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", parameters, "x", "y", "z", "w");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveDelegate.MemberId_Invoke, methodSetup);
			return methodSetup;
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> global::Mockolate.Mock.IMockSetupForComprehensiveDelegate.Setup(int x, global::Mockolate.Parameters.IRefParameter<int> y, global::Mockolate.Parameters.IOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w)
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", (global::Mockolate.Parameters.IParameterMatch<int>)global::Mockolate.It.Is<int>(x, ((global::System.IFormattable)x).ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)), (global::Mockolate.Parameters.IParameterMatch<int>)(y), (global::Mockolate.Parameters.IParameterMatch<string>)(z), (global::Mockolate.Parameters.IParameterMatch<long>)(w ?? global::Mockolate.It.IsNull<long>("null")));
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveDelegate.MemberId_Invoke, methodSetup);
			return methodSetup;
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> global::Mockolate.Mock.IMockSetupForComprehensiveDelegate.Setup(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IRefParameter<int> y, global::Mockolate.Parameters.IOutParameter<string> z, long w)
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", CovariantParameterAdapter<int>.Wrap(x ?? global::Mockolate.It.IsNull<int>("null")), (global::Mockolate.Parameters.IParameterMatch<int>)(y), (global::Mockolate.Parameters.IParameterMatch<string>)(z), (global::Mockolate.Parameters.IParameterMatch<long>)global::Mockolate.It.Is<long>(w, ((global::System.IFormattable)w).ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)));
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveDelegate.MemberId_Invoke, methodSetup);
			return methodSetup;
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> global::Mockolate.Mock.IMockSetupForComprehensiveDelegate.Setup(int x, global::Mockolate.Parameters.IRefParameter<int> y, global::Mockolate.Parameters.IOutParameter<string> z, long w)
		{
			var methodSetup = new global::Mockolate.Setup.ReturnMethodSetup<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long>.WithParameterCollection(MockRegistry, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", (global::Mockolate.Parameters.IParameterMatch<int>)global::Mockolate.It.Is<int>(x, ((global::System.IFormattable)x).ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)), (global::Mockolate.Parameters.IParameterMatch<int>)(y), (global::Mockolate.Parameters.IParameterMatch<string>)(z), (global::Mockolate.Parameters.IParameterMatch<long>)global::Mockolate.It.Is<long>(w, ((global::System.IFormattable)w).ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)));
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ComprehensiveDelegate.MemberId_Invoke, methodSetup);
			return methodSetup;
		}

		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => 
				(x is not null ? CovariantParameterAdapter<int>.Wrap(x).Matches(__i.Parameter1) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter1, default(int))) && 
				(y is global::Mockolate.Parameters.IParameterMatch<int> yMatch ? yMatch.Matches(__i.Parameter2) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter2, default(int))) && 
				(z is global::Mockolate.Parameters.IParameterMatch<string> zMatch ? zMatch.Matches(__i.Parameter3) : global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__i.Parameter3, default(string))) && 
				(w is not null ? CovariantParameterAdapter<long>.Wrap(w).Matches(__i.Parameter4) : global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(__i.Parameter4, default(long))), () => $"Invoke({x}, {y}, {z}, {w})");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(global::Mockolate.Parameters.IParameters parameters)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => parameters switch
				{
					global::Mockolate.Parameters.IParametersMatch m => m.Matches([__i.Parameter1, __i.Parameter2, __i.Parameter3, __i.Parameter4]),
					global::Mockolate.Parameters.INamedParametersMatch m => m.Matches([("x", __i.Parameter1), ("y", __i.Parameter2), ("z", __i.Parameter3), ("w", __i.Parameter4)]),
					_ => true
				}, () => $"Invoke({parameters})");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(int x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => 
				(global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(x, __i.Parameter1)) && 
				(y is global::Mockolate.Parameters.IParameterMatch<int> yMatch ? yMatch.Matches(__i.Parameter2) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter2, default(int))) && 
				(z is global::Mockolate.Parameters.IParameterMatch<string> zMatch ? zMatch.Matches(__i.Parameter3) : global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__i.Parameter3, default(string))) && 
				(w is not null ? CovariantParameterAdapter<long>.Wrap(w).Matches(__i.Parameter4) : global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(__i.Parameter4, default(long))), () => $"Invoke({x}, {y}, {z}, {w})");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, long w)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => 
				(x is not null ? CovariantParameterAdapter<int>.Wrap(x).Matches(__i.Parameter1) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter1, default(int))) && 
				(y is global::Mockolate.Parameters.IParameterMatch<int> yMatch ? yMatch.Matches(__i.Parameter2) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter2, default(int))) && 
				(z is global::Mockolate.Parameters.IParameterMatch<string> zMatch ? zMatch.Matches(__i.Parameter3) : global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__i.Parameter3, default(string))) && 
				(global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(w, __i.Parameter4)), () => $"Invoke({x}, {y}, {z}, {w})");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(int x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, long w)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => 
				(global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(x, __i.Parameter1)) && 
				(y is global::Mockolate.Parameters.IParameterMatch<int> yMatch ? yMatch.Matches(__i.Parameter2) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter2, default(int))) && 
				(z is global::Mockolate.Parameters.IParameterMatch<string> zMatch ? zMatch.Matches(__i.Parameter3) : global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__i.Parameter3, default(string))) && 
				(global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(w, __i.Parameter4)), () => $"Invoke({x}, {y}, {z}, {w})");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockForComprehensiveDelegate.VerifySetup(global::Mockolate.Setup.IMethodSetup setup)
			=> this.MockRegistry.Method<IMockVerifyForComprehensiveDelegate>(this, setup);

		/// <inheritdoc />
		bool IMockForComprehensiveDelegate.VerifyThatAllInteractionsAreVerified()
			=> this.MockRegistry.Interactions.GetUnverifiedInteractions().Count == 0;

		/// <inheritdoc />
		bool IMockForComprehensiveDelegate.VerifyThatAllSetupsAreUsed()
			=> this.MockRegistry.GetUnusedSetups(this.MockRegistry.Interactions).Count == 0;

		/// <inheritdoc />
		void IMockForComprehensiveDelegate.ClearAllInteractions()
			=> this.MockRegistry.ClearAllInteractions();

		/// <inheritdoc />
		global::Mockolate.Monitor.MockMonitor<IMockVerifyForComprehensiveDelegate> IMockForComprehensiveDelegate.Monitor()
			=> new global::Mockolate.Monitor.MockMonitor<IMockVerifyForComprehensiveDelegate>(this.MockRegistry.Interactions, interactions => new VerifyMonitorComprehensiveDelegate(new global::Mockolate.MockRegistry(this.MockRegistry, interactions)));
	}

	[global::System.Diagnostics.DebuggerNonUserCode]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class VerifyMonitorComprehensiveDelegate(global::Mockolate.MockRegistry mockRegistry) : global::Mockolate.Mock.IMockVerifyForComprehensiveDelegate
	{
		private global::Mockolate.MockRegistry MockRegistry { get; } = mockRegistry;

		#region IMockVerifyForComprehensiveDelegate

		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => 
				(x is not null ? CovariantParameterAdapter<int>.Wrap(x).Matches(__i.Parameter1) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter1, default(int))) && 
				(y is global::Mockolate.Parameters.IParameterMatch<int> yMatch ? yMatch.Matches(__i.Parameter2) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter2, default(int))) && 
				(z is global::Mockolate.Parameters.IParameterMatch<string> zMatch ? zMatch.Matches(__i.Parameter3) : global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__i.Parameter3, default(string))) && 
				(w is not null ? CovariantParameterAdapter<long>.Wrap(w).Matches(__i.Parameter4) : global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(__i.Parameter4, default(long))), () => $"Invoke({x}, {y}, {z}, {w})");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(global::Mockolate.Parameters.IParameters parameters)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => parameters switch
				{
					global::Mockolate.Parameters.IParametersMatch m => m.Matches([__i.Parameter1, __i.Parameter2, __i.Parameter3, __i.Parameter4]),
					global::Mockolate.Parameters.INamedParametersMatch m => m.Matches([("x", __i.Parameter1), ("y", __i.Parameter2), ("z", __i.Parameter3), ("w", __i.Parameter4)]),
					_ => true
				}, () => $"Invoke({parameters})");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(int x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => 
				(global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(x, __i.Parameter1)) && 
				(y is global::Mockolate.Parameters.IParameterMatch<int> yMatch ? yMatch.Matches(__i.Parameter2) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter2, default(int))) && 
				(z is global::Mockolate.Parameters.IParameterMatch<string> zMatch ? zMatch.Matches(__i.Parameter3) : global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__i.Parameter3, default(string))) && 
				(w is not null ? CovariantParameterAdapter<long>.Wrap(w).Matches(__i.Parameter4) : global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(__i.Parameter4, default(long))), () => $"Invoke({x}, {y}, {z}, {w})");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, long w)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => 
				(x is not null ? CovariantParameterAdapter<int>.Wrap(x).Matches(__i.Parameter1) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter1, default(int))) && 
				(y is global::Mockolate.Parameters.IParameterMatch<int> yMatch ? yMatch.Matches(__i.Parameter2) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter2, default(int))) && 
				(z is global::Mockolate.Parameters.IParameterMatch<string> zMatch ? zMatch.Matches(__i.Parameter3) : global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__i.Parameter3, default(string))) && 
				(global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(w, __i.Parameter4)), () => $"Invoke({x}, {y}, {z}, {w})");
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> IMockVerifyForComprehensiveDelegate.Verify(int x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, long w)
			=> this.MockRegistry.VerifyMethod<IMockVerifyForComprehensiveDelegate, global::Mockolate.Interactions.MethodInvocation<int, int, string, long>>(this, -1, "global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate.Invoke", __i => 
				(global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(x, __i.Parameter1)) && 
				(y is global::Mockolate.Parameters.IParameterMatch<int> yMatch ? yMatch.Matches(__i.Parameter2) : global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(__i.Parameter2, default(int))) && 
				(z is global::Mockolate.Parameters.IParameterMatch<string> zMatch ? zMatch.Matches(__i.Parameter3) : global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(__i.Parameter3, default(string))) && 
				(global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(w, __i.Parameter4)), () => $"Invoke({x}, {y}, {z}, {w})");
		#endregion IMockVerifyForComprehensiveDelegate
	}

	/// <summary>
	///     Accesses the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see>.
	/// </summary>
	internal interface IMockForComprehensiveDelegate :
		 IMockSetupForComprehensiveDelegate, IMockVerifyForComprehensiveDelegate
	{
		/// <summary>
		///     Verifies the method invocations for the <paramref name="setup" /> on the mock.
		/// </summary>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> VerifySetup(global::Mockolate.Setup.IMethodSetup setup);

		/// <summary>
		///     Gets a value indicating whether all expected interactions have been verified.
		/// </summary>
		bool VerifyThatAllInteractionsAreVerified();

		/// <summary>
		///     Gets a value indicating whether all registered setups were used.
		/// </summary>
		bool VerifyThatAllSetupsAreUsed();

		/// <summary>
		///     Clears all interactions recorded by the mock object.
		/// </summary>
		void ClearAllInteractions();

		/// <summary>
		///     Provides monitoring capabilities for a mocked instance of the specified type, allowing inspection of accessed properties, invoked methods, and event subscriptions.
		/// </summary>
		global::Mockolate.Monitor.MockMonitor<IMockVerifyForComprehensiveDelegate> Monitor();
	}

	/// <summary>
	///     Set up the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see>.
	/// </summary>
	internal interface IMockSetupForComprehensiveDelegate : global::Mockolate.Setup.IMockSetup<global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate>
	{
		/// <summary>
		///     Setup for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="x"/>, <paramref name="y"/>, <paramref name="z"/>, <paramref name="w"/>.
		/// </summary>
		/// <remarks>
		///     This overload takes <see cref="global::Mockolate.It">It</see> argument matchers (e.g. <c>It.IsAny&lt;T&gt;()</c>, <c>It.Is&lt;T&gt;(value)</c>) for every parameter.
		/// </remarks>
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> Setup(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IRefParameter<int> y, global::Mockolate.Parameters.IOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w);

		/// <summary>
		///     Setup for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="parameters" />.
		/// </summary>
		/// <remarks>
		///     This overload configures the setup via a custom <see cref="global::Mockolate.Match">Match</see> predicate (for example <see cref="global::Mockolate.Match.AnyParameters()">AnyParameters()</see> or <see cref="global::Mockolate.Match.Parameters(global::System.Func{object?[], bool}, string)">Parameters(Func&lt;object?[], bool&gt;, string)</see>) rather than per-parameter matchers.
		/// </remarks>
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> Setup(global::Mockolate.Parameters.IParameters parameters);

		/// <summary>
		///     Setup for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="x"/>, <paramref name="y"/>, <paramref name="z"/>, <paramref name="w"/>.
		/// </summary>
		/// <remarks>
		///     This overload accepts a direct value for <paramref name="x" /> (equivalent to <c>It.Is&lt;T&gt;(value)</c>) and an <see cref="global::Mockolate.It">It</see> matcher for <paramref name="y" />, <paramref name="z" />, <paramref name="w" />.
		/// </remarks>
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> Setup(int x, global::Mockolate.Parameters.IRefParameter<int> y, global::Mockolate.Parameters.IOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w);

		/// <summary>
		///     Setup for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="x"/>, <paramref name="y"/>, <paramref name="z"/>, <paramref name="w"/>.
		/// </summary>
		/// <remarks>
		///     This overload accepts a direct value for <paramref name="w" /> (equivalent to <c>It.Is&lt;T&gt;(value)</c>) and an <see cref="global::Mockolate.It">It</see> matcher for <paramref name="x" />, <paramref name="y" />, <paramref name="z" />.
		/// </remarks>
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> Setup(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IRefParameter<int> y, global::Mockolate.Parameters.IOutParameter<string> z, long w);

		/// <summary>
		///     Setup for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="x"/>, <paramref name="y"/>, <paramref name="z"/>, <paramref name="w"/>.
		/// </summary>
		/// <remarks>
		///     This overload accepts a direct value for <paramref name="x" />, <paramref name="w" /> (equivalent to <c>It.Is&lt;T&gt;(value)</c>) and an <see cref="global::Mockolate.It">It</see> matcher for <paramref name="y" />, <paramref name="z" />.
		/// </remarks>
		global::Mockolate.Setup.IReturnMethodSetupWithCallback<global::Mockolate.Setup.SpanWrapper<char>, int, int, string, long> Setup(int x, global::Mockolate.Parameters.IRefParameter<int> y, global::Mockolate.Parameters.IOutParameter<string> z, long w);

	}

	/// <summary>
	///     Verify interactions with the mock of <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see>.
	/// </summary>
	internal interface IMockVerifyForComprehensiveDelegate : global::Mockolate.Verify.IMockVerify<global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate>
	{
		/// <summary>
		///     Verify invocations for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="x"/>, <paramref name="y"/>, <paramref name="z"/>, <paramref name="w"/>.
		/// </summary>
		/// <remarks>
		///     This overload takes <see cref="global::Mockolate.It">It</see> argument matchers (e.g. <c>It.IsAny&lt;T&gt;()</c>, <c>It.Is&lt;T&gt;(value)</c>) for every parameter.
		/// </remarks>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> Verify(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w);

		/// <summary>
		///     Verify invocations for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="parameters"/>.
		/// </summary>
		/// <remarks>
		///     This overload matches invocations via a custom <see cref="global::Mockolate.Match">Match</see> predicate (for example <see cref="global::Mockolate.Match.AnyParameters()">AnyParameters()</see> or <see cref="global::Mockolate.Match.Parameters(global::System.Func{object?[], bool}, string)">Parameters(Func&lt;object?[], bool&gt;, string)</see>) rather than per-parameter matchers.
		/// </remarks>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> Verify(global::Mockolate.Parameters.IParameters parameters);

		/// <summary>
		///     Verify invocations for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="x"/>, <paramref name="y"/>, <paramref name="z"/>, <paramref name="w"/>.
		/// </summary>
		/// <remarks>
		///     This overload accepts a direct value for <paramref name="x" /> (equivalent to <c>It.Is&lt;T&gt;(value)</c>) and an <see cref="global::Mockolate.It">It</see> matcher for <paramref name="y" />, <paramref name="z" />, <paramref name="w" />.
		/// </remarks>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> Verify(int x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, global::Mockolate.Parameters.IParameter<long>? w);

		/// <summary>
		///     Verify invocations for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="x"/>, <paramref name="y"/>, <paramref name="z"/>, <paramref name="w"/>.
		/// </summary>
		/// <remarks>
		///     This overload accepts a direct value for <paramref name="w" /> (equivalent to <c>It.Is&lt;T&gt;(value)</c>) and an <see cref="global::Mockolate.It">It</see> matcher for <paramref name="x" />, <paramref name="y" />, <paramref name="z" />.
		/// </remarks>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> Verify(global::Mockolate.Parameters.IParameter<int>? x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, long w);

		/// <summary>
		///     Verify invocations for the delegate <see cref="global::Mockolate.ExampleTests.GeneratorCoverage.ComprehensiveDelegate">ComprehensiveDelegate</see> with the given <paramref name="x"/>, <paramref name="y"/>, <paramref name="z"/>, <paramref name="w"/>.
		/// </summary>
		/// <remarks>
		///     This overload accepts a direct value for <paramref name="x" />, <paramref name="w" /> (equivalent to <c>It.Is&lt;T&gt;(value)</c>) and an <see cref="global::Mockolate.It">It</see> matcher for <paramref name="y" />, <paramref name="z" />.
		/// </remarks>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForComprehensiveDelegate> Verify(int x, global::Mockolate.Parameters.IVerifyRefParameter<int> y, global::Mockolate.Parameters.IVerifyOutParameter<string> z, long w);

	}
}
#nullable disable annotations
