//----------------------
// <auto-generated>
//     This code was generated by the Mockolate source generator.
//
//     Changes to this file may cause incorrect behavior and
//     will be lost if the code is regenerated!
// </auto-generated>
//----------------------

#nullable enable annotations
namespace Mockolate;

internal static partial class Mock
{
	/// <summary>
	///     A mock implementation for <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.
	/// </summary>
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal class ICombinationMockA :
		global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA, IMockForICombinationMockA, IMockSetupForICombinationMockA, IMockVerifyForICombinationMockA,
		global::Mockolate.IMock
	{
		internal const int MemberId_Value_Get = 0;
		internal const int MemberId_Value_Set = 1;
		internal const int MemberId_Run = 2;
		internal const int MemberCount = 3;
		internal static readonly global::Mockolate.Interactions.PropertyGetterAccess PropertyAccess_Value_Get = new global::Mockolate.Interactions.PropertyGetterAccess("global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Value");

		/// <summary>
		///     Creates a <see cref="global::Mockolate.Interactions.FastMockInteractions">FastMockInteractions</see> sized to <see cref="MemberCount">MemberCount</see> for use as the mock's interaction store.
		///     Per-member buffers are not allocated up-front: the recording hot paths call <see cref="global::Mockolate.Interactions.FastMockInteractions.GetOrCreateBuffer{TBuffer}(int, global::System.Func{global::Mockolate.Interactions.FastMockInteractions, TBuffer})">GetOrCreateBuffer&lt;TBuffer&gt;(int, Func&lt;FastMockInteractions, TBuffer&gt;)</see> so a slot is materialized only when its member is first invoked.
		/// </summary>
		internal static global::Mockolate.Interactions.FastMockInteractions CreateFastInteractions(global::Mockolate.MockBehavior behavior)
			=> new global::Mockolate.Interactions.FastMockInteractions(MemberCount, behavior.SkipInteractionRecording);

		/// <summary>
		///     Builds a <see cref="global::Mockolate.MockRegistry">MockRegistry</see> backed by a typed-buffer-sized <see cref="global::Mockolate.Interactions.FastMockInteractions">FastMockInteractions</see> from <paramref name="behavior" />.
		/// </summary>
		private static global::Mockolate.MockRegistry MockolateCreateRegistryFromBehavior(global::Mockolate.MockBehavior behavior)
		{
			global::Mockolate.MockRegistry registry = new global::Mockolate.MockRegistry(behavior, CreateFastInteractions(behavior));
			return registry;
		}

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.MockRegistry global::Mockolate.IMock.MockRegistry => this.MockRegistry;
		private global::Mockolate.MockRegistry MockRegistry { get; }

		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		private global::Mockolate.Interactions.FastMethod0Buffer MockolateBuffer_Run
			=> field ?? (field = ((global::Mockolate.Interactions.FastMockInteractions)this.MockRegistry.Interactions).GetOrCreateBuffer<global::Mockolate.Interactions.FastMethod0Buffer>(global::Mockolate.Mock.ICombinationMockA.MemberId_Run, static fast => new global::Mockolate.Interactions.FastMethod0Buffer(fast)));

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockSetupForICombinationMockA IMockForICombinationMockA.Setup
			=> this;
		/// <inheritdoc />
		IMockInScenarioForICombinationMockA IMockForICombinationMockA.InScenario(string scenario)
			=> new MockInScenarioForICombinationMockA(this.MockRegistry, scenario);

		/// <inheritdoc />
		IMockForICombinationMockA IMockForICombinationMockA.InScenario(string scenario, global::System.Action<IMockInScenarioForICombinationMockA> setup)
		{
			setup.Invoke(new MockInScenarioForICombinationMockA(this.MockRegistry, scenario));
			return this;
		}

		/// <inheritdoc />
		IMockForICombinationMockA IMockForICombinationMockA.TransitionTo(string scenario)
		{
			this.MockRegistry.TransitionTo(scenario);
			return this;
		}
		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		IMockVerifyForICombinationMockA IMockForICombinationMockA.Verify
			=> this;
		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForICombinationMockA> IMockForICombinationMockA.VerifySetup(global::Mockolate.Setup.IMethodSetup setup)
			=> this.MockRegistry.Method<IMockVerifyForICombinationMockA>(this, setup);
		/// <inheritdoc />
		bool IMockForICombinationMockA.VerifyThatAllInteractionsAreVerified()
			=> this.MockRegistry.Interactions.GetUnverifiedInteractions().Count == 0;
		/// <inheritdoc />
		bool IMockForICombinationMockA.VerifyThatAllSetupsAreUsed()
			=> this.MockRegistry.GetUnusedSetups(this.MockRegistry.Interactions).Count == 0;
		/// <inheritdoc />
		void IMockForICombinationMockA.ClearAllInteractions()
			=> this.MockRegistry.ClearAllInteractions();
		/// <inheritdoc />
		global::Mockolate.Monitor.MockMonitor<IMockVerifyForICombinationMockA> IMockForICombinationMockA.Monitor()
			=> new global::Mockolate.Monitor.MockMonitor<IMockVerifyForICombinationMockA>(this.MockRegistry.Interactions, interactions => new VerifyMonitorICombinationMockA(new global::Mockolate.MockRegistry(this.MockRegistry, interactions)));

		/// <inheritdoc />
		string global::Mockolate.IMock.ToString()
			=> "Mockolate.Tests.GeneratorCoverage.ICombinationMockA mock";

		/// <inheritdoc cref="ICombinationMockA" />
		public ICombinationMockA(global::Mockolate.MockRegistry mockRegistry)
		{
			this.MockRegistry = mockRegistry;
		}

		/// <inheritdoc cref="ICombinationMockA" />
		public ICombinationMockA(global::Mockolate.MockBehavior behavior)
			: this(MockolateCreateRegistryFromBehavior(behavior))
		{
		}

		#region Mockolate.Tests.GeneratorCoverage.ICombinationMockA

		/// <inheritdoc cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Value" />
		public int Value
		{
			get
			{
				return this.MockRegistry.GetPropertyFast<int>(global::Mockolate.Mock.ICombinationMockA.MemberId_Value_Get, global::Mockolate.Mock.ICombinationMockA.PropertyAccess_Value_Get, static b => b.DefaultValue.Generate(default(int)!), this.MockRegistry.Wraps is not global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA wraps ? null : () => wraps.Value);
			}
		}

		/// <inheritdoc cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run()" />
		public void Run()
		{
			global::Mockolate.Setup.VoidMethodSetup? methodSetup = null;
			if (string.IsNullOrEmpty(this.MockRegistry.Scenario))
			{
				global::Mockolate.Setup.MethodSetup[]? snapshot_methodSetup = this.MockRegistry.GetMethodSetupSnapshot(global::Mockolate.Mock.ICombinationMockA.MemberId_Run);
				if (snapshot_methodSetup is not null)
				{
					for (int i_methodSetup = snapshot_methodSetup.Length - 1; i_methodSetup >= 0; i_methodSetup--)
					{
						if (snapshot_methodSetup[i_methodSetup] is global::Mockolate.Setup.VoidMethodSetup s_methodSetup && s_methodSetup.Matches())
						{
							methodSetup = s_methodSetup;
							break;
						}
					}
				}
			}
			if (methodSetup is null)
			{
				foreach (global::Mockolate.Setup.VoidMethodSetup s_methodSetup in this.MockRegistry.GetMethodSetups<global::Mockolate.Setup.VoidMethodSetup>("global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run"))
				{
					if (s_methodSetup.Matches())
					{
						methodSetup = s_methodSetup;
						break;
					}
				}
			}
			bool hasWrappedResult = false;
			if (this.MockRegistry.Behavior.SkipInteractionRecording == false)
			{
				this.MockolateBuffer_Run.Append("global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run");
			}
			try
			{
				if (this.MockRegistry.Wraps is global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA wraps)
				{
					wraps.Run();
					hasWrappedResult = true;
				}
			}
			finally
			{
				methodSetup?.TriggerCallbacks();
			}
			if (methodSetup is null && !hasWrappedResult && this.MockRegistry.Behavior.ThrowWhenNotSetup)
			{
				throw new global::Mockolate.Exceptions.MockNotSetupException("The method 'global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run()' was invoked without prior setup.");
			}
		}

		#endregion Mockolate.Tests.GeneratorCoverage.ICombinationMockA

		#region IMockSetupForICombinationMockA

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Setup.PropertySetup<int> global::Mockolate.Mock.IMockSetupForICombinationMockA.Value
		{
			get
			{
				var propertySetup = new global::Mockolate.Setup.PropertySetup<int>(MockRegistry, "global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Value");
				this.MockRegistry.SetupProperty(global::Mockolate.Mock.ICombinationMockA.MemberId_Value_Get, propertySetup);
				return propertySetup;
			}
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IVoidMethodSetup global::Mockolate.Mock.IMockSetupForICombinationMockA.Run()
		{
			var methodSetup = new global::Mockolate.Setup.VoidMethodSetup.WithParameterCollection(MockRegistry, "global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ICombinationMockA.MemberId_Run, methodSetup);
			return methodSetup;
		}

		#endregion IMockSetupForICombinationMockA

		#region IMockVerifyForICombinationMockA

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForICombinationMockA, int> IMockVerifyForICombinationMockA.Value
		{
			get
			{
				return new global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForICombinationMockA, int>(this, this.MockRegistry, global::Mockolate.Mock.ICombinationMockA.MemberId_Value_Get, global::Mockolate.Mock.ICombinationMockA.MemberId_Value_Set, "global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Value");
			}
		}

		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForICombinationMockA>.IgnoreParameters IMockVerifyForICombinationMockA.Run()
			=> this.MockRegistry.VerifyMethod<IMockVerifyForICombinationMockA>(this, global::Mockolate.Mock.ICombinationMockA.MemberId_Run, "global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run", () => $"Run()");
		#endregion IMockVerifyForICombinationMockA
	}

	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class VerifyMonitorICombinationMockA(global::Mockolate.MockRegistry mockRegistry) : global::Mockolate.Mock.IMockVerifyForICombinationMockA
	{
		private global::Mockolate.MockRegistry MockRegistry { get; } = mockRegistry;

		#region IMockVerifyForICombinationMockA

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForICombinationMockA, int> IMockVerifyForICombinationMockA.Value
		{
			get
			{
				return new global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForICombinationMockA, int>(this, this.MockRegistry, global::Mockolate.Mock.ICombinationMockA.MemberId_Value_Get, global::Mockolate.Mock.ICombinationMockA.MemberId_Value_Set, "global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Value");
			}
		}

		/// <inheritdoc />
		global::Mockolate.Verify.VerificationResult<IMockVerifyForICombinationMockA>.IgnoreParameters IMockVerifyForICombinationMockA.Run()
			=> this.MockRegistry.VerifyMethod<IMockVerifyForICombinationMockA>(this, global::Mockolate.Mock.ICombinationMockA.MemberId_Run, "global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run", () => $"Run()");
		#endregion IMockVerifyForICombinationMockA
	}

	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class MockInScenarioForICombinationMockA : global::Mockolate.Mock.IMockInScenarioForICombinationMockA, global::Mockolate.Mock.IMockSetupForICombinationMockA
	{
		private global::Mockolate.MockRegistry MockRegistry { get; }
		private string _scenarioName;

		public MockInScenarioForICombinationMockA(global::Mockolate.MockRegistry mockRegistry, string scenario)
		{
			this.MockRegistry = mockRegistry;
			_scenarioName = scenario;
		}

		/// <inheritdoc />
		global::Mockolate.Mock.IMockSetupForICombinationMockA global::Mockolate.Mock.IMockInScenarioForICombinationMockA.Setup
			=> this;

		#region IMockSetupForICombinationMockA

		/// <inheritdoc />
		[global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
		global::Mockolate.Setup.PropertySetup<int> global::Mockolate.Mock.IMockSetupForICombinationMockA.Value
		{
			get
			{
				var propertySetup = new global::Mockolate.Setup.PropertySetup<int>(MockRegistry, "global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Value");
				this.MockRegistry.SetupProperty(global::Mockolate.Mock.ICombinationMockA.MemberId_Value_Get, _scenarioName, propertySetup);
				return propertySetup;
			}
		}

		/// <inheritdoc />
		global::Mockolate.Setup.IVoidMethodSetup global::Mockolate.Mock.IMockSetupForICombinationMockA.Run()
		{
			var methodSetup = new global::Mockolate.Setup.VoidMethodSetup.WithParameterCollection(MockRegistry, "global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run");
			this.MockRegistry.SetupMethod(global::Mockolate.Mock.ICombinationMockA.MemberId_Run, _scenarioName, methodSetup);
			return methodSetup;
		}

		#endregion IMockSetupForICombinationMockA
	}

	/// <summary>
	///     The Mockolate accessor for a mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>, reached through <c>.Mock</c> on the mocked instance.
	/// </summary>
	/// <remarks>
	///     Groups every operation that acts on the mock rather than on the mocked subject: setups, verifications, event raising, scenarios and monitoring.
	/// </remarks>
	internal interface IMockForICombinationMockA
	{
		/// <summary>
		///     Configures how members of the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> respond when invoked.
		/// </summary>
		/// <remarks>
		///     Each mocked member is available as a strongly-typed entry on this surface. Chain <c>Returns</c>, <c>ReturnsAsync</c>, <c>Throws</c>, <c>ThrowsAsync</c> or <c>Do</c> to control the response; chain <c>InitializeWith</c>/<c>Register</c> to initialize properties and indexers; chain multiple returns/throws to define a sequence; use <c>.For(n)</c>, <c>.Only(n)</c>, <c>.Forever()</c>, <c>.When(predicate)</c> to control when a callback runs.<br />
		///     When two setups overlap, the most recently defined one wins.
		/// </remarks>
		IMockSetupForICombinationMockA Setup { get; }

		/// <summary>
		///     Opens a named scenario scope on the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> so that additional setups can be registered for that scenario.
		/// </summary>
		/// <remarks>
		///     Scenarios let you define per-state behavior. Setups registered inside the returned <c>IMockInScenarioFor...</c> scope only apply while the mock's current scenario matches <paramref name="scenario" />; switch scenarios with <see cref="TransitionTo">TransitionTo</see>.
		/// </remarks>
		/// <param name="scenario">Name of the scenario to enter. Any non-null string acts as a key; the mock starts in an unnamed default scenario.</param>
		/// <returns>A scoped accessor whose <c>Setup</c> (and <c>SetupProtected</c>, where applicable) register scenario-specific setups.</returns>
		IMockInScenarioForICombinationMockA InScenario(string scenario);

		/// <summary>
		///     Opens a named scenario scope on the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> and immediately invokes <paramref name="setup" /> to register scenario-specific setups.
		/// </summary>
		/// <remarks>
		///     Equivalent to <c>InScenario(scenario)</c> followed by the setup callback, but returns the original <c>IMockFor...</c> accessor so it chains nicely at mock-creation time.
		/// </remarks>
		/// <param name="scenario">Name of the scenario to enter.</param>
		/// <param name="setup">Callback that receives the scenario-scoped setup surface and registers scenario-specific setups.</param>
		/// <returns>This accessor, to allow chaining.</returns>
		IMockForICombinationMockA InScenario(string scenario, global::System.Action<IMockInScenarioForICombinationMockA> setup);

		/// <summary>
		///     Switches the active scenario of the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> to <paramref name="scenario" />.
		/// </summary>
		/// <remarks>
		///     After the transition, setups registered via <see cref="InScenario(string)">InScenario(string)</see> under that scenario take effect. Scenarios that have no matching setup for a given member fall back to the default (un-scoped) setups.
		/// </remarks>
		/// <param name="scenario">Name of the scenario to transition to.</param>
		/// <returns>This accessor, to allow chaining.</returns>
		IMockForICombinationMockA TransitionTo(string scenario);

		/// <summary>
		///     Asserts how often, and in which order, members of the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> were invoked.
		/// </summary>
		/// <remarks>
		///     Each call to a member here returns a <c>VerificationResult</c> that you terminate with a count assertion: <c>Never()</c>, <c>Once()</c>, <c>Twice()</c>, <c>Exactly(n)</c>, <c>AtLeast(n)</c>/<c>AtLeastOnce()</c>/<c>AtLeastTwice()</c>, <c>AtMost(n)</c>/<c>AtMostOnce()</c>/<c>AtMostTwice()</c>, <c>Between(min, max)</c> or <c>Times(predicate)</c>.<br />
		///     Use <c>Within(TimeSpan)</c> / <c>WithCancellation(CancellationToken)</c> before the terminator to wait for expected interactions that happen on background threads.<br />
		///     Chain <c>Then(...)</c> to assert an ordered sequence of calls. A failing assertion throws a <see cref="global::Mockolate.Exceptions.MockVerificationException">MockVerificationException</see>.
		/// </remarks>
		IMockVerifyForICombinationMockA Verify { get; }

		/// <summary>
		///     Verifies how often a specific method setup was matched by actual invocations.
		/// </summary>
		/// <remarks>
		///     Useful when you want to verify &quot;this <em>particular</em> setup was hit N times&quot; without re-stating the matchers. Chain the usual count terminators (<c>Once()</c>, <c>AtLeastOnce()</c>, <c>Exactly(n)</c>, ...) on the returned result.
		/// </remarks>
		/// <param name="setup">The setup previously registered through <see cref="Setup">Setup</see> (typically returned from a <c>Returns(...)</c>/<c>Throws(...)</c> call).</param>
		/// <returns>A <c>VerificationResult</c> that counts invocations matching the given setup.</returns>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForICombinationMockA> VerifySetup(global::Mockolate.Setup.IMethodSetup setup);

		/// <summary>
		///     Checks whether every recorded interaction on this mock has been observed by at least one <c>Verify</c> call.
		/// </summary>
		/// <remarks>
		///     Useful in test teardown to catch unexpected interactions (&quot;strict verification&quot;): if any recorded call has never been matched by a verification, the method returns <see langword="false" />.
		/// </remarks>
		/// <returns><see langword="true" /> if every recorded interaction was verified at least once; otherwise <see langword="false" />.</returns>
		bool VerifyThatAllInteractionsAreVerified();

		/// <summary>
		///     Checks whether every registered setup on this mock was matched by at least one actual invocation.
		/// </summary>
		/// <remarks>
		///     Useful to catch unused setups that silently rot as the test subject evolves.
		/// </remarks>
		/// <returns><see langword="true" /> if every registered setup was used at least once; otherwise <see langword="false" />.</returns>
		bool VerifyThatAllSetupsAreUsed();

		/// <summary>
		///     Removes every recorded interaction from this mock while keeping all registered setups intact.
		/// </summary>
		/// <remarks>
		///     Handy when a single test exercises multiple logical phases and you only want to verify the interactions of the latest phase.
		/// </remarks>
		void ClearAllInteractions();

		/// <summary>
		///     Creates a monitor whose <c>Verify</c> surface is scoped to interactions produced between <c>monitor.Run()</c> and the disposal of its <see cref="global::System.IDisposable">IDisposable</see> scope.
		/// </summary>
		/// <remarks>
		///     The underlying mock keeps recording all interactions as usual - only the monitor's <c>Verify</c> view is scoped. Useful to verify only the interactions produced by a specific block of test code without resetting the mock.
		/// </remarks>
		/// <returns>A <see cref="global::Mockolate.Monitor.MockMonitor{T}">MockMonitor&lt;T&gt;</see> that exposes <c>Verify</c> over the monitored interactions and a <c>Run()</c> method that opens the recording scope.</returns>
		global::Mockolate.Monitor.MockMonitor<IMockVerifyForICombinationMockA> Monitor();
	}

	/// <summary>
	///     Scoped access to setups for a scenario on the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.
	/// </summary>
	internal interface IMockInScenarioForICombinationMockA
	{
		/// <summary>
		///     Set up the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> within the scenario scope.
		/// </summary>
		IMockSetupForICombinationMockA Setup { get; }
	}

	/// <summary>
	///     Set up the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.
	/// </summary>
	internal interface IMockSetupForICombinationMockA : global::Mockolate.Setup.IMockSetup<global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA>
	{
		/// <summary>
		///     Setup for the int property <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Value">Value</see>.
		/// </summary>
		global::Mockolate.Setup.PropertySetup<int> Value { get; }

		/// <summary>
		///     Setup for the method <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run()">Run()</see>.
		/// </summary>
		[global::System.Runtime.CompilerServices.OverloadResolutionPriority(int.MaxValue)]
		global::Mockolate.Setup.IVoidMethodSetup Run();

	}

	/// <summary>
	///     Verify interactions with the mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.
	/// </summary>
	internal interface IMockVerifyForICombinationMockA : global::Mockolate.Verify.IMockVerify<global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA>
	{
		/// <summary>
		///     Verify interactions with the int property <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Value">Value</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationPropertyResult<IMockVerifyForICombinationMockA, int> Value { get; }

		/// <summary>
		///     Verify invocations for the method <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA.Run()">Run()</see>.
		/// </summary>
		global::Mockolate.Verify.VerificationResult<IMockVerifyForICombinationMockA>.IgnoreParameters Run();

	}
}
/// <summary>
///     Mock extensions for <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.
/// </summary>
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static partial class MockExtensionsForICombinationMockA
{
	/// <inheritdoc cref="MockExtensionsForICombinationMockA" />
	extension(global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA mock)
	{
		/// <summary>
		///     Gets the mock accessor for <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> - the entry point for configuring setups, verifying interactions and raising events.
		/// </summary>
		/// <remarks>
		///     The accessor is the bridge between the strongly-typed instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> returned by <c>CreateMock(...)</c> and the underlying mock registry where setups and recorded interactions live.<br />
		///     Through it you can:<br />
		///     <list type="bullet"><br />
		///       <item><description><c>Setup</c> - configure how members respond when invoked (<c>Returns</c>, <c>Throws</c>, <c>Do</c>, <c>InitializeWith</c>, ...).</description></item><br />
		///       <item><description><c>Verify</c> - assert how often (and in which order) members were invoked.</description></item><br />
		///       <item><description><c>InScenario</c> / <c>TransitionTo</c> - scope setups and behavior to a named scenario and switch between scenarios.</description></item><br />
		///       <item><description><c>Monitor</c>, <c>ClearAllInteractions</c>, <c>VerifyThatAllInteractionsAreVerified</c>, <c>VerifyThatAllSetupsAreUsed</c> - manage recorded interactions.</description></item><br />
		///       <item><description><c>VerifySetup</c> - verify how often a specific setup matched.</description></item><br />
		///     </list>
		/// </remarks>
		/// <exception cref="global::Mockolate.Exceptions.MockException">The instance is not a Mockolate-generated mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.</exception>
		public global::Mockolate.Mock.IMockForICombinationMockA Mock
		{
			get
			{
				if (mock is global::Mockolate.Mock.IMockForICombinationMockA mockInterface)
				{
					return mockInterface;
				}
				throw new global::Mockolate.Exceptions.MockException("The subject is no mock.");
			}
		}

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> with the default <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.
		/// </summary>
		/// <remarks>
		///     The returned instance is a strongly-typed mock generated at compile time - it implements <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> and exposes the Mockolate surface through <c>.Mock</c>:<br />
		///     <list type="bullet"><br />
		///       <item><description><c>.Mock.Setup</c> configures how members respond (<c>Returns</c>, <c>Throws</c>, <c>Do</c>, <c>InitializeWith</c>, sequences, callbacks).</description></item><br />
		///       <item><description><c>.Mock.Verify</c> asserts how often and in which order members were invoked.</description></item><br />
		///     </list><br />
		///     With the default behavior, un-configured members return <c>default</c> values (empty collections / strings, completed tasks, <see langword="null" /> otherwise) and base-class implementations are invoked for class mocks. Use one of the overloads that accepts a <see cref="global::Mockolate.MockBehavior">MockBehavior</see> to customize this (for example to make un-configured calls throw or to skip the base class).<br />
		///     Overloads allow you to additionally pass constructor parameters (for class mocks), apply an initial <c>setup</c> callback before the instance is returned, or combine both.
		/// </remarks>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.</returns>
		public static global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA CreateMock()
			=> CreateMock(null, null, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> with the default <see cref="global::Mockolate.MockBehavior">MockBehavior</see>, applying the given <paramref name="setup" /> immediately.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.</returns>
		public static global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA CreateMock(global::System.Action<global::Mockolate.Mock.IMockSetupForICombinationMockA> setup)
			=> CreateMock(null, setup, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> with the given <paramref name="mockBehavior" />.
		/// </summary>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.</returns>
		public static global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA CreateMock(global::Mockolate.MockBehavior mockBehavior)
			=> CreateMock(mockBehavior, null, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> with the given <paramref name="mockBehavior" />, applying the given <paramref name="setup" /> immediately.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup; see <see cref="global::Mockolate.MockBehavior">MockBehavior</see>.</param>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.</returns>
		public static global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA CreateMock(global::Mockolate.MockBehavior mockBehavior, global::System.Action<global::Mockolate.Mock.IMockSetupForICombinationMockA> setup)
			=> CreateMock(mockBehavior, setup, (object?[]?)null);

		/// <summary>
		///     Creates a new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> using the given <paramref name="mockBehavior" />, applying the given <paramref name="setup" /> immediately, using the given <paramref name="constructorParameters" />.
		/// </summary>
		/// <remarks>
		///     The provided <paramref name="setup" /> is immediately applied to the mock. Use this overload when you want setups to cover virtual interactions triggered inside the constructor.
		/// </remarks>
		/// <param name="mockBehavior">Controls how the mock responds when members are invoked without a matching setup, or <see langword="null" /> for <c>MockBehavior.Default</c>.</param>
		/// <param name="setup">Callback that receives the mock's setup surface and registers initial setups before the mock is returned, or <see langword="null" /> to skip.</param>
		/// <param name="constructorParameters">Values forwarded to a matching base-class constructor, or <see langword="null" /> to use the parameterless constructor.</param>
		/// <returns>A new mock instance of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see>.</returns>
		private static global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA CreateMock(global::Mockolate.MockBehavior? mockBehavior, global::System.Action<global::Mockolate.Mock.IMockSetupForICombinationMockA>? setup, object?[]? constructorParameters)
		{
			if (mockBehavior is not null)
			{
				IMockBehaviorAccess mockBehaviorAccess = (global::Mockolate.IMockBehaviorAccess)mockBehavior;
				if (mockBehaviorAccess.TryGet<global::System.Action<global::Mockolate.Mock.IMockSetupForICombinationMockA>?>(out var additionalSetup))
				{
					if (setup is null)
					{
						setup = additionalSetup;
					}
					else
					{
						var originalSetup = setup;
						setup = s => { additionalSetup.Invoke(s); originalSetup.Invoke(s); };
					}
				}
			}

			mockBehavior ??= global::Mockolate.MockBehavior.Default;
			global::Mockolate.MockRegistry mockRegistry = new global::Mockolate.MockRegistry(mockBehavior, global::Mockolate.Mock.ICombinationMockA.CreateFastInteractions(mockBehavior), constructorParameters);
			return CreateMockInstance(mockRegistry, constructorParameters, setup);
		}

		private static global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA CreateMockInstance(global::Mockolate.MockRegistry mockRegistry, object?[]? constructorParameters, global::System.Action<global::Mockolate.Mock.IMockSetupForICombinationMockA>? setup)
		{
			var value = new global::Mockolate.Mock.ICombinationMockA(mockRegistry);
			if (setup is not null)
			{
				setup.Invoke(value);
			}
			return value;
		}
		/// <summary>
		///     Creates a mock that wraps the given <paramref name="instance" />.
		/// </summary>
		/// <remarks>
		///     Public members on the mock forward to <paramref name="instance" /> unless overridden by a setup; protected members still go through the base-class implementation. All forwarded interactions are recorded and can be verified the same as on a plain mock.
		/// </remarks>
		/// <param name="instance">The real object whose calls should be forwarded. Must not be <see langword="null" />.</param>
		/// <returns>A new mock of <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> that delegates to <paramref name="instance" />.</returns>
		public global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA Wrapping(global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA instance)
		{
			if (mock is global::Mockolate.IMock mockInterface)
			{
				global::Mockolate.MockRegistry wrappingRegistry = new global::Mockolate.MockRegistry(mockInterface.MockRegistry, instance);
				wrappingRegistry = new global::Mockolate.MockRegistry(wrappingRegistry, global::Mockolate.Mock.ICombinationMockA.CreateFastInteractions(wrappingRegistry.Behavior));
				return CreateMockInstance(wrappingRegistry, mockInterface.MockRegistry.ConstructorParameters, null);
			}
			throw new global::Mockolate.Exceptions.MockException("The subject is no mock.");
		}

	}

	/// <inheritdoc cref="MockExtensionsForICombinationMockA" />
	extension(global::Mockolate.MockBehavior behavior)
	{
		/// <summary>
		///     Initializes mocks of type <typeparamref name="T" /> with the given <paramref name="setup" />.
		/// </summary>
		/// <remarks>
		///     The <paramref name="setup" /> is applied to the mock before the constructor is executed. Calling <c>Initialize</c> again overlays additional setups on top of any previously registered ones.
		/// </remarks>
		/// <typeparam name="T">The mockable type derived from <see cref="global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA">ICombinationMockA</see> that this setup should apply to.</typeparam>
		/// <param name="setup">Callback invoked when a new mock of <typeparamref name="T" /> is created.</param>
		/// <returns>A new <see cref="global::Mockolate.MockBehavior">MockBehavior</see> with the registered initializer. The original instance is unchanged.</returns>
		public global::Mockolate.MockBehavior Initialize<T>(global::System.Action<global::Mockolate.Mock.IMockSetupForICombinationMockA> setup)
			where T : global::Mockolate.Tests.GeneratorCoverage.ICombinationMockA
		{
			var behaviorAccess = (global::Mockolate.IMockBehaviorAccess)behavior;
			return behaviorAccess.Set(setup);
		}
	}

	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	private sealed class CovariantParameterAdapter<T>(global::Mockolate.Parameters.IParameter inner) : global::Mockolate.Parameters.IParameterMatch<T>
	{
		public bool Matches(T value) => inner.Matches(value);
		public void InvokeCallbacks(T value) => inner.InvokeCallbacks(value);
		public override string? ToString() => inner.ToString();

		public static global::Mockolate.Parameters.IParameterMatch<T> Wrap(global::Mockolate.Parameters.IParameter<T> parameter)
			=> parameter is global::Mockolate.Parameters.IParameterMatch<T> direct
				? direct
				: new CovariantParameterAdapter<T>(parameter);
	}
}

#nullable disable annotations
