using System.Text;
using Microsoft.CodeAnalysis;
using Mockolate.SourceGenerators.Entities;
using Mockolate.SourceGenerators.Internals;
using Type = Mockolate.SourceGenerators.Entities.Type;

namespace Mockolate.SourceGenerators.Sources;

#pragma warning disable S3776 // Cognitive Complexity of methods should not be too high
internal static partial class Sources
{
	private static StringBuilder InitializeBuilder()
	{
		StringBuilder sb = new();
		sb.AppendLine("""
		              //----------------------
		              // <auto-generated>
		              //     This code was generated by the Mockolate source generator.
		              //
		              //     Changes to this file may cause incorrect behavior and
		              //     will be lost if the code is regenerated!
		              // </auto-generated>
		              //----------------------
		              """);

		sb.AppendLine();
		return sb;
	}

	/// <summary>
	///     Generates a comma-separated list of generic type parameters (e.g., "T1, T2, T3").
	/// </summary>
	private static string GetGenericTypeParameters(int count, int startIndex = 1)
		=> string.Join(", ", Enumerable.Range(startIndex, count).Select(i => $"T{i}"));

	/// <summary>
	///     Generates a comma-separated list of generic type parameters with 'out' variance (e.g., "out T1, out T2").
	/// </summary>
	private static string GetOutGenericTypeParameters(int count, int startIndex = 1)
		=> string.Join(", ", Enumerable.Range(startIndex, count).Select(i => $"out T{i}"));

	/// <summary>
	///     Generates a descriptive text listing type parameters (e.g., "T1, T2 and T3" or just "T1").
	/// </summary>
	private static string GetTypeParametersDescription(int numberOfParameters, int startIndex = 1)
	{
		StringBuilder sb = new();
		for (int i = startIndex; i < startIndex + numberOfParameters - 1; i++)
		{
			if (i > startIndex)
			{
				sb.Append(", ");
			}

			sb.Append("<typeparamref name=\"T").Append(i).Append("\" />");
		}

		sb.Append(" and <typeparamref name=\"T").Append(startIndex + numberOfParameters - 1).Append("\" />");
		return sb.ToString();
	}

	/// <summary>
	///     Appends a TriggerCallbacks invocation.
	/// </summary>
	private static void AppendTriggerCallbacks(StringBuilder sb, string indent, string varName,
		IEnumerable<MethodParameter> parameters)
		=> sb.Append(indent).Append(varName).Append("?.TriggerCallbacks(")
			.Append(string.Join(", ", parameters.Select(p => p.ToNameOrWrapper())))
			.Append(");").AppendLine();

	/// <summary>
	///     Formats method parameters with ref/out keywords and names for method invocations.
	/// </summary>
	private static string FormatMethodParametersWithRefKind(IEnumerable<MethodParameter> parameters)
		=> string.Join(", ", parameters.Select(p => $"{p.RefKind.GetString(true)}{p.Name}"));

	/// <summary>
	///     Appends a typed parameter list for indexer accesses, e.g. <c>T1, T2</c>.
	/// </summary>
	private static void AppendIndexerParameterTypes(StringBuilder sb,
		EquatableArray<MethodParameter> parameters)
	{
		bool first = true;
		foreach (MethodParameter p in parameters)
		{
			if (!first)
			{
				sb.Append(", ");
			}

			sb.AppendTypeOrWrapper(p.Type);
			first = false;
		}
	}

	/// <summary>
	///     Appends a constructor-argument list of the form
	///     <c>"p1", p1, "p2", p2</c>.
	/// </summary>
	private static void AppendIndexerParameterArguments(StringBuilder sb,
		EquatableArray<MethodParameter> parameters)
	{
		bool first = true;
		foreach (MethodParameter p in parameters)
		{
			if (!first)
			{
				sb.Append(", ");
			}

			sb.Append(p.ToNameOrWrapper());
			first = false;
		}
	}

	/// <summary>
	///     Emits variable declarations for the indexer getter access and matching setup:
	///     <code>var access = new IndexerGetterAccess&lt;T...&gt;(p, ...);
	///     mockRegistry.RegisterInteraction(access);
	///     var setup = mockRegistry.GetIndexerSetup&lt;IndexerSetup&lt;TValue, T...&gt;&gt;(access);</code>
	/// </summary>
#pragma warning disable S107 // Methods should not have too many parameters
	private static void EmitIndexerGetterAccessAndSetup(StringBuilder sb, string indent,
		string mockRegistry, string accessVarName, string setupVarName,
		Type propertyType, EquatableArray<MethodParameter> parameters,
		bool useFastBuffers = false, string? memberIdRef = null,
		string? setupMemberIdRef = null)
#pragma warning restore S107
	{
		sb.Append(indent).Append("global::Mockolate.Interactions.IndexerGetterAccess<");
		AppendIndexerParameterTypes(sb, parameters);
		sb.Append("> ").Append(accessVarName).Append(" = new(");
		AppendIndexerParameterArguments(sb, parameters);
		sb.Append(");").AppendLine();

		sb.Append(indent).Append("if (").Append(mockRegistry).Append(".Behavior.SkipInteractionRecording == false)").AppendLine();
		sb.Append(indent).Append("{").AppendLine();
		if (useFastBuffers && memberIdRef is not null)
		{
			sb.Append(indent).Append("\t((global::Mockolate.Interactions.FastIndexerGetterBuffer<");
			AppendIndexerParameterTypes(sb, parameters);
			sb.Append(">)((global::Mockolate.Interactions.FastMockInteractions)").Append(mockRegistry)
				.Append(".Interactions).Buffers[").Append(memberIdRef).Append("]!).Append(")
				.Append(accessVarName).Append(");").AppendLine();
		}
		else
		{
			sb.Append(indent).Append('\t').Append(mockRegistry).Append(".RegisterInteraction(").Append(accessVarName).Append(");")
				.AppendLine();
		}

		sb.Append(indent).Append("}").AppendLine();

		EmitIndexerSetupLookup(sb, indent, mockRegistry, accessVarName, setupVarName, propertyType, parameters,
			setupMemberIdRef ?? memberIdRef);
	}

	/// <summary>
	///     Emits variable declarations for the indexer setter access and matching setup.
	/// </summary>
#pragma warning disable S107 // Methods should not have too many parameters
	private static void EmitIndexerSetterAccessAndSetup(StringBuilder sb, string indent,
		string mockRegistry, string accessVarName, string setupVarName,
		Type propertyType, EquatableArray<MethodParameter> parameters,
		bool useFastBuffers = false, string? memberIdRef = null,
		string? setupMemberIdRef = null)
#pragma warning restore S107
	{
		sb.Append(indent).Append("global::Mockolate.Interactions.IndexerSetterAccess<");
		AppendIndexerParameterTypes(sb, parameters);
		sb.Append(", ").AppendTypeOrWrapper(propertyType).Append("> ").Append(accessVarName).Append(" = new(");
		AppendIndexerParameterArguments(sb, parameters);
		sb.Append(", value);").AppendLine();

		sb.Append(indent).Append("if (").Append(mockRegistry).Append(".Behavior.SkipInteractionRecording == false)").AppendLine();
		sb.Append(indent).Append("{").AppendLine();
		if (useFastBuffers && memberIdRef is not null)
		{
			sb.Append(indent).Append("\t((global::Mockolate.Interactions.FastIndexerSetterBuffer<");
			AppendIndexerParameterTypes(sb, parameters);
			sb.Append(", ").AppendTypeOrWrapper(propertyType)
				.Append(">)((global::Mockolate.Interactions.FastMockInteractions)").Append(mockRegistry)
				.Append(".Interactions).Buffers[").Append(memberIdRef).Append("]!).Append(")
				.Append(accessVarName).Append(");").AppendLine();
		}
		else
		{
			sb.Append(indent).Append('\t').Append(mockRegistry).Append(".RegisterInteraction(").Append(accessVarName).Append(");")
				.AppendLine();
		}

		sb.Append(indent).Append("}").AppendLine();

		// Setup-side dispatch: indexer setups are always indexed under the GETTER member id (they apply to both
		// directions). Setter call sites pass the getter id via setupMemberIdRef; getters reuse memberIdRef.
		EmitIndexerSetupLookup(sb, indent, mockRegistry, accessVarName, setupVarName, propertyType, parameters,
			setupMemberIdRef);
	}

	/// <summary>
	///     Emits the indexer-setup lookup variable. When <paramref name="memberIdRef" /> is provided the lookup
	///     scans the lock-free <c>GetIndexerSetupSnapshot</c> array first (default-scope fast path), and falls back
	///     to the closure-free <c>GetIndexerSetup&lt;T&gt;(access)</c> overload for scenario-scoped setups.
	/// </summary>
#pragma warning disable S107 // Methods should not have too many parameters
	private static void EmitIndexerSetupLookup(StringBuilder sb, string indent,
		string mockRegistry, string accessVarName, string setupVarName,
		Type propertyType, EquatableArray<MethodParameter> parameters, string? memberIdRef)
#pragma warning restore S107
	{
		StringBuilder typedSetup = new("global::Mockolate.Setup.IndexerSetup<");
		typedSetup.AppendTypeOrWrapper(propertyType);
		foreach (MethodParameter p in parameters)
		{
			typedSetup.Append(", ").AppendTypeOrWrapper(p.Type);
		}

		typedSetup.Append('>');
		string typedSetupName = typedSetup.ToString();

		if (memberIdRef is null)
		{
			// Legacy path: no fast-buffer dispatch, fall straight through to the closure-free
			// access-keyed lookup (matches pre-D-refactor emission shape).
			sb.Append(indent).Append(typedSetupName).Append("? ").Append(setupVarName).Append(" = ")
				.Append(mockRegistry).Append(".GetIndexerSetup<").Append(typedSetupName).Append(">(")
				.Append(accessVarName).Append(");").AppendLine();
			return;
		}

		string snapshotVar = "snapshot_" + setupVarName;
		string indexVar = "i_" + setupVarName;
		string itemVar = "s_" + setupVarName;
		sb.Append(indent).Append(typedSetupName).Append("? ").Append(setupVarName).Append(" = null;").AppendLine();
		sb.Append(indent).Append("if (string.IsNullOrEmpty(").Append(mockRegistry).Append(".Scenario))").AppendLine();
		sb.Append(indent).Append('{').AppendLine();
		sb.Append(indent).Append("\tglobal::Mockolate.Setup.IndexerSetup[]? ").Append(snapshotVar)
			.Append(" = ").Append(mockRegistry).Append(".GetIndexerSetupSnapshot(").Append(memberIdRef).Append(");")
			.AppendLine();
		sb.Append(indent).Append("\tif (").Append(snapshotVar).Append(" is not null)").AppendLine();
		sb.Append(indent).Append("\t{").AppendLine();
		sb.Append(indent).Append("\t\tfor (int ").Append(indexVar).Append(" = ").Append(snapshotVar)
			.Append(".Length - 1; ").Append(indexVar).Append(" >= 0; ").Append(indexVar).Append("--)").AppendLine();
		sb.Append(indent).Append("\t\t{").AppendLine();
		sb.Append(indent).Append("\t\t\tif (").Append(snapshotVar).Append('[').Append(indexVar)
			.Append("] is ").Append(typedSetupName).Append(' ').Append(itemVar)
			.Append(" && ((global::Mockolate.Setup.IInteractiveIndexerSetup)").Append(itemVar)
			.Append(").Matches(").Append(accessVarName).Append("))").AppendLine();
		sb.Append(indent).Append("\t\t\t{").AppendLine();
		sb.Append(indent).Append("\t\t\t\t").Append(setupVarName).Append(" = ").Append(itemVar)
			.Append(';').AppendLine();
		sb.Append(indent).Append("\t\t\t\tbreak;").AppendLine();
		sb.Append(indent).Append("\t\t\t}").AppendLine();
		sb.Append(indent).Append("\t\t}").AppendLine();
		sb.Append(indent).Append("\t}").AppendLine();
		sb.Append(indent).Append('}').AppendLine();
		sb.Append(indent).Append(setupVarName).Append(" ??= ").Append(mockRegistry)
			.Append(".GetIndexerSetup<").Append(typedSetupName).Append(">(").Append(accessVarName).Append(");")
			.AppendLine();
	}

	/// <summary>
	///     Formats indexer parameters as comma-separated names.
	/// </summary>
	private static string FormatIndexerParametersAsNames(EquatableArray<MethodParameter> parameters)
		=> string.Join(", ", parameters.Select(p => p.Name));

	/// <summary>
	///     Formats parameters with type and name (e.g., "int value, string name").
	/// </summary>
	private static string FormatParametersWithTypeAndName(IEnumerable<MethodParameter> parameters)
		=> string.Join(", ", parameters.Select(p => $"{p.Type.Fullname} {p.Name}"));

	/// <summary>
	///     Formats parameters as names only (e.g., "value1, value2").
	/// </summary>
	private static string FormatParametersAsNames(IEnumerable<MethodParameter> parameters)
		=> string.Join(", ", parameters.Select(p => p.Name));

	/// <summary>
	///     Appends a NamedParameter with nullable handling.
	/// </summary>
	private static void AppendNamedParameter(StringBuilder sb, MethodParameter parameter)
	{
		bool useCovarianceAdapter = parameter.RefKind == RefKind.None;
		if (useCovarianceAdapter)
		{
			// Setup parameter is IParameter<T> (or nullable) — use CovariantParameterAdapter to support covariant
			// widening (e.g. passing an IParameter<Derived> where IParameter<Base> is expected).
			sb.Append("CovariantParameterAdapter<");
			sb.AppendTypeOrWrapper(parameter.Type);
			sb.Append(">.Wrap(");
		}
		else
		{
			// out/ref setup parameters use IOutParameter<T> / IRefParameter<T>, which don't inherit from
			// IParameter<T> — covariance isn't applicable, so keep the direct IParameterMatch<T> cast.
			sb.Append("(global::Mockolate.Parameters.IParameterMatch<");
			sb.AppendTypeOrWrapper(parameter.Type);
			sb.Append(">)(");
		}

		sb.Append(parameter.Name);
		if (parameter.CanUseNullableParameterOverload())
		{
			if (parameter.HasExplicitDefaultValue)
			{
				sb.Append(" ?? global::Mockolate.It.Is<").Append(parameter.ToNullableType()).Append(">(")
					.Append(parameter.ExplicitDefaultValue).Append(")");
			}
			else
			{
				sb.Append(" ?? global::Mockolate.It.IsNull<").Append(parameter.ToNullableType()).Append(">(\"null\")");
			}
		}

		sb.Append(")");
	}

	/// <summary>
	///     Appends a NamedParameter wrapping an explicit value with <c>It.Is&lt;T&gt;</c>.
	/// </summary>
	private static void AppendNamedValueParameter(StringBuilder sb, MethodParameter parameter)
		=> AppendNamedValueParameter(sb, parameter, parameter.Name);

	/// <summary>
	///     Appends a NamedParameter wrapping an explicit value with <c>It.Is&lt;T&gt;</c>, using the given variable reference
	///     name.
	/// </summary>
	private static void AppendNamedValueParameter(StringBuilder sb, MethodParameter parameter, string paramRef)
	{
		sb.Append("(global::Mockolate.Parameters.IParameterMatch<");
		sb.AppendTypeOrWrapper(parameter.Type);
		sb.Append(">)global::Mockolate.It.Is<")
			.Append(parameter.ToNullableType()).Append(">(").Append(paramRef).Append(", ");
		if (parameter.Type.SpecialType == SpecialType.System_String)
		{
			sb.Append("$\"\\\"{").Append(paramRef).Append("}\\\"\"");
		}
		else if (parameter.Type.CanBeNullable)
		{
			sb.Append(paramRef).Append(" is null ? \"null\" : ");
			if (parameter.Type.IsFormattable)
			{
				sb.Append("((global::System.IFormattable)").Append(paramRef).Append(").ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)");
			}
			else
			{
				sb.Append(paramRef).Append(".ToString()");
			}
		}
		else if (parameter.Type.IsFormattable)
		{
			sb.Append("((global::System.IFormattable)").Append(paramRef)
				.Append(").ToString(null, global::System.Globalization.CultureInfo.InvariantCulture)");
		}
		else
		{
			sb.Append(paramRef).Append(".ToString()");
		}

		sb.Append(")");
	}

	private static string CreateUniqueParameterName(EquatableArray<MethodParameter> parameters, string name)
	{
		string usedName = name;
#pragma warning disable S1994
		for (int index = 1; parameters.Any(x => x.Name == usedName); index++)
		{
			usedName = $"{usedName}_{index}";
		}
#pragma warning restore S1994

		return usedName;
	}

	private static string CreateUniquePropertyName(Class @class, string initialValue)
	{
		string propertyName = initialValue;
		if (@class.HasReservedName(propertyName))
		{
			propertyName = $"Mockolate_{initialValue}";
		}

		if (@class.HasReservedName(propertyName))
		{
			int index = 1;
			do
			{
				propertyName = $"Mockolate_{initialValue}__" + index++;
			} while (@class.HasReservedName(propertyName));
		}

		return propertyName;
	}

	/// <summary>
	///     Rewrites every self-closing <c>&lt;see cref="X" /&gt;</c> inside <paramref name="source" />
	///     to <c>&lt;see cref="X"&gt;Display&lt;/see&gt;</c>, where <c>Display</c> is a simplified
	///     version of the cref (outer namespace and enclosing types stripped, inner namespace
	///     qualifiers inside generic arguments / parameter lists stripped to their rightmost
	///     segment, and cref-style <c>{T}</c> generics rendered as <c>&amp;lt;T&amp;gt;</c>).
	///     This keeps the IDE/docs link intact while making the rendered prose shorter and avoiding
	///     the <c>Type.Type(...)</c> duplication that constructor crefs otherwise show.
	/// </summary>
	/// <remarks>
	///     Tags that already carry inner text (<c>&lt;see cref="X"&gt;...&lt;/see&gt;</c>) are left
	///     untouched so callers can override the default display when needed.
	/// </remarks>
	internal static string ExpandCrefs(string source)
	{
		const string OpenTag = "<see cref=\"";
		// Many of the smaller generator outputs (ActionFunc.g.cs, ReturnsThrowsAsyncExtensions.g.cs,
		// MockBehaviorExtensions.g.cs) carry no self-closing cref tags. Exit before the StringBuilder
		// is allocated and the source is rewalked.
		if (source.IndexOf(OpenTag, StringComparison.Ordinal) < 0)
		{
			return source;
		}

		int searchFrom = 0;
		int copiedUpTo = 0;
		StringBuilder? result = null;
		while (true)
		{
			int start = source.IndexOf(OpenTag, searchFrom, StringComparison.Ordinal);
			if (start < 0)
			{
				break;
			}

			int crefStart = start + OpenTag.Length;
			int crefEnd = source.IndexOf('"', crefStart);
			if (crefEnd < 0)
			{
				break;
			}

			int after = crefEnd + 1;
			while (after < source.Length && source[after] == ' ')
			{
				after++;
			}

			if (after + 1 < source.Length && source[after] == '/' && source[after + 1] == '>')
			{
				string cref = source.Substring(crefStart, crefEnd - crefStart);
				string display = SimplifyCrefForDisplay(cref);
				result ??= new StringBuilder(source.Length + 64);
				result.Append(source, copiedUpTo, start - copiedUpTo);
				result.Append(OpenTag).Append(cref).Append("\">").Append(display).Append("</see>");
				copiedUpTo = after + 2;
				searchFrom = after + 2;
			}
			else
			{
				searchFrom = crefEnd + 1;
			}
		}

		if (result is null)
		{
			return source;
		}

		result.Append(source, copiedUpTo, source.Length - copiedUpTo);
		return result.ToString();
	}

	/// <summary>
	///     Derives a short display form from a cref value.
	///     <list type="number">
	///         <item>Strips every <c>global::</c> prefix.</item>
	///         <item>
	///             Keeps everything from the last <c>.</c> that precedes the first <c>{</c> or
	///             <c>(</c> — i.e. drops the outer namespace / enclosing-type qualifiers but
	///             preserves a trailing <c>Type.Member</c> chain when no brackets are present.
	///         </item>
	///         <item>
	///             Inside the first <c>{…}</c> / <c>(…)</c> and everything after it, reduces each
	///             dotted identifier chain to its rightmost segment (so
	///             <c>(System.Func{object?[], bool}, string)</c> becomes
	///             <c>(Func{object?[], bool}, string)</c>).
	///         </item>
	///         <item>
	///             Converts cref-style <c>{</c>/<c>}</c> generics to <c>&amp;lt;</c>/<c>&amp;gt;</c>
	///             so the rendered text shows actual angle brackets.
	///         </item>
	///     </list>
	/// </summary>
	private static string SimplifyCrefForDisplay(string cref)
	{
		string stripped = cref.Replace("global::", string.Empty);
		int firstBracket = stripped.IndexOfAny(['{', '(',]);
		int searchEnd = firstBracket < 0 ? stripped.Length : firstBracket;
		int lastDot = searchEnd > 0 ? stripped.LastIndexOf('.', searchEnd - 1) : -1;
		string simplified = lastDot >= 0 ? stripped.Substring(lastDot + 1) : stripped;
		simplified = StripInnerNamespaces(simplified);
		return simplified.Replace("{", "&lt;").Replace("}", "&gt;");
	}

	/// <summary>
	///     Within the portion of <paramref name="value" /> that starts at the first <c>{</c> or
	///     <c>(</c>, reduces every dotted identifier chain (e.g. <c>System.Collections.Generic.List</c>)
	///     to its rightmost segment. The head preceding that first bracket is left untouched so
	///     a legitimate <c>Type.Member</c> prefix is preserved.
	/// </summary>
	private static string StripInnerNamespaces(string value)
	{
		int firstBracket = value.IndexOfAny(['{', '(',]);
		if (firstBracket < 0)
		{
			return value;
		}

		StringBuilder sb = new(value.Length);
		sb.Append(value, 0, firstBracket);
		int i = firstBracket;
		while (i < value.Length)
		{
			char c = value[i];
			if (IsIdentifierStart(c))
			{
				int lastIdStart = i;
				while (i < value.Length && (IsIdentifierPart(value[i]) || value[i] == '.'))
				{
					if (value[i] == '.')
					{
						lastIdStart = i + 1;
					}

					i++;
				}

				sb.Append(value, lastIdStart, i - lastIdStart);
			}
			else
			{
				sb.Append(c);
				i++;
			}
		}

		return sb.ToString();

		static bool IsIdentifierStart(char c)
		{
			return char.IsLetter(c) || c == '_';
		}

		static bool IsIdentifierPart(char c)
		{
			return char.IsLetterOrDigit(c) || c == '_';
		}
	}

	extension(Accessibility accessibility)
	{
		internal string ToVisibilityString()
			=> accessibility switch
			{
				Accessibility.Protected => "protected",
				Accessibility.Internal => "internal",
				Accessibility.ProtectedOrInternal => "protected",
				Accessibility.Public => "public",
				Accessibility.ProtectedAndInternal => "private protected",
				_ => "private",
			};
	}

	extension(RefKind refKind)
	{
		internal string GetString(bool replaceRefReadonlyWithIn = false)
			=> refKind switch
			{
				RefKind.In => "in ",
				RefKind.Out => "out ",
				RefKind.Ref => "ref ",
				RefKind.RefReadOnlyParameter => replaceRefReadonlyWithIn ? "in " : "ref readonly ",
				_ => "",
			};
	}

	extension(string value)
	{
		private string EscapeForXmlDoc()
			=> value.Replace('<', '{').Replace('>', '}');
	}

	extension(StringBuilder sb)
	{
		/// <summary>
		///     Appends XML documentation summary tags with the given text.
		/// </summary>
		private void AppendXmlSummary(string summaryText, string indent = "\t\t")
		{
			sb.Append(indent).Append("/// <summary>").AppendLine();
			sb.Append(indent).Append("///     ").Append(summaryText).AppendLine();
			sb.Append(indent).Append("/// </summary>").AppendLine();
		}

		/// <summary>
		///     Appends XML documentation remarks tags with the given text.
		/// </summary>
		private void AppendXmlRemarks(string remarksText, string indent = "\t\t")
		{
			sb.Append(indent).Append("/// <remarks>").AppendLine();
			sb.Append(indent).Append("///     ").Append(remarksText).AppendLine();
			sb.Append(indent).Append("/// </remarks>").AppendLine();
		}

		/// <summary>
		///     Appends an XML documentation <c>&lt;remarks&gt;</c> block consisting of several pre-formatted lines.
		/// </summary>
		private void AppendXmlRemarks(string[] lines, string indent = "\t\t")
		{
			if (lines.Length == 0)
			{
				return;
			}

			sb.Append(indent).Append("/// <remarks>").AppendLine();
			for (int i = 0; i < lines.Length; i++)
			{
				sb.Append(indent).Append("///     ").Append(lines[i]);
				if (i < lines.Length - 1)
				{
					sb.Append("<br />");
				}

				sb.AppendLine();
			}

			sb.Append(indent).Append("/// </remarks>").AppendLine();
		}

		/// <summary>
		///     Appends an XML documentation <c>&lt;param&gt;</c> tag with the given name and description.
		/// </summary>
		private void AppendXmlParam(string name, string description, string indent = "\t\t")
			=> sb.Append(indent).Append("/// <param name=\"").Append(name).Append("\">")
				.Append(description).Append("</param>").AppendLine();

		/// <summary>
		///     Appends an XML documentation <c>&lt;typeparam&gt;</c> tag with the given name and description.
		/// </summary>
		private void AppendXmlTypeParam(string name, string description, string indent = "\t\t")
			=> sb.Append(indent).Append("/// <typeparam name=\"").Append(name).Append("\">")
				.Append(description).Append("</typeparam>").AppendLine();

		/// <summary>
		///     Appends an XML documentation <c>&lt;returns&gt;</c> tag with the given text.
		/// </summary>
		private void AppendXmlReturns(string returnsText, string indent = "\t\t")
			=> sb.Append(indent).Append("/// <returns>").Append(returnsText).Append("</returns>").AppendLine();

		/// <summary>
		///     Appends an XML documentation <c>&lt;exception&gt;</c> tag with the given <paramref name="cref" /> and text.
		/// </summary>
		private void AppendXmlException(string cref, string text, string indent = "\t\t")
			=> sb.Append(indent).Append("/// <exception cref=\"").Append(cref).Append("\">")
				.Append(text).Append("</exception>").AppendLine();
	}
}
#pragma warning restore S3776 // Cognitive Complexity of methods should not be too high
