using System.Text;
using Microsoft.CodeAnalysis;

namespace Mockolate.SourceGenerators.Sources;

#pragma warning disable S3776 // Cognitive Complexity of methods should not be too high
internal static partial class Sources
{
	private static StringBuilder InitializeBuilder()
	{
		StringBuilder sb = new();
		sb.AppendLine("""
		              //----------------------
		              // <auto-generated>
		              //     This code was generated by the Mockolate source generator.
		              //
		              //     Changes to this file may cause incorrect behavior and
		              //     will be lost if the code is regenerated!
		              // </auto-generated>
		              //----------------------
		              """);

		sb.AppendLine();
		return sb;
	}

	/// <summary>
	///     Creates the static <c>Mock</c> class with the <c>Create</c> methods to create new mocks.
	/// </summary>
	public static string MockClass()
	{
		StringBuilder sb = InitializeBuilder();

		int maxNumberOfArguments = 9;
		sb.AppendLine("""
		              namespace Mockolate;

		              #nullable enable
		              /// <summary>
		              ///     Create new mocks by calling <c>Mock.Create&lt;T&gt;()</c>.<br />
		              ///     You can specify up to eight additional interfaces that the mock will also implement.
		              /// </summary>
		              /// <remarks>
		              ///     If your type is a class without default constructor, you can provide constructor parameters using <see cref="BaseClass.WithConstructorParameters(object?[])" />.
		              ///     You can also provide a <see cref="global::Mockolate.MockBehavior"/> parameter to customize how the mock should behave in certain scenarios.
		              /// </remarks>
		              internal static partial class Mock
		              {
		              """);
		
		
		
		sb.AppendLine($$"""
		              	/// <summary>
		              	///     Create a new mock for <typeparamref name="T" /> with the default <see cref="global::Mockolate.MockBehavior" />.
		              	/// </summary>
		              	/// <typeparam name="T">Type to mock, which can be an interface or a class.</typeparam>
		              	/// <remarks>
		              	///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
		              	/// </remarks>
		              	extension<T>(T _)
		              	{
		              		/// <summary>
		              		///     Create a new mock for <typeparamref name="T" /> with the given <paramref name="mockBehavior" />.
		              		/// </summary>
		              		/// <typeparam name="T">Type to mock, which can be an interface or a class.</typeparam>
		              		/// <remarks>
		              		///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
		              		/// </remarks>
		              		[MockGenerator]
		              		public static T CreateMock(global::Mockolate.MockBehavior? mockBehavior = null, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              		{
		              			throw new global::System.NotSupportedException("This method is only meant to be used in the context of Mockolate and should not be called directly.");
		              		}
		              		/// <summary>
		              		///     Create a new mock for <typeparamref name="T" /> using the <paramref name="constructorParameters" /> with the given <paramref name="mockBehavior" />.
		              		/// </summary>
		              		/// <typeparam name="T">Type to mock, which can be an interface or a class.</typeparam>
		              		/// <remarks>
		              		///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
		              		/// </remarks>
		              		[MockGenerator]
		              		public static T CreateMock(global::Mockolate.BaseClass.ConstructorParameters? constructorParameters, global::Mockolate.MockBehavior? mockBehavior = null, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              		{
		              			throw new global::System.NotSupportedException("This method is only meant to be used in the context of Mockolate and should not be called directly.");
		              		}
		              	}
		              """);
		
		
		
		sb.AppendLine("""
		              	/// <summary>
		              	///     Create a new mock for <typeparamref name="T" /> with the default <see cref="global::Mockolate.MockBehavior" />.
		              	/// </summary>
		              	/// <typeparam name="T">Type to mock, which can be an interface or a class.</typeparam>
		              	/// <remarks>
		              	///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
		              	/// </remarks>
		              	[MockGenerator]
		              	public static T Create<T>(params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              		where T : class
		              	{
		              		ThrowIfNotMockable(typeof(T));

		              		return new MockGenerator().Get<T>(null, global::Mockolate.MockBehavior.Default, setups)
		              			?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T>. Did the source generator run correctly?");
		              	}
		              """);
		sb.AppendLine();
		sb.AppendLine("""
		              	/// <summary>
		              	///     Create a new mock for <typeparamref name="T" /> with the default <see cref="global::Mockolate.MockBehavior" />.
		              	/// </summary>
		              	/// <typeparam name="T">Type to mock, which can be an interface or a class.</typeparam>
		              	/// <remarks>
		              	///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
		              	/// </remarks>
		              	[MockGenerator]
		              	public static T Create<T>(global::Mockolate.BaseClass.ConstructorParameters constructorParameters, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              		where T : class
		              	{
		              		ThrowIfNotMockable(typeof(T));

		              		return new MockGenerator().Get<T>(constructorParameters, global::Mockolate.MockBehavior.Default, setups)
		              			?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T>. Did the source generator run correctly?");
		              	}
		              """);
		sb.AppendLine();
		sb.AppendLine("""
		              	/// <summary>
		              	///     Create a new mock for <typeparamref name="T" /> with the given <paramref name="mockBehavior" />.
		              	/// </summary>
		              	/// <typeparam name="T">Type to mock, which can be an interface or a class.</typeparam>
		              	/// <remarks>
		              	///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
		              	///     <para />
		              	///     The behavior of the mock regarding the setups and the actual calls is determined by the <see cref="global::Mockolate.MockBehavior" />.
		              	/// </remarks>
		              	[MockGenerator]
		              	public static T Create<T>(global::Mockolate.MockBehavior mockBehavior, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              		where T : class
		              	{
		              		ThrowIfNotMockable(typeof(T));
		              	
		              		return new MockGenerator().Get<T>(null, mockBehavior, setups)
		              			?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T>. Did the source generator run correctly?");
		              	}
		              """);
		sb.AppendLine();
		sb.AppendLine("""
		              	/// <summary>
		              	///     Create a new mock for <typeparamref name="T" /> with the given <paramref name="mockBehavior" />.
		              	/// </summary>
		              	/// <typeparam name="T">Type to mock, which can be an interface or a class.</typeparam>
		              	/// <remarks>
		              	///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
		              	///     <para />
		              	///     The behavior of the mock regarding the setups and the actual calls is determined by the <see cref="global::Mockolate.MockBehavior" />.
		              	/// </remarks>
		              	[MockGenerator]
		              	public static T Create<T>(global::Mockolate.BaseClass.ConstructorParameters constructorParameters, global::Mockolate.MockBehavior mockBehavior, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              		where T : class
		              	{
		              		ThrowIfNotMockable(typeof(T));
		              	
		              		return new MockGenerator().Get<T>(constructorParameters, mockBehavior, setups)
		              			?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T>. Did the source generator run correctly?");
		              	}
		              """);
		sb.AppendLine();
		for (int numberOfArguments = 1; numberOfArguments < maxNumberOfArguments; numberOfArguments++)
		{
			string types = GetGenericTypeParameters(numberOfArguments, 2);
			sb.AppendXmlSummary(
				$"Create a new mock for <typeparamref name=\"T\" /> that also implements {GetAdditionalInterfacesDescription(numberOfArguments)} with the default <see cref=\"global::Mockolate.MockBehavior\" />.", "\t");
			sb.AppendLine(
				"\t/// <typeparam name=\"T\">Type to mock, which can be an interface or a class.</typeparam>");
			sb.AppendTypeParamDocs(numberOfArguments, "Additional interface that is implemented by the mock.",
				startIndex: 2);

			sb.AppendLine($$"""
			                	/// <remarks>
			                	///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
			                	/// </remarks>
			                	[MockGenerator]
			                	public static T Create<T, {{types}}>(params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
			                		where T : class
			                	{
			                		ThrowIfNotMockable(typeof(T));

			                		return new MockGenerator().Get<T, {{types}}>(null, global::Mockolate.MockBehavior.Default, setups)
			                			?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T, {{types}}>. Did the source generator run correctly?");
			                	}
			                """);
			sb.AppendLine();

			sb.AppendXmlSummary(
				$"Create a new mock for <typeparamref name=\"T\" /> that also implements {GetAdditionalInterfacesDescription(numberOfArguments)} with the default <see cref=\"global::Mockolate.MockBehavior\" />.", "\t");
			sb.AppendLine(
				"\t/// <typeparam name=\"T\">Type to mock, which can be an interface or a class.</typeparam>");
			sb.AppendTypeParamDocs(numberOfArguments, "Additional interface that is implemented by the mock.",
				startIndex: 2);

			sb.AppendLine($$"""
			                	/// <remarks>
			                	///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
			                	/// </remarks>
			                	[MockGenerator]
			                	public static T Create<T, {{types}}>(global::Mockolate.BaseClass.ConstructorParameters constructorParameters, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
			                		where T : class
			                	{
			                		ThrowIfNotMockable(typeof(T));

			                		return new MockGenerator().Get<T, {{types}}>(constructorParameters, global::Mockolate.MockBehavior.Default, setups)
			                			?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T, {{types}}>. Did the source generator run correctly?");
			                	}
			                """);
			sb.AppendLine();

			sb.Append("\t/// <summary>").AppendLine();
			sb.Append("\t///     Create a new mock for <typeparamref name=\"T\" /> that also implements ")
				.Append(numberOfArguments > 1 ? "interfaces " : "interface ")
				.Append(string.Join(", ",
					Enumerable.Range(2, numberOfArguments - 1).Select(n => $"<typeparamref name=\"T{n}\" />")))
				.Append(numberOfArguments > 1 ? " and " : "")
				.Append("<typeparamref name=\"T").Append(numberOfArguments + 1).Append("\" />")
				.Append(" with the given <paramref name=\"mockBehavior\" />.").AppendLine();
			sb.Append("\t/// </summary>").AppendLine();
			sb.Append("\t/// <typeparam name=\"T\">Type to mock, which can be an interface or a class.</typeparam>")
				.AppendLine();
			for (int i = 2; i <= numberOfArguments + 1; i++)
			{
				sb.Append("\t/// <typeparam name=\"T").Append(i)
					.Append("\">Additional interface that is implemented by the mock.</typeparam>").AppendLine();
			}

			sb.AppendLine($$"""
			                	/// <remarks>
			                	///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
			                	/// </remarks>
			                	[MockGenerator]
			                	public static T Create<T, {{types}}>(global::Mockolate.MockBehavior mockBehavior, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
			                		where T : class
			                	{
			                		ThrowIfNotMockable(typeof(T));

			                		return new MockGenerator().Get<T, {{types}}>(null, mockBehavior, setups)
			                			?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T, {{types}}>. Did the source generator run correctly?");
			                	}
			                """);
			sb.AppendLine();

			sb.AppendXmlSummary(
				$"Create a new mock for <typeparamref name=\"T\" /> that also implements {GetAdditionalInterfacesDescription(numberOfArguments)} with the given <paramref name=\"mockBehavior\" />.", "\t");
			sb.AppendLine(
				"\t/// <typeparam name=\"T\">Type to mock, which can be an interface or a class.</typeparam>");
			sb.AppendTypeParamDocs(numberOfArguments, "Additional interface that is implemented by the mock.",
				startIndex: 2);

			sb.AppendLine($$"""
			                	/// <remarks>
			                	///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
			                	/// </remarks>
			                	[MockGenerator]
			                	public static T Create<T, {{types}}>(global::Mockolate.BaseClass.ConstructorParameters constructorParameters, global::Mockolate.MockBehavior mockBehavior, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
			                		where T : class
			                	{
			                		ThrowIfNotMockable(typeof(T));

			                		return new MockGenerator().Get<T, {{types}}>(constructorParameters, mockBehavior, setups)
			                			?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T, {{types}}>. Did the source generator run correctly?");
			                	}
			                """);
			sb.AppendLine();
		}

		sb.AppendLine("""
		              	/// <summary>
		              	///     A mock factory to create mocks with a common behavior.
		              	/// </summary>
		              	public partial class Factory
		              	{
		              		private global::Mockolate.MockBehavior _behavior;
		              		
		              		/// <inheritdoc cref="Factory" />
		              		public Factory(global::Mockolate.MockBehavior behavior)
		              		{
		              			_behavior = behavior;
		              		}
		              """);
		sb.AppendLine();
		sb.AppendLine("""
		              		/// <summary>
		              		///     Create a new mock for <typeparamref name="T" />.
		              		/// </summary>
		              		/// <typeparam name="T">Type to mock, which can be an interface or a class.</typeparam>
		              		/// <remarks>
		              		///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
		              		/// </remarks>
		              		[MockGenerator]
		              		public T Create<T>(params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              			where T : class
		              		{
		              			ThrowIfNotMockable(typeof(T));
		              		
		              			return new MockGenerator().Get<T>(null, _behavior, setups)
		              				?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T>. Did the source generator run correctly?");
		              		}
		              """);
		sb.AppendLine();
		sb.AppendLine("""
		              		/// <summary>
		              		///     Create a new mock for <typeparamref name="T" />.
		              		/// </summary>
		              		/// <typeparam name="T">Type to mock, which can be an interface or a class.</typeparam>
		              		/// <remarks>
		              		///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
		              		/// </remarks>
		              		[MockGenerator]
		              		public T Create<T>(global::Mockolate.BaseClass.ConstructorParameters constructorParameters, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              			where T : class
		              		{
		              			ThrowIfNotMockable(typeof(T));
		              		
		              			return new MockGenerator().Get<T>(constructorParameters, _behavior, setups)
		              				?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T>. Did the source generator run correctly?");
		              		}
		              """);
		for (int numberOfArguments = 1; numberOfArguments < maxNumberOfArguments; numberOfArguments++)
		{
			string types = GetGenericTypeParameters(numberOfArguments, 2);
			sb.AppendLine();
			sb.AppendXmlSummary(
				$"Create a new mock for <typeparamref name=\"T\" /> that also implements {GetAdditionalInterfacesDescription(numberOfArguments)}.", "\t\t");
			sb.AppendLine(
				"\t\t/// <typeparam name=\"T\">Type to mock, which can be an interface or a class.</typeparam>");
			sb.AppendTypeParamDocs(numberOfArguments, "Additional interface that is implemented by the mock.", "\t\t",
				2);

			sb.AppendLine($$"""
			                		/// <remarks>
			                		///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
			                		/// </remarks>
			                		[MockGenerator]
			                		public T Create<T, {{types}}>(params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
			                			where T : class
			                		{
			                			ThrowIfNotMockable(typeof(T));

			                			return new MockGenerator().Get<T, {{types}}>(null, _behavior, setups)
			                				?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T, {{types}}>. Did the source generator run correctly?");
			                		}
			                """);

			sb.AppendLine();
			sb.AppendXmlSummary(
				$"Create a new mock for <typeparamref name=\"T\" /> that also implements {GetAdditionalInterfacesDescription(numberOfArguments)}.", "\t\t");
			sb.AppendLine(
				"\t\t/// <typeparam name=\"T\">Type to mock, which can be an interface or a class.</typeparam>");
			sb.AppendTypeParamDocs(numberOfArguments, "Additional interface that is implemented by the mock.", "\t\t",
				2);

			sb.AppendLine($$"""
			                		/// <remarks>
			                		///     Any interface type can be used for mocking, but for classes, only abstract and virtual members can be mocked.
			                		/// </remarks>
			                		[MockGenerator]
			                		public T Create<T, {{types}}>(global::Mockolate.BaseClass.ConstructorParameters constructorParameters, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
			                			where T : class
			                		{
			                			ThrowIfNotMockable(typeof(T));

			                			return new MockGenerator().Get<T, {{types}}>(constructorParameters, _behavior, setups)
			                				?? throw new global::Mockolate.Exceptions.MockException("Could not generate Mock<T, {{types}}>. Did the source generator run correctly?");
			                		}
			                """);
		}

		sb.AppendLine("\t}");
		sb.AppendLine();

		sb.AppendLine("""
		              	/// <summary>
		              	///     Wraps a concrete instance with a mock proxy that intercepts and delegates method calls,
		              	///     supporting setup and verification on the wrapped instance.
		              	/// </summary>
		              	/// <typeparam name="T">Type to wrap, which must be an interface.</typeparam>
		              	/// <param name="instance">The concrete instance to wrap.</param>
		              	/// <param name="setups">Optional setup actions to configure the mock.</param>
		              	/// <remarks>
		              	///     When no setup is specified for a method, the call is delegated to the wrapped instance.
		              	///     Setup and verification work the same as with regular mocks.
		              	/// </remarks>
		              	[MockGenerator]
		              	public static T Wrap<T>(T instance, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              		where T : class
		              	{
		              		if (instance == null)
		              		{
		              			throw new global::System.ArgumentNullException(nameof(instance));
		              		}
		              	
		              		ThrowIfNotWrappable(typeof(T));
		              	
		              		return new MockGenerator().GetWrapped<T>(instance, global::Mockolate.MockBehavior.Default, setups)
		              			?? throw new global::Mockolate.Exceptions.MockException("Could not generate wrapped Mock<T>. Did the source generator run correctly?");
		              	}
		              """);
		sb.AppendLine();

		sb.AppendLine("""
		              	/// <summary>
		              	///     Wraps a concrete instance with a mock proxy that intercepts and delegates method calls,
		              	///     supporting setup and verification on the wrapped instance.
		              	/// </summary>
		              	/// <typeparam name="T">Type to wrap, which must be an interface.</typeparam>
		              	/// <param name="instance">The concrete instance to wrap.</param>
		              	/// <param name="mockBehavior">The behavior settings for the mock.</param>
		              	/// <param name="setups">Optional setup actions to configure the mock.</param>
		              	/// <remarks>
		              	///     When no setup is specified for a method, the call is delegated to the wrapped instance.
		              	///     Setup and verification work the same as with regular mocks.
		              	/// </remarks>
		              	[MockGenerator]
		              	public static T Wrap<T>(T instance, global::Mockolate.MockBehavior mockBehavior, params global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              		where T : class
		              	{
		              		if (instance == null)
		              		{
		              			throw new global::System.ArgumentNullException(nameof(instance));
		              		}
		              	
		              		ThrowIfNotWrappable(typeof(T));
		              	
		              		return new MockGenerator().GetWrapped<T>(instance, mockBehavior, setups)
		              			?? throw new global::Mockolate.Exceptions.MockException("Could not generate wrapped Mock<T>. Did the source generator run correctly?");
		              	}
		              """);
		sb.AppendLine();

		sb.AppendLine("""
		              	private static void ThrowIfNotMockable(global::System.Type type)
		              	{
		              		if (type.IsSealed && type.BaseType != typeof(global::System.MulticastDelegate))
		              		{
		              			throw new global::Mockolate.Exceptions.MockException($"Unable to mock type '{type.FullName ?? type.Name}'. The type is sealed and therefore not mockable.");
		              		}
		              	}
		              	
		              	private static void ThrowIfNotWrappable(global::System.Type type)
		              	{
		              		if (!type.IsInterface)
		              		{
		              			throw new global::Mockolate.Exceptions.MockException($"Unable to wrap type '{type.FullName ?? type.Name}'. When wrapping a concrete instance, only interfaces can be mocked.");
		              		}
		              	}
		              """);
		sb.AppendLine();

		sb.AppendLine("""
		              	private partial class MockGenerator
		              	{
		              		#pragma warning disable CS0649 // Field 'field' is never assigned to, and will always have its default value 'value' 
		              		private object? _value;
		              		#pragma warning restore CS0649

		              		partial void Generate<T>(global::Mockolate.BaseClass.ConstructorParameters? constructorParameters, global::Mockolate.MockBehavior mockBehavior, global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups, params global::System.Type[] types);
		              		partial void GenerateWrapped<T>(T instance, global::Mockolate.MockBehavior mockBehavior, global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups);

		              		public object? Get(global::Mockolate.BaseClass.ConstructorParameters? constructorParameters, global::Mockolate.MockBehavior mockBehavior, global::System.Type type)
		              		{
		              			Generate<object>(constructorParameters, mockBehavior, global::System.Array.Empty<global::System.Action<global::Mockolate.Setup.IMockSetup<object>>>(), type);
		              			return _value;
		              		}

		              		public T? Get<T>(global::Mockolate.BaseClass.ConstructorParameters? constructorParameters, global::Mockolate.MockBehavior mockBehavior, global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              			where T : class
		              		{
		              			Generate<T>(constructorParameters, mockBehavior, setups, typeof(T));
		              			return _value as T;
		              		}
		              """);
		for (int i = 1; i < maxNumberOfArguments; i++)
		{
			string types = string.Join(", ", Enumerable.Range(2, i).Select(n => $"T{n}"));
			string typeOfTypes = string.Join(", ", Enumerable.Range(2, i).Select(n => $"typeof(T{n})"));
			sb.AppendLine($$"""
			                		public T? Get<T, {{types}}>(global::Mockolate.BaseClass.ConstructorParameters? constructorParameters, global::Mockolate.MockBehavior mockBehavior, global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
			                			where T : class
			                		{
			                			Generate<T>(constructorParameters, mockBehavior, setups, typeof(T), {{typeOfTypes}});
			                			return _value as T;
			                		}
			                """);
		}

		sb.AppendLine();
		sb.AppendLine("""
		              		public T? GetWrapped<T>(T instance, global::Mockolate.MockBehavior mockBehavior, global::System.Action<global::Mockolate.Setup.IMockSetup<T>>[] setups)
		              			where T : class
		              		{
		              			GenerateWrapped<T>(instance, mockBehavior, setups);
		              			return _value as T;
		              		}
		              """);

		sb.AppendLine("""
		              	}
		              }
		              #nullable disable
		              """);
		return sb.ToString();
	}

	/// <summary>
	///     Creates the <c>MockGenerator</c> attribute.
	/// </summary>
	public static string MockGeneratorAttribute()
	{
		StringBuilder sb = InitializeBuilder();

		sb.AppendLine("""
		              namespace Mockolate;

		              /// <summary>
		              ///     Marks a method as a mock generator for its generic parameters.
		              /// </summary>
		              [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
		              internal class MockGeneratorAttribute : global::System.Attribute
		              {
		              }
		              """);
		return sb.ToString();
	}

	internal static string ToVisibilityString(this Accessibility accessibility)
		=> accessibility switch
		{
			Accessibility.Protected => "protected",
			Accessibility.Internal => "internal",
			Accessibility.ProtectedOrInternal => "protected",
			Accessibility.Public => "public",
			Accessibility.ProtectedAndInternal => "private protected",
			_ => "private",
		};

	internal static string GetString(this RefKind refKind, bool replaceRefReadonlyWithIn = false)
		=> refKind switch
		{
			RefKind.In => "in ",
			RefKind.Out => "out ",
			RefKind.Ref => "ref ",
			RefKind.RefReadOnlyParameter => replaceRefReadonlyWithIn ? "in " : "ref readonly ",
			_ => "",
		};

	private static string EscapeForXmlDoc(this string value)
		=> value.Replace('<', '{').Replace('>', '}');

	/// <summary>
	///     Generates a comma-separated list of generic type parameters (e.g., "T1, T2, T3").
	/// </summary>
	private static string GetGenericTypeParameters(int count, int startIndex = 1)
		=> string.Join(", ", Enumerable.Range(startIndex, count).Select(i => $"T{i}"));

	/// <summary>
	///     Generates a comma-separated list of generic type parameters with 'out' variance (e.g., "out T1, out T2").
	/// </summary>
	private static string GetOutGenericTypeParameters(int count, int startIndex = 1)
		=> string.Join(", ", Enumerable.Range(startIndex, count).Select(i => $"out T{i}"));

	/// <summary>
	///     Appends XML documentation summary tags with the given text.
	/// </summary>
	private static StringBuilder AppendXmlSummary(this StringBuilder sb, string summaryText, string indent = "\t\t")
	{
		sb.Append(indent).Append("/// <summary>").AppendLine();
		sb.Append(indent).Append("///     ").Append(summaryText).AppendLine();
		sb.Append(indent).Append("/// </summary>").AppendLine();
		return sb;
	}

	/// <summary>
	///     Appends XML documentation remarks tags with the given text.
	/// </summary>
	private static StringBuilder AppendXmlRemarks(this StringBuilder sb, string remarksText, string indent = "\t\t")
	{
		sb.Append(indent).Append("/// <remarks>").AppendLine();
		sb.Append(indent).Append("///     ").Append(remarksText).AppendLine();
		sb.Append(indent).Append("/// </remarks>").AppendLine();
		return sb;
	}

	/// <summary>
	///     Generates a descriptive text listing type parameters (e.g., "T1, T2 and T3" or just "T1").
	/// </summary>
	private static string GetTypeParametersDescription(int numberOfParameters, int startIndex = 1)
	{
		StringBuilder sb = new();
		for (int i = startIndex; i < startIndex + numberOfParameters - 1; i++)
		{
			if (i > startIndex)
			{
				sb.Append(", ");
			}

			sb.Append("<typeparamref name=\"T").Append(i).Append("\" />");
		}

		sb.Append(" and <typeparamref name=\"T").Append(startIndex + numberOfParameters - 1).Append("\" />");
		return sb.ToString();
	}

	/// <summary>
	///     Appends type parameter XML documentation for generic parameters.
	/// </summary>
	private static StringBuilder AppendTypeParamDocs(this StringBuilder sb, int count, string description,
		string indent = "\t", int startIndex = 1)
	{
		for (int i = startIndex; i < startIndex + count; i++)
		{
			sb.Append(indent).Append("/// <typeparam name=\"T").Append(i).Append("\">").Append(description)
				.AppendLine("</typeparam>");
		}

		return sb;
	}

	/// <summary>
	///     Generates description text for additional interfaces (e.g., "interface T2" or "interfaces T2, T3 and T4").
	/// </summary>
	private static string GetAdditionalInterfacesDescription(int numberOfArguments, int startIndex = 2)
	{
		if (numberOfArguments == 1)
		{
			return $"interface <typeparamref name=\"T{startIndex}\" />";
		}

		StringBuilder sb = new("interfaces ");
		for (int i = startIndex; i < startIndex + numberOfArguments - 1; i++)
		{
			if (i > startIndex)
			{
				sb.Append(", ");
			}

			sb.Append("<typeparamref name=\"T").Append(i).Append("\" />");
		}

		sb.Append(" and <typeparamref name=\"T").Append(startIndex + numberOfArguments - 1).Append("\" />");
		return sb.ToString();
	}
}
#pragma warning restore S3776 // Cognitive Complexity of methods should not be too high
